import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { DatabaseSync } from "node:sqlite"
import { EnvHttpProxyAgent, fetch } from "undici"

interface SourceManifest {
  readonly gameVersion: string
  readonly upstreamCommit: string
  readonly upstreamRepository: string
}

interface WeaponRow {
  readonly id: string
  readonly rarity: number
  readonly weapon_type: string
}

interface ArtifactSetRow {
  readonly id: string
  readonly set_bonuses_json: string
}

interface WeaponInventoryRecord {
  readonly id: string
  readonly label: string
  readonly rarity: number
  readonly weaponType: string
}

interface ArtifactSetInventoryRecord {
  readonly id: string
  readonly label: string
  readonly setBonuses: readonly number[]
}

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const projectRoot = join(packageRoot, "..", "..")
const gameDataRoot = join(projectRoot, "packages", "game-data")
const sourceManifestPath = join(gameDataRoot, "sources", "current.json")
// The pinned upstream snapshot contains this non-release test fixture. Keep the raw snapshot
// intact for provenance, but never copy it into the player-facing equipment catalog.
const excludedNonGenshinWeaponIds = new Set(["QuantumCatalyst"])

function calculateSha256(value: Uint8Array): string {
  return createHash("sha256").update(value).digest("hex")
}

function assertExactIds(
  expectedIds: readonly string[],
  localizedNames: Readonly<Record<string, string>>,
  kind: string
): void {
  const expected = new Set(expectedIds)
  const localized = new Set(Object.keys(localizedNames))
  const missing = expectedIds.filter((id) => !localized.has(id))
  const extra = [...localized].filter((id) => !expected.has(id))
  if (missing.length > 0 || extra.length > 0) {
    throw new Error(
      `${kind} localization IDs differ from the local game-data snapshot: ` +
        `missing=${missing.join(",") || "none"}; extra=${extra.join(",") || "none"}`
    )
  }
}

async function downloadJson(
  dispatcher: EnvHttpProxyAgent,
  url: string
): Promise<{ readonly bytes: Uint8Array; readonly value: Readonly<Record<string, string>> }> {
  const response = await fetch(url, { dispatcher, signal: AbortSignal.timeout(30_000) })
  if (!response.ok) throw new Error(`Unable to download ${url}: HTTP ${response.status}`)
  const bytes = new Uint8Array(await response.arrayBuffer())
  return {
    bytes,
    value: JSON.parse(new TextDecoder().decode(bytes)) as Readonly<Record<string, string>>
  }
}

async function downloadLocalizationAssets(
  localizationRoot: string
): Promise<
  readonly [
    { readonly bytes: Uint8Array; readonly value: Readonly<Record<string, string>> },
    { readonly bytes: Uint8Array; readonly value: Readonly<Record<string, string>> }
  ]
> {
  const dispatcher = new EnvHttpProxyAgent()
  try {
    return await Promise.all([
      downloadJson(dispatcher, `${localizationRoot}/weaponNames_gen.json`),
      downloadJson(dispatcher, `${localizationRoot}/artifactNames_gen.json`)
    ])
  } finally {
    await dispatcher.close()
  }
}

function renderGeneratedSource(
  manifest: SourceManifest,
  weaponNames: { readonly bytes: Uint8Array; readonly value: Readonly<Record<string, string>> },
  artifactNames: { readonly bytes: Uint8Array; readonly value: Readonly<Record<string, string>> },
  weapons: readonly WeaponInventoryRecord[],
  artifactSets: readonly ArtifactSetInventoryRecord[]
): string {
  const source = {
    artifactNameAggregatePath: "libs/gi/dm-localization/assets/locales/chs/artifactNames_gen.json",
    artifactNameAggregateSha256: calculateSha256(artifactNames.bytes),
    excludedNonGenshinWeaponIds: [...excludedNonGenshinWeaponIds],
    gameVersion: manifest.gameVersion,
    upstreamCommit: manifest.upstreamCommit,
    upstreamRepository: manifest.upstreamRepository,
    weaponNameAggregatePath: "libs/gi/dm-localization/assets/locales/chs/weaponNames_gen.json",
    weaponNameAggregateSha256: calculateSha256(weaponNames.bytes)
  }
  return [
    "// Generated by tools/generate-equipment-inventory.ts; do not edit by hand.",
    `export const equipmentInventorySource = ${JSON.stringify(source, null, 2)} as const`,
    "",
    `export const weaponInventoryGenerated = ${JSON.stringify(weapons, null, 2)} as const`,
    "",
    `export const artifactSetInventoryGenerated = ${JSON.stringify(artifactSets, null, 2)} as const`,
    ""
  ].join("\n")
}

const manifest = JSON.parse(readFileSync(sourceManifestPath, "utf8")) as SourceManifest
if (manifest.upstreamRepository !== "https://github.com/frzyc/genshin-optimizer") {
  throw new Error(`Unsupported equipment localization source: ${manifest.upstreamRepository}`)
}

const localizationRoot =
  `https://raw.githubusercontent.com/frzyc/genshin-optimizer/${manifest.upstreamCommit}` +
  "/libs/gi/dm-localization/assets/locales/chs"
const [weaponNames, artifactNames] = await downloadLocalizationAssets(localizationRoot)
const databasePath = join(gameDataRoot, "snapshots", manifest.gameVersion, "game-data.sqlite")
using database = new DatabaseSync(databasePath, { readOnly: true })
const weaponRows = database
  .prepare("SELECT id, rarity, weapon_type FROM weapons ORDER BY id")
  .all() as unknown as WeaponRow[]
const artifactSetRows = database
  .prepare("SELECT id, set_bonuses_json FROM artifact_sets ORDER BY id")
  .all() as unknown as ArtifactSetRow[]

const catalogWeaponRows = weaponRows.filter((weapon) => !excludedNonGenshinWeaponIds.has(weapon.id))
const catalogWeaponNames = Object.fromEntries(
  Object.entries(weaponNames.value).filter(([weaponId]) => !excludedNonGenshinWeaponIds.has(weaponId))
)

assertExactIds(catalogWeaponRows.map((weapon) => weapon.id), catalogWeaponNames, "Weapon")
assertExactIds(artifactSetRows.map((artifactSet) => artifactSet.id), artifactNames.value, "Artifact-set")

const weapons: readonly WeaponInventoryRecord[] = catalogWeaponRows.map((weapon) => ({
  id: weapon.id,
  label: catalogWeaponNames[weapon.id] ?? "",
  rarity: weapon.rarity,
  weaponType: weapon.weapon_type
}))
const artifactSets: readonly ArtifactSetInventoryRecord[] = artifactSetRows.map((artifactSet) => ({
  id: artifactSet.id,
  label: artifactNames.value[artifactSet.id] ?? "",
  setBonuses: JSON.parse(artifactSet.set_bonuses_json) as number[]
}))
const outputPath = join(packageRoot, "src", "equipment-inventory.generated.ts")
writeFileSync(outputPath, renderGeneratedSource(manifest, weaponNames, artifactNames, weapons, artifactSets))

console.log(`Generated ${weapons.length} weapons and ${artifactSets.length} artifact sets at ${outputPath}`)
