// Generated by tools/generate-registries.ts; do not edit by hand.
import type { CharacterCatalogPresentation } from "../catalog/types.js"

import { raidenDefinition as characterRaidenDefinition } from "../characters/raiden/definition.js"
import { travelerDefinition as characterTravelerDefinition } from "../characters/traveler/definition.js"
import { bennettDefinition as characterBennettDefinition } from "../characters/bennett/definition.js"
import { yelanDefinition as characterYelanDefinition } from "../characters/yelan/definition.js"
import { albedoDefinition as characterAlbedoDefinition } from "../characters/albedo/definition.js"
import { dehyaDefinition as characterDehyaDefinition } from "../characters/dehya/definition.js"
import { colleiDefinition as characterColleiDefinition } from "../characters/collei/definition.js"
import { xianglingDefinition as characterXianglingDefinition } from "../characters/xiangling/definition.js"
import { xingqiuDefinition as characterXingqiuDefinition } from "../characters/xingqiu/definition.js"
import { kaeyaDefinition as characterKaeyaDefinition } from "../characters/kaeya/definition.js"
import { lisaDefinition as characterLisaDefinition } from "../characters/lisa/definition.js"
import { sucroseDefinition as characterSucroseDefinition } from "../characters/sucrose/definition.js"
import { noelleDefinition as characterNoelleDefinition } from "../characters/noelle/definition.js"
import { chongyunDefinition as characterChongyunDefinition } from "../characters/chongyun/definition.js"
import { razorDefinition as characterRazorDefinition } from "../characters/razor/definition.js"
import { yanfeiDefinition as characterYanfeiDefinition } from "../characters/yanfei/definition.js"
import { kujouSaraDefinition as characterKujouSaraDefinition } from "../characters/kujou-sara/definition.js"
import { gorouDefinition as characterGorouDefinition } from "../characters/gorou/definition.js"
import { kavehDefinition as characterKavehDefinition } from "../characters/kaveh/definition.js"
import { gamingDefinition as characterGamingDefinition } from "../characters/gaming/definition.js"
import { chevreuseDefinition as characterChevreuseDefinition } from "../characters/chevreuse/definition.js"
import { ororonDefinition as characterOroronDefinition } from "../characters/ororon/definition.js"
import { lanYanDefinition as characterLanYanDefinition } from "../characters/lan-yan/definition.js"
import { kachinaDefinition as characterKachinaDefinition } from "../characters/kachina/definition.js"
import { dahliaDefinition as characterDahliaDefinition } from "../characters/dahlia/definition.js"
import { jeanDefinition as characterJeanDefinition } from "../characters/jean/definition.js"
import { xiaoDefinition as characterXiaoDefinition } from "../characters/xiao/definition.js"
import { aloyDefinition as characterAloyDefinition } from "../characters/aloy/definition.js"
import { kamisatoAyakaDefinition as characterKamisatoAyakaDefinition } from "../characters/kamisato-ayaka/definition.js"
import { escoffierDefinition as characterEscoffierDefinition } from "../characters/escoffier/definition.js"
import { qiqiDefinition as characterQiqiDefinition } from "../characters/qiqi/definition.js"
import { tighnariDefinition as characterTighnariDefinition } from "../characters/tighnari/definition.js"
import { yunJinDefinition as characterYunJinDefinition } from "../characters/yun-jin/definition.js"
import { zhongliDefinition as characterZhongliDefinition } from "../characters/zhongli/definition.js"
import { neuvilletteDefinition as characterNeuvilletteDefinition } from "../characters/neuvillette/definition.js"
import { nilouDefinition as characterNilouDefinition } from "../characters/nilou/definition.js"
import { dilucDefinition as characterDilucDefinition } from "../characters/diluc/definition.js"
import { thomaDefinition as characterThomaDefinition } from "../characters/thoma/definition.js"
import { arlecchinoDefinition as characterArlecchinoDefinition } from "../characters/arlecchino/definition.js"
import { cynoDefinition as characterCynoDefinition } from "../characters/cyno/definition.js"
import { beidouDefinition as characterBeidouDefinition } from "../characters/beidou/definition.js"
import { candaceDefinition as characterCandaceDefinition } from "../characters/candace/definition.js"
import { dionaDefinition as characterDionaDefinition } from "../characters/diona/definition.js"
import { eulaDefinition as characterEulaDefinition } from "../characters/eula/definition.js"
import { faruzanDefinition as characterFaruzanDefinition } from "../characters/faruzan/definition.js"
import { ganyuDefinition as characterGanyuDefinition } from "../characters/ganyu/definition.js"
import { kaedeharaKazuhaDefinition as characterKaedeharaKazuhaDefinition } from "../characters/kaedehara-kazuha/definition.js"
import { keqingDefinition as characterKeqingDefinition } from "../characters/keqing/definition.js"
import { kiraraDefinition as characterKiraraDefinition } from "../characters/kirara/definition.js"
import { kukiShinobuDefinition as characterKukiShinobuDefinition } from "../characters/kuki-shinobu/definition.js"
import { laylaDefinition as characterLaylaDefinition } from "../characters/layla/definition.js"
import { mikaDefinition as characterMikaDefinition } from "../characters/mika/definition.js"
import { ningguangDefinition as characterNingguangDefinition } from "../characters/ningguang/definition.js"
import { sethosDefinition as characterSethosDefinition } from "../characters/sethos/definition.js"
import { shenheDefinition as characterShenheDefinition } from "../characters/shenhe/definition.js"
import { ventiDefinition as characterVentiDefinition } from "../characters/venti/definition.js"
import { xinyanDefinition as characterXinyanDefinition } from "../characters/xinyan/definition.js"
import { amberDefinition as characterAmberDefinition } from "../characters/amber/definition.js"
import { barbaraDefinition as characterBarbaraDefinition } from "../characters/barbara/definition.js"
import { charlotteDefinition as characterCharlotteDefinition } from "../characters/charlotte/definition.js"
import { doriDefinition as characterDoriDefinition } from "../characters/dori/definition.js"
import { fischlDefinition as characterFischlDefinition } from "../characters/fischl/definition.js"
import { kleeDefinition as characterKleeDefinition } from "../characters/klee/definition.js"
import { lynetteDefinition as characterLynetteDefinition } from "../characters/lynette/definition.js"
import { nahidaDefinition as characterNahidaDefinition } from "../characters/nahida/definition.js"
import { naviaDefinition as characterNaviaDefinition } from "../characters/navia/definition.js"
import { rosariaDefinition as characterRosariaDefinition } from "../characters/rosaria/definition.js"
import { sayuDefinition as characterSayuDefinition } from "../characters/sayu/definition.js"
import { shikanoinHeizouDefinition as characterShikanoinHeizouDefinition } from "../characters/shikanoin-heizou/definition.js"
import { tartagliaDefinition as characterTartagliaDefinition } from "../characters/tartaglia/definition.js"
import { xianyunDefinition as characterXianyunDefinition } from "../characters/xianyun/definition.js"
import { yaeMikoDefinition as characterYaeMikoDefinition } from "../characters/yae-miko/definition.js"
import { yaoyaoDefinition as characterYaoyaoDefinition } from "../characters/yaoyao/definition.js"
import { chascaDefinition as characterChascaDefinition } from "../characters/chasca/definition.js"
import { ifaDefinition as characterIfaDefinition } from "../characters/ifa/definition.js"
import { citlaliDefinition as characterCitlaliDefinition } from "../characters/citlali/definition.js"
import { freminetDefinition as characterFreminetDefinition } from "../characters/freminet/definition.js"
import { alhaithamDefinition as characterAlhaithamDefinition } from "../characters/alhaitham/definition.js"
import { baizhuDefinition as characterBaizhuDefinition } from "../characters/baizhu/definition.js"
import { clorindeDefinition as characterClorindeDefinition } from "../characters/clorinde/definition.js"
import { iansanDefinition as characterIansanDefinition } from "../characters/iansan/definition.js"
import { aratakiIttoDefinition as characterAratakiIttoDefinition } from "../characters/arataki-itto/definition.js"
import { chioriDefinition as characterChioriDefinition } from "../characters/chiori/definition.js"
import { ainoDefinition as characterAinoDefinition } from "../characters/aino/definition.js"
import { monaDefinition as characterMonaDefinition } from "../characters/mona/definition.js"
import { huTaoDefinition as characterHuTaoDefinition } from "../characters/hu-tao/definition.js"
import { lyneyDefinition as characterLyneyDefinition } from "../characters/lyney/definition.js"
import { furinaDefinition as characterFurinaDefinition } from "../characters/furina/definition.js"
import { kamisatoAyatoDefinition as characterKamisatoAyatoDefinition } from "../characters/kamisato-ayato/definition.js"
import { jahodaDefinition as characterJahodaDefinition } from "../characters/jahoda/definition.js"
import { pruneDefinition as characterPruneDefinition } from "../characters/prune/definition.js"
import { varkaDefinition as characterVarkaDefinition } from "../characters/varka/definition.js"
import { lohenDefinition as characterLohenDefinition } from "../characters/lohen/definition.js"
import { wriothesleyDefinition as characterWriothesleyDefinition } from "../characters/wriothesley/definition.js"
import { emilieDefinition as characterEmilieDefinition } from "../characters/emilie/definition.js"
import { laumaDefinition as characterLaumaDefinition } from "../characters/lauma/definition.js"
import { flinsDefinition as characterFlinsDefinition } from "../characters/flins/definition.js"
import { linneaDefinition as characterLinneaDefinition } from "../characters/linnea/definition.js"
import { xilonenDefinition as characterXilonenDefinition } from "../characters/xilonen/definition.js"
import { sigewinneDefinition as characterSigewinneDefinition } from "../characters/sigewinne/definition.js"
import { columbinaDefinition as characterColumbinaDefinition } from "../characters/columbina/definition.js"
import { yoimiyaDefinition as characterYoimiyaDefinition } from "../characters/yoimiya/definition.js"
import { nicoleDefinition as characterNicoleDefinition } from "../characters/nicole/definition.js"
import { mavuikaDefinition as characterMavuikaDefinition } from "../characters/mavuika/definition.js"
import { wandererDefinition as characterWandererDefinition } from "../characters/wanderer/definition.js"
import { yumemizukiMizukiDefinition as characterYumemizukiMizukiDefinition } from "../characters/yumemizuki-mizuki/definition.js"
import { sandroneDefinition as characterSandroneDefinition } from "../characters/sandrone/definition.js"
import { skirkDefinition as characterSkirkDefinition } from "../characters/skirk/definition.js"
import { kinichDefinition as characterKinichDefinition } from "../characters/kinich/definition.js"
import { neferDefinition as characterNeferDefinition } from "../characters/nefer/definition.js"
import { ineffaDefinition as characterIneffaDefinition } from "../characters/ineffa/definition.js"
import { varesaDefinition as characterVaresaDefinition } from "../characters/varesa/definition.js"
import { illugaDefinition as characterIllugaDefinition } from "../characters/illuga/definition.js"
import { zibaiDefinition as characterZibaiDefinition } from "../characters/zibai/definition.js"
import { mualaniDefinition as characterMualaniDefinition } from "../characters/mualani/definition.js"
import { sangonomiyaKokomiDefinition as characterSangonomiyaKokomiDefinition } from "../characters/sangonomiya-kokomi/definition.js"
import { durinDefinition as characterDurinDefinition } from "../characters/durin/definition.js"
import { odetteDefinition as characterOdetteDefinition } from "../characters/odette/definition.js"
import { alyoshaDefinition as characterAlyoshaDefinition } from "../characters/alyosha/definition.js"

export const characterCatalogPresentation: readonly CharacterCatalogPresentation[] = [
  characterRaidenDefinition.catalog,
  characterTravelerDefinition.catalog,
  characterBennettDefinition.catalog,
  characterYelanDefinition.catalog,
  characterAlbedoDefinition.catalog,
  characterDehyaDefinition.catalog,
  characterColleiDefinition.catalog,
  characterXianglingDefinition.catalog,
  characterXingqiuDefinition.catalog,
  characterKaeyaDefinition.catalog,
  characterLisaDefinition.catalog,
  characterSucroseDefinition.catalog,
  characterNoelleDefinition.catalog,
  characterChongyunDefinition.catalog,
  characterRazorDefinition.catalog,
  characterYanfeiDefinition.catalog,
  characterKujouSaraDefinition.catalog,
  characterGorouDefinition.catalog,
  characterKavehDefinition.catalog,
  characterGamingDefinition.catalog,
  characterChevreuseDefinition.catalog,
  characterOroronDefinition.catalog,
  characterLanYanDefinition.catalog,
  characterKachinaDefinition.catalog,
  characterDahliaDefinition.catalog,
  characterJeanDefinition.catalog,
  characterXiaoDefinition.catalog,
  characterAloyDefinition.catalog,
  characterKamisatoAyakaDefinition.catalog,
  characterEscoffierDefinition.catalog,
  characterQiqiDefinition.catalog,
  characterTighnariDefinition.catalog,
  characterYunJinDefinition.catalog,
  characterZhongliDefinition.catalog,
  characterNeuvilletteDefinition.catalog,
  characterNilouDefinition.catalog,
  characterDilucDefinition.catalog,
  characterThomaDefinition.catalog,
  characterArlecchinoDefinition.catalog,
  characterCynoDefinition.catalog,
  characterBeidouDefinition.catalog,
  characterCandaceDefinition.catalog,
  characterDionaDefinition.catalog,
  characterEulaDefinition.catalog,
  characterFaruzanDefinition.catalog,
  characterGanyuDefinition.catalog,
  characterKaedeharaKazuhaDefinition.catalog,
  characterKeqingDefinition.catalog,
  characterKiraraDefinition.catalog,
  characterKukiShinobuDefinition.catalog,
  characterLaylaDefinition.catalog,
  characterMikaDefinition.catalog,
  characterNingguangDefinition.catalog,
  characterSethosDefinition.catalog,
  characterShenheDefinition.catalog,
  characterVentiDefinition.catalog,
  characterXinyanDefinition.catalog,
  characterAmberDefinition.catalog,
  characterBarbaraDefinition.catalog,
  characterCharlotteDefinition.catalog,
  characterDoriDefinition.catalog,
  characterFischlDefinition.catalog,
  characterKleeDefinition.catalog,
  characterLynetteDefinition.catalog,
  characterNahidaDefinition.catalog,
  characterNaviaDefinition.catalog,
  characterRosariaDefinition.catalog,
  characterSayuDefinition.catalog,
  characterShikanoinHeizouDefinition.catalog,
  characterTartagliaDefinition.catalog,
  characterXianyunDefinition.catalog,
  characterYaeMikoDefinition.catalog,
  characterYaoyaoDefinition.catalog,
  characterChascaDefinition.catalog,
  characterIfaDefinition.catalog,
  characterCitlaliDefinition.catalog,
  characterFreminetDefinition.catalog,
  characterAlhaithamDefinition.catalog,
  characterBaizhuDefinition.catalog,
  characterClorindeDefinition.catalog,
  characterIansanDefinition.catalog,
  characterAratakiIttoDefinition.catalog,
  characterChioriDefinition.catalog,
  characterAinoDefinition.catalog,
  characterMonaDefinition.catalog,
  characterHuTaoDefinition.catalog,
  characterLyneyDefinition.catalog,
  characterFurinaDefinition.catalog,
  characterKamisatoAyatoDefinition.catalog,
  characterJahodaDefinition.catalog,
  characterPruneDefinition.catalog,
  characterVarkaDefinition.catalog,
  characterLohenDefinition.catalog,
  characterWriothesleyDefinition.catalog,
  characterEmilieDefinition.catalog,
  characterLaumaDefinition.catalog,
  characterFlinsDefinition.catalog,
  characterLinneaDefinition.catalog,
  characterXilonenDefinition.catalog,
  characterSigewinneDefinition.catalog,
  characterColumbinaDefinition.catalog,
  characterYoimiyaDefinition.catalog,
  characterNicoleDefinition.catalog,
  characterMavuikaDefinition.catalog,
  characterWandererDefinition.catalog,
  characterYumemizukiMizukiDefinition.catalog,
  characterSandroneDefinition.catalog,
  characterSkirkDefinition.catalog,
  characterKinichDefinition.catalog,
  characterNeferDefinition.catalog,
  characterIneffaDefinition.catalog,
  characterVaresaDefinition.catalog,
  characterIllugaDefinition.catalog,
  characterZibaiDefinition.catalog,
  characterMualaniDefinition.catalog,
  characterSangonomiyaKokomiDefinition.catalog,
  characterDurinDefinition.catalog,
  characterOdetteDefinition.catalog,
  characterAlyoshaDefinition.catalog
]
