// Generated by tools/generate-registries.ts; do not edit by hand.
import type { CharacterCombatCoverage } from "../combat/types.js"

import { ainoCombatCoverage as characterAinoCoverage } from "../characters/aino/combat.js"
import { albedoCombatCoverage as characterAlbedoCoverage } from "../characters/albedo/combat.js"
import { alhaithamCombatCoverage as characterAlhaithamCoverage } from "../characters/alhaitham/combat.js"
import { aloyCombatCoverage as characterAloyCoverage } from "../characters/aloy/combat.js"
import { alyoshaCombatCoverage as characterAlyoshaCoverage } from "../characters/alyosha/combat.js"
import { amberCombatCoverage as characterAmberCoverage } from "../characters/amber/combat.js"
import { aratakiIttoCombatCoverage as characterAratakiIttoCoverage } from "../characters/arataki-itto/combat.js"
import { arlecchinoCombatCoverage as characterArlecchinoCoverage } from "../characters/arlecchino/combat.js"
import { baizhuCombatCoverage as characterBaizhuCoverage } from "../characters/baizhu/combat.js"
import { barbaraCombatCoverage as characterBarbaraCoverage } from "../characters/barbara/combat.js"
import { beidouCombatCoverage as characterBeidouCoverage } from "../characters/beidou/combat.js"
import { bennettCombatCoverage as characterBennettCoverage } from "../characters/bennett/combat.js"
import { candaceCombatCoverage as characterCandaceCoverage } from "../characters/candace/combat.js"
import { charlotteCombatCoverage as characterCharlotteCoverage } from "../characters/charlotte/combat.js"
import { chascaCombatCoverage as characterChascaCoverage } from "../characters/chasca/combat.js"
import { chevreuseCombatCoverage as characterChevreuseCoverage } from "../characters/chevreuse/combat.js"
import { chioriCombatCoverage as characterChioriCoverage } from "../characters/chiori/combat.js"
import { chongyunCombatCoverage as characterChongyunCoverage } from "../characters/chongyun/combat.js"
import { citlaliCombatCoverage as characterCitlaliCoverage } from "../characters/citlali/combat.js"
import { clorindeCombatCoverage as characterClorindeCoverage } from "../characters/clorinde/combat.js"
import { colleiCombatCoverage as characterColleiCoverage } from "../characters/collei/combat.js"
import { columbinaCombatCoverage as characterColumbinaCoverage } from "../characters/columbina/combat.js"
import { cynoCombatCoverage as characterCynoCoverage } from "../characters/cyno/combat.js"
import { dahliaCombatCoverage as characterDahliaCoverage } from "../characters/dahlia/combat.js"
import { dehyaCombatCoverage as characterDehyaCoverage } from "../characters/dehya/combat.js"
import { dilucCombatCoverage as characterDilucCoverage } from "../characters/diluc/combat.js"
import { dionaCombatCoverage as characterDionaCoverage } from "../characters/diona/combat.js"
import { doriCombatCoverage as characterDoriCoverage } from "../characters/dori/combat.js"
import { durinCombatCoverage as characterDurinCoverage } from "../characters/durin/combat.js"
import { emilieCombatCoverage as characterEmilieCoverage } from "../characters/emilie/combat.js"
import { escoffierCombatCoverage as characterEscoffierCoverage } from "../characters/escoffier/combat.js"
import { eulaCombatCoverage as characterEulaCoverage } from "../characters/eula/combat.js"
import { faruzanCombatCoverage as characterFaruzanCoverage } from "../characters/faruzan/combat.js"
import { fischlCombatCoverage as characterFischlCoverage } from "../characters/fischl/combat.js"
import { flinsCombatCoverage as characterFlinsCoverage } from "../characters/flins/combat.js"
import { freminetCombatCoverage as characterFreminetCoverage } from "../characters/freminet/combat.js"
import { furinaCombatCoverage as characterFurinaCoverage } from "../characters/furina/combat.js"
import { gamingCombatCoverage as characterGamingCoverage } from "../characters/gaming/combat.js"
import { ganyuCombatCoverage as characterGanyuCoverage } from "../characters/ganyu/combat.js"
import { gorouCombatCoverage as characterGorouCoverage } from "../characters/gorou/combat.js"
import { huTaoCombatCoverage as characterHuTaoCoverage } from "../characters/hu-tao/combat.js"
import { iansanCombatCoverage as characterIansanCoverage } from "../characters/iansan/combat.js"
import { ifaCombatCoverage as characterIfaCoverage } from "../characters/ifa/combat.js"
import { illugaCombatCoverage as characterIllugaCoverage } from "../characters/illuga/combat.js"
import { ineffaCombatCoverage as characterIneffaCoverage } from "../characters/ineffa/combat.js"
import { jahodaCombatCoverage as characterJahodaCoverage } from "../characters/jahoda/combat.js"
import { jeanCombatCoverage as characterJeanCoverage } from "../characters/jean/combat.js"
import { kachinaCombatCoverage as characterKachinaCoverage } from "../characters/kachina/combat.js"
import { kaedeharaKazuhaCombatCoverage as characterKaedeharaKazuhaCoverage } from "../characters/kaedehara-kazuha/combat.js"
import { kaeyaCombatCoverage as characterKaeyaCoverage } from "../characters/kaeya/combat.js"
import { kamisatoAyakaCombatCoverage as characterKamisatoAyakaCoverage } from "../characters/kamisato-ayaka/combat.js"
import { kamisatoAyatoCombatCoverage as characterKamisatoAyatoCoverage } from "../characters/kamisato-ayato/combat.js"
import { kavehCombatCoverage as characterKavehCoverage } from "../characters/kaveh/combat.js"
import { keqingCombatCoverage as characterKeqingCoverage } from "../characters/keqing/combat.js"
import { kinichCombatCoverage as characterKinichCoverage } from "../characters/kinich/combat.js"
import { kiraraCombatCoverage as characterKiraraCoverage } from "../characters/kirara/combat.js"
import { kleeCombatCoverage as characterKleeCoverage } from "../characters/klee/combat.js"
import { kujouSaraCombatCoverage as characterKujouSaraCoverage } from "../characters/kujou-sara/combat.js"
import { kukiShinobuCombatCoverage as characterKukiShinobuCoverage } from "../characters/kuki-shinobu/combat.js"
import { lanYanCombatCoverage as characterLanYanCoverage } from "../characters/lan-yan/combat.js"
import { laumaCombatCoverage as characterLaumaCoverage } from "../characters/lauma/combat.js"
import { laylaCombatCoverage as characterLaylaCoverage } from "../characters/layla/combat.js"
import { linneaCombatCoverage as characterLinneaCoverage } from "../characters/linnea/combat.js"
import { lisaCombatCoverage as characterLisaCoverage } from "../characters/lisa/combat.js"
import { lohenCombatCoverage as characterLohenCoverage } from "../characters/lohen/combat.js"
import { lynetteCombatCoverage as characterLynetteCoverage } from "../characters/lynette/combat.js"
import { lyneyCombatCoverage as characterLyneyCoverage } from "../characters/lyney/combat.js"
import { mavuikaCombatCoverage as characterMavuikaCoverage } from "../characters/mavuika/combat.js"
import { mikaCombatCoverage as characterMikaCoverage } from "../characters/mika/combat.js"
import { monaCombatCoverage as characterMonaCoverage } from "../characters/mona/combat.js"
import { mualaniCombatCoverage as characterMualaniCoverage } from "../characters/mualani/combat.js"
import { nahidaCombatCoverage as characterNahidaCoverage } from "../characters/nahida/combat.js"
import { naviaCombatCoverage as characterNaviaCoverage } from "../characters/navia/combat.js"
import { neferCombatCoverage as characterNeferCoverage } from "../characters/nefer/combat.js"
import { neuvilletteCombatCoverage as characterNeuvilletteCoverage } from "../characters/neuvillette/combat.js"
import { nicoleCombatCoverage as characterNicoleCoverage } from "../characters/nicole/combat.js"
import { nilouCombatCoverage as characterNilouCoverage } from "../characters/nilou/combat.js"
import { ningguangCombatCoverage as characterNingguangCoverage } from "../characters/ningguang/combat.js"
import { noelleCombatCoverage as characterNoelleCoverage } from "../characters/noelle/combat.js"
import { odetteCombatCoverage as characterOdetteCoverage } from "../characters/odette/combat.js"
import { ororonCombatCoverage as characterOroronCoverage } from "../characters/ororon/combat.js"
import { pruneCombatCoverage as characterPruneCoverage } from "../characters/prune/combat.js"
import { qiqiCombatCoverage as characterQiqiCoverage } from "../characters/qiqi/combat.js"
import { raidenCombatCoverage as characterRaidenCoverage } from "../characters/raiden/combat.js"
import { razorCombatCoverage as characterRazorCoverage } from "../characters/razor/combat.js"
import { rosariaCombatCoverage as characterRosariaCoverage } from "../characters/rosaria/combat.js"
import { sandroneCombatCoverage as characterSandroneCoverage } from "../characters/sandrone/combat.js"
import { sangonomiyaKokomiCombatCoverage as characterSangonomiyaKokomiCoverage } from "../characters/sangonomiya-kokomi/combat.js"
import { sayuCombatCoverage as characterSayuCoverage } from "../characters/sayu/combat.js"
import { sethosCombatCoverage as characterSethosCoverage } from "../characters/sethos/combat.js"
import { shenheCombatCoverage as characterShenheCoverage } from "../characters/shenhe/combat.js"
import { shikanoinHeizouCombatCoverage as characterShikanoinHeizouCoverage } from "../characters/shikanoin-heizou/combat.js"
import { sigewinneCombatCoverage as characterSigewinneCoverage } from "../characters/sigewinne/combat.js"
import { skirkCombatCoverage as characterSkirkCoverage } from "../characters/skirk/combat.js"
import { sucroseCombatCoverage as characterSucroseCoverage } from "../characters/sucrose/combat.js"
import { tartagliaCombatCoverage as characterTartagliaCoverage } from "../characters/tartaglia/combat.js"
import { thomaCombatCoverage as characterThomaCoverage } from "../characters/thoma/combat.js"
import { tighnariCombatCoverage as characterTighnariCoverage } from "../characters/tighnari/combat.js"
import { travelerCombatCoverage as characterTravelerCoverage } from "../characters/traveler/combat.js"
import { varesaCombatCoverage as characterVaresaCoverage } from "../characters/varesa/combat.js"
import { varkaCombatCoverage as characterVarkaCoverage } from "../characters/varka/combat.js"
import { ventiCombatCoverage as characterVentiCoverage } from "../characters/venti/combat.js"
import { wandererCombatCoverage as characterWandererCoverage } from "../characters/wanderer/combat.js"
import { wriothesleyCombatCoverage as characterWriothesleyCoverage } from "../characters/wriothesley/combat.js"
import { xianglingCombatCoverage as characterXianglingCoverage } from "../characters/xiangling/combat.js"
import { xianyunCombatCoverage as characterXianyunCoverage } from "../characters/xianyun/combat.js"
import { xiaoCombatCoverage as characterXiaoCoverage } from "../characters/xiao/combat.js"
import { xilonenCombatCoverage as characterXilonenCoverage } from "../characters/xilonen/combat.js"
import { xingqiuCombatCoverage as characterXingqiuCoverage } from "../characters/xingqiu/combat.js"
import { xinyanCombatCoverage as characterXinyanCoverage } from "../characters/xinyan/combat.js"
import { yaeMikoCombatCoverage as characterYaeMikoCoverage } from "../characters/yae-miko/combat.js"
import { yanfeiCombatCoverage as characterYanfeiCoverage } from "../characters/yanfei/combat.js"
import { yaoyaoCombatCoverage as characterYaoyaoCoverage } from "../characters/yaoyao/combat.js"
import { yelanCombatCoverage as characterYelanCoverage } from "../characters/yelan/combat.js"
import { yoimiyaCombatCoverage as characterYoimiyaCoverage } from "../characters/yoimiya/combat.js"
import { yumemizukiMizukiCombatCoverage as characterYumemizukiMizukiCoverage } from "../characters/yumemizuki-mizuki/combat.js"
import { yunJinCombatCoverage as characterYunJinCoverage } from "../characters/yun-jin/combat.js"
import { zhongliCombatCoverage as characterZhongliCoverage } from "../characters/zhongli/combat.js"
import { zibaiCombatCoverage as characterZibaiCoverage } from "../characters/zibai/combat.js"

export const characterCombatCoverageRegistry: readonly CharacterCombatCoverage[] = [
  characterAinoCoverage,
  characterAlbedoCoverage,
  characterAlhaithamCoverage,
  characterAloyCoverage,
  characterAlyoshaCoverage,
  characterAmberCoverage,
  characterAratakiIttoCoverage,
  characterArlecchinoCoverage,
  characterBaizhuCoverage,
  characterBarbaraCoverage,
  characterBeidouCoverage,
  characterBennettCoverage,
  characterCandaceCoverage,
  characterCharlotteCoverage,
  characterChascaCoverage,
  characterChevreuseCoverage,
  characterChioriCoverage,
  characterChongyunCoverage,
  characterCitlaliCoverage,
  characterClorindeCoverage,
  characterColleiCoverage,
  characterColumbinaCoverage,
  characterCynoCoverage,
  characterDahliaCoverage,
  characterDehyaCoverage,
  characterDilucCoverage,
  characterDionaCoverage,
  characterDoriCoverage,
  characterDurinCoverage,
  characterEmilieCoverage,
  characterEscoffierCoverage,
  characterEulaCoverage,
  characterFaruzanCoverage,
  characterFischlCoverage,
  characterFlinsCoverage,
  characterFreminetCoverage,
  characterFurinaCoverage,
  characterGamingCoverage,
  characterGanyuCoverage,
  characterGorouCoverage,
  characterHuTaoCoverage,
  characterIansanCoverage,
  characterIfaCoverage,
  characterIllugaCoverage,
  characterIneffaCoverage,
  characterJahodaCoverage,
  characterJeanCoverage,
  characterKachinaCoverage,
  characterKaedeharaKazuhaCoverage,
  characterKaeyaCoverage,
  characterKamisatoAyakaCoverage,
  characterKamisatoAyatoCoverage,
  characterKavehCoverage,
  characterKeqingCoverage,
  characterKinichCoverage,
  characterKiraraCoverage,
  characterKleeCoverage,
  characterKujouSaraCoverage,
  characterKukiShinobuCoverage,
  characterLanYanCoverage,
  characterLaumaCoverage,
  characterLaylaCoverage,
  characterLinneaCoverage,
  characterLisaCoverage,
  characterLohenCoverage,
  characterLynetteCoverage,
  characterLyneyCoverage,
  characterMavuikaCoverage,
  characterMikaCoverage,
  characterMonaCoverage,
  characterMualaniCoverage,
  characterNahidaCoverage,
  characterNaviaCoverage,
  characterNeferCoverage,
  characterNeuvilletteCoverage,
  characterNicoleCoverage,
  characterNilouCoverage,
  characterNingguangCoverage,
  characterNoelleCoverage,
  characterOdetteCoverage,
  characterOroronCoverage,
  characterPruneCoverage,
  characterQiqiCoverage,
  characterRaidenCoverage,
  characterRazorCoverage,
  characterRosariaCoverage,
  characterSandroneCoverage,
  characterSangonomiyaKokomiCoverage,
  characterSayuCoverage,
  characterSethosCoverage,
  characterShenheCoverage,
  characterShikanoinHeizouCoverage,
  characterSigewinneCoverage,
  characterSkirkCoverage,
  characterSucroseCoverage,
  characterTartagliaCoverage,
  characterThomaCoverage,
  characterTighnariCoverage,
  characterTravelerCoverage,
  characterVaresaCoverage,
  characterVarkaCoverage,
  characterVentiCoverage,
  characterWandererCoverage,
  characterWriothesleyCoverage,
  characterXianglingCoverage,
  characterXianyunCoverage,
  characterXiaoCoverage,
  characterXilonenCoverage,
  characterXingqiuCoverage,
  characterXinyanCoverage,
  characterYaeMikoCoverage,
  characterYanfeiCoverage,
  characterYaoyaoCoverage,
  characterYelanCoverage,
  characterYoimiyaCoverage,
  characterYumemizukiMizukiCoverage,
  characterYunJinCoverage,
  characterZhongliCoverage,
  characterZibaiCoverage
]
