// Generated by tools/generate-registries.ts; do not edit by hand.
import type { EquipmentCoverageEntry } from "../equipment-coverage.js"

import { equipmentCoverage as artifactADayCarvedFromRisingWindsCoverage } from "../artifacts/a-day-carved-from-rising-winds/coverage.js"
import { equipmentCoverage as artifactAdventurerCoverage } from "../artifacts/adventurer/coverage.js"
import { equipmentCoverage as artifactArchaicPetraCoverage } from "../artifacts/archaic-petra/coverage.js"
import { equipmentCoverage as artifactAubadeOfMorningstarAndMoonCoverage } from "../artifacts/aubade-of-morningstar-and-moon/coverage.js"
import { equipmentCoverage as artifactBerserkerCoverage } from "../artifacts/berserker/coverage.js"
import { equipmentCoverage as artifactBlizzardStrayerCoverage } from "../artifacts/blizzard-strayer/coverage.js"
import { equipmentCoverage as artifactBloodstainedChivalryCoverage } from "../artifacts/bloodstained-chivalry/coverage.js"
import { equipmentCoverage as artifactBraveHeartCoverage } from "../artifacts/brave-heart/coverage.js"
import { equipmentCoverage as artifactCelestialGiftCoverage } from "../artifacts/celestial-gift/coverage.js"
import { equipmentCoverage as artifactCrimsonWitchOfFlamesCoverage } from "../artifacts/crimson-witch-of-flames/coverage.js"
import { equipmentCoverage as artifactDeepwoodMemoriesCoverage } from "../artifacts/deepwood-memories/coverage.js"
import { equipmentCoverage as artifactDefendersWillCoverage } from "../artifacts/defenders-will/coverage.js"
import { equipmentCoverage as artifactDesertPavilionChronicleCoverage } from "../artifacts/desert-pavilion-chronicle/coverage.js"
import { equipmentCoverage as artifactDisenchantmentInDeepShadowCoverage } from "../artifacts/disenchantment-in-deep-shadow/coverage.js"
import { equipmentCoverage as artifactEchoesOfAnOfferingCoverage } from "../artifacts/echoes-of-an-offering/coverage.js"
import { equipmentCoverage as artifactEmblemOfSeveredFateCoverage } from "../artifacts/emblem-of-severed-fate/coverage.js"
import { equipmentCoverage as artifactFinaleOfTheDeepGalleriesCoverage } from "../artifacts/finale-of-the-deep-galleries/coverage.js"
import { equipmentCoverage as artifactFlowerOfParadiseLostCoverage } from "../artifacts/flower-of-paradise-lost/coverage.js"
import { equipmentCoverage as artifactFragmentOfHarmonicWhimsyCoverage } from "../artifacts/fragment-of-harmonic-whimsy/coverage.js"
import { equipmentCoverage as artifactGamblerCoverage } from "../artifacts/gambler/coverage.js"
import { equipmentCoverage as artifactGildedDreamsCoverage } from "../artifacts/gilded-dreams/coverage.js"
import { equipmentCoverage as artifactGladiatorsFinaleCoverage } from "../artifacts/gladiators-finale/coverage.js"
import { equipmentCoverage as artifactGoldenTroupeCoverage } from "../artifacts/golden-troupe/coverage.js"
import { equipmentCoverage as artifactHeartOfDepthCoverage } from "../artifacts/heart-of-depth/coverage.js"
import { equipmentCoverage as artifactHeartOfTheFurnaceCoverage } from "../artifacts/heart-of-the-furnace/coverage.js"
import { equipmentCoverage as artifactHuskOfOpulentDreamsCoverage } from "../artifacts/husk-of-opulent-dreams/coverage.js"
import { equipmentCoverage as artifactInstructorCoverage } from "../artifacts/instructor/coverage.js"
import { equipmentCoverage as artifactLavawalkerCoverage } from "../artifacts/lavawalker/coverage.js"
import { equipmentCoverage as artifactLongNightsOathCoverage } from "../artifacts/long-nights-oath/coverage.js"
import { equipmentCoverage as artifactLuckyDogCoverage } from "../artifacts/lucky-dog/coverage.js"
import { equipmentCoverage as artifactMaidenBelovedCoverage } from "../artifacts/maiden-beloved/coverage.js"
import { equipmentCoverage as artifactMarechausseeHunterCoverage } from "../artifacts/marechaussee-hunter/coverage.js"
import { equipmentCoverage as artifactMartialArtistCoverage } from "../artifacts/martial-artist/coverage.js"
import { equipmentCoverage as artifactNightOfTheSkysUnveilingCoverage } from "../artifacts/night-of-the-skys-unveiling/coverage.js"
import { equipmentCoverage as artifactNighttimeWhispersInTheEchoingWoodsCoverage } from "../artifacts/nighttime-whispers-in-the-echoing-woods/coverage.js"
import { equipmentCoverage as artifactNoblesseObligeCoverage } from "../artifacts/noblesse-oblige/coverage.js"
import { equipmentCoverage as artifactNymphsDreamCoverage } from "../artifacts/nymphs-dream/coverage.js"
import { equipmentCoverage as artifactObsidianCodexCoverage } from "../artifacts/obsidian-codex/coverage.js"
import { equipmentCoverage as artifactOceanHuedClamCoverage } from "../artifacts/ocean-hued-clam/coverage.js"
import { equipmentCoverage as artifactPaleFlameCoverage } from "../artifacts/pale-flame/coverage.js"
import { equipmentCoverage as artifactPrayersForDestinyCoverage } from "../artifacts/prayers-for-destiny/coverage.js"
import { equipmentCoverage as artifactPrayersForIlluminationCoverage } from "../artifacts/prayers-for-illumination/coverage.js"
import { equipmentCoverage as artifactPrayersForWisdomCoverage } from "../artifacts/prayers-for-wisdom/coverage.js"
import { equipmentCoverage as artifactPrayersToSpringtimeCoverage } from "../artifacts/prayers-to-springtime/coverage.js"
import { equipmentCoverage as artifactResolutionOfSojournerCoverage } from "../artifacts/resolution-of-sojourner/coverage.js"
import { equipmentCoverage as artifactRetracingBolideCoverage } from "../artifacts/retracing-bolide/coverage.js"
import { equipmentCoverage as artifactScarletProofCoverage } from "../artifacts/scarlet-proof/coverage.js"
import { equipmentCoverage as artifactScholarCoverage } from "../artifacts/scholar/coverage.js"
import { equipmentCoverage as artifactScrollOfTheHeroOfCinderCityCoverage } from "../artifacts/scroll-of-the-hero-of-cinder-city/coverage.js"
import { equipmentCoverage as artifactShimenawasReminiscenceCoverage } from "../artifacts/shimenawas-reminiscence/coverage.js"
import { equipmentCoverage as artifactSilkenMoonsSerenadeCoverage } from "../artifacts/silken-moons-serenade/coverage.js"
import { equipmentCoverage as artifactSongOfDaysPastCoverage } from "../artifacts/song-of-days-past/coverage.js"
import { equipmentCoverage as artifactTenacityOfTheMillelithCoverage } from "../artifacts/tenacity-of-the-millelith/coverage.js"
import { equipmentCoverage as artifactTheExileCoverage } from "../artifacts/the-exile/coverage.js"
import { equipmentCoverage as artifactThunderingFuryCoverage } from "../artifacts/thundering-fury/coverage.js"
import { equipmentCoverage as artifactThundersootherCoverage } from "../artifacts/thundersoother/coverage.js"
import { equipmentCoverage as artifactTinyMiracleCoverage } from "../artifacts/tiny-miracle/coverage.js"
import { equipmentCoverage as artifactTravelingDoctorCoverage } from "../artifacts/traveling-doctor/coverage.js"
import { equipmentCoverage as artifactUnfinishedReverieCoverage } from "../artifacts/unfinished-reverie/coverage.js"
import { equipmentCoverage as artifactVermillionHereafterCoverage } from "../artifacts/vermillion-hereafter/coverage.js"
import { equipmentCoverage as artifactViridescentVenererCoverage } from "../artifacts/viridescent-venerer/coverage.js"
import { equipmentCoverage as artifactVourukashasGlowCoverage } from "../artifacts/vourukashas-glow/coverage.js"
import { equipmentCoverage as artifactWanderersTroupeCoverage } from "../artifacts/wanderers-troupe/coverage.js"
import { equipmentCoverage as weaponATeaspoonOfTranscendenceCoverage } from "../weapons/a-teaspoon-of-transcendence/coverage.js"
import { equipmentCoverage as weaponAThousandBlazingSunsCoverage } from "../weapons/a-thousand-blazing-suns/coverage.js"
import { equipmentCoverage as weaponAThousandFloatingDreamsCoverage } from "../weapons/a-thousand-floating-dreams/coverage.js"
import { equipmentCoverage as weaponAbsolutionCoverage } from "../weapons/absolution/coverage.js"
import { equipmentCoverage as weaponAkuoumaruCoverage } from "../weapons/akuoumaru/coverage.js"
import { equipmentCoverage as weaponAlleyHunterCoverage } from "../weapons/alley-hunter/coverage.js"
import { equipmentCoverage as weaponAmenomaKageuchiCoverage } from "../weapons/amenoma-kageuchi/coverage.js"
import { equipmentCoverage as weaponAmosBowCoverage } from "../weapons/amos-bow/coverage.js"
import { equipmentCoverage as weaponAngelosHeptadesCoverage } from "../weapons/angelos-heptades/coverage.js"
import { equipmentCoverage as weaponApprenticesNotesCoverage } from "../weapons/apprentices-notes/coverage.js"
import { equipmentCoverage as weaponAquaSimulacraCoverage } from "../weapons/aqua-simulacra/coverage.js"
import { equipmentCoverage as weaponAquilaFavoniaCoverage } from "../weapons/aquila-favonia/coverage.js"
import { equipmentCoverage as weaponAshGravenDrinkingHornCoverage } from "../weapons/ash-graven-drinking-horn/coverage.js"
import { equipmentCoverage as weaponAstralVulturesCrimsonPlumageCoverage } from "../weapons/astral-vultures-crimson-plumage/coverage.js"
import { equipmentCoverage as weaponAthameArtisCoverage } from "../weapons/athame-artis/coverage.js"
import { equipmentCoverage as weaponAzurelightCoverage } from "../weapons/azurelight/coverage.js"
import { equipmentCoverage as weaponBalladOfTheBoundlessBlueCoverage } from "../weapons/ballad-of-the-boundless-blue/coverage.js"
import { equipmentCoverage as weaponBalladOfTheFjordsCoverage } from "../weapons/ballad-of-the-fjords/coverage.js"
import { equipmentCoverage as weaponBeaconOfTheReedSeaCoverage } from "../weapons/beacon-of-the-reed-sea/coverage.js"
import { equipmentCoverage as weaponBeginnersProtectorCoverage } from "../weapons/beginners-protector/coverage.js"
import { equipmentCoverage as weaponBlackTasselCoverage } from "../weapons/black-tassel/coverage.js"
import { equipmentCoverage as weaponBlackcliffAgateCoverage } from "../weapons/blackcliff-agate/coverage.js"
import { equipmentCoverage as weaponBlackcliffLongswordCoverage } from "../weapons/blackcliff-longsword/coverage.js"
import { equipmentCoverage as weaponBlackcliffPoleCoverage } from "../weapons/blackcliff-pole/coverage.js"
import { equipmentCoverage as weaponBlackcliffSlasherCoverage } from "../weapons/blackcliff-slasher/coverage.js"
import { equipmentCoverage as weaponBlackcliffWarbowCoverage } from "../weapons/blackcliff-warbow/coverage.js"
import { equipmentCoverage as weaponBlackmarrowLanternCoverage } from "../weapons/blackmarrow-lantern/coverage.js"
import { equipmentCoverage as weaponBladeOfAtonementCoverage } from "../weapons/blade-of-atonement/coverage.js"
import { equipmentCoverage as weaponBloodsoakedRuinsCoverage } from "../weapons/bloodsoaked-ruins/coverage.js"
import { equipmentCoverage as weaponBloodtaintedGreatswordCoverage } from "../weapons/bloodtainted-greatsword/coverage.js"
import { equipmentCoverage as weaponCalamityOfEshuCoverage } from "../weapons/calamity-of-eshu/coverage.js"
import { equipmentCoverage as weaponCalamityQuellerCoverage } from "../weapons/calamity-queller/coverage.js"
import { equipmentCoverage as weaponCashflowSupervisionCoverage } from "../weapons/cashflow-supervision/coverage.js"
import { equipmentCoverage as weaponChainBreakerCoverage } from "../weapons/chain-breaker/coverage.js"
import { equipmentCoverage as weaponCinnabarSpindleCoverage } from "../weapons/cinnabar-spindle/coverage.js"
import { equipmentCoverage as weaponClashOfKingsCoverage } from "../weapons/clash-of-kings/coverage.js"
import { equipmentCoverage as weaponCloudforgedCoverage } from "../weapons/cloudforged/coverage.js"
import { equipmentCoverage as weaponCompoundBowCoverage } from "../weapons/compound-bow/coverage.js"
import { equipmentCoverage as weaponCoolSteelCoverage } from "../weapons/cool-steel/coverage.js"
import { equipmentCoverage as weaponCovenantOfFrostAndSnowCoverage } from "../weapons/covenant-of-frost-and-snow/coverage.js"
import { equipmentCoverage as weaponCranesEchoingCallCoverage } from "../weapons/cranes-echoing-call/coverage.js"
import { equipmentCoverage as weaponCrescentPikeCoverage } from "../weapons/crescent-pike/coverage.js"
import { equipmentCoverage as weaponCrimsonMoonsSemblanceCoverage } from "../weapons/crimson-moons-semblance/coverage.js"
import { equipmentCoverage as weaponDarkIronSwordCoverage } from "../weapons/dark-iron-sword/coverage.js"
import { equipmentCoverage as weaponDawningFrostCoverage } from "../weapons/dawning-frost/coverage.js"
import { equipmentCoverage as weaponDeathmatchCoverage } from "../weapons/deathmatch/coverage.js"
import { equipmentCoverage as weaponDebateClubCoverage } from "../weapons/debate-club/coverage.js"
import { equipmentCoverage as weaponDialoguesOfTheDesertSagesCoverage } from "../weapons/dialogues-of-the-desert-sages/coverage.js"
import { equipmentCoverage as weaponDisasterAndRemorseCoverage } from "../weapons/disaster-and-remorse/coverage.js"
import { equipmentCoverage as weaponDodocoTalesCoverage } from "../weapons/dodoco-tales/coverage.js"
import { equipmentCoverage as weaponDragonsBaneCoverage } from "../weapons/dragons-bane/coverage.js"
import { equipmentCoverage as weaponDragonspineSpearCoverage } from "../weapons/dragonspine-spear/coverage.js"
import { equipmentCoverage as weaponDullBladeCoverage } from "../weapons/dull-blade/coverage.js"
import { equipmentCoverage as weaponEarthShakerCoverage } from "../weapons/earth-shaker/coverage.js"
import { equipmentCoverage as weaponEchoesOfTheHeartCoverage } from "../weapons/echoes-of-the-heart/coverage.js"
import { equipmentCoverage as weaponElegyForTheEndCoverage } from "../weapons/elegy-for-the-end/coverage.js"
import { equipmentCoverage as weaponEmberwellCoverage } from "../weapons/emberwell/coverage.js"
import { equipmentCoverage as weaponEmeraldOrbCoverage } from "../weapons/emerald-orb/coverage.js"
import { equipmentCoverage as weaponEndOfTheLineCoverage } from "../weapons/end-of-the-line/coverage.js"
import { equipmentCoverage as weaponEngulfingLightningCoverage } from "../weapons/engulfing-lightning/coverage.js"
import { equipmentCoverage as weaponEtherlightSpindleluteCoverage } from "../weapons/etherlight-spindlelute/coverage.js"
import { equipmentCoverage as weaponEverlastingMoonglowCoverage } from "../weapons/everlasting-moonglow/coverage.js"
import { equipmentCoverage as weaponExaiphanesBladeCoverage } from "../weapons/exaiphanes-blade/coverage.js"
import { equipmentCoverage as weaponEyeOfPerceptionCoverage } from "../weapons/eye-of-perception/coverage.js"
import { equipmentCoverage as weaponFadingTwilightCoverage } from "../weapons/fading-twilight/coverage.js"
import { equipmentCoverage as weaponFangOfTheMountainKingCoverage } from "../weapons/fang-of-the-mountain-king/coverage.js"
import { equipmentCoverage as weaponFavoniusCodexCoverage } from "../weapons/favonius-codex/coverage.js"
import { equipmentCoverage as weaponFavoniusGreatswordCoverage } from "../weapons/favonius-greatsword/coverage.js"
import { equipmentCoverage as weaponFavoniusLanceCoverage } from "../weapons/favonius-lance/coverage.js"
import { equipmentCoverage as weaponFavoniusSwordCoverage } from "../weapons/favonius-sword/coverage.js"
import { equipmentCoverage as weaponFavoniusWarbowCoverage } from "../weapons/favonius-warbow/coverage.js"
import { equipmentCoverage as weaponFerrousShadowCoverage } from "../weapons/ferrous-shadow/coverage.js"
import { equipmentCoverage as weaponFesteringDesireCoverage } from "../weapons/festering-desire/coverage.js"
import { equipmentCoverage as weaponFilletBladeCoverage } from "../weapons/fillet-blade/coverage.js"
import { equipmentCoverage as weaponFinaleOfTheDeepCoverage } from "../weapons/finale-of-the-deep/coverage.js"
import { equipmentCoverage as weaponFlameForgedInsightCoverage } from "../weapons/flame-forged-insight/coverage.js"
import { equipmentCoverage as weaponFleuveCendreFerrymanCoverage } from "../weapons/fleuve-cendre-ferryman/coverage.js"
import { equipmentCoverage as weaponFlowerWreathedFeathersCoverage } from "../weapons/flower-wreathed-feathers/coverage.js"
import { equipmentCoverage as weaponFlowingPurityCoverage } from "../weapons/flowing-purity/coverage.js"
import { equipmentCoverage as weaponFluteOfEzpitzalCoverage } from "../weapons/flute-of-ezpitzal/coverage.js"
import { equipmentCoverage as weaponFootprintOfTheRainbowCoverage } from "../weapons/footprint-of-the-rainbow/coverage.js"
import { equipmentCoverage as weaponForestRegaliaCoverage } from "../weapons/forest-regalia/coverage.js"
import { equipmentCoverage as weaponForgedByTheGoldenMelodyCoverage } from "../weapons/forged-by-the-golden-melody/coverage.js"
import { equipmentCoverage as weaponFracturedHaloCoverage } from "../weapons/fractured-halo/coverage.js"
import { equipmentCoverage as weaponFreedomSwornCoverage } from "../weapons/freedom-sworn/coverage.js"
import { equipmentCoverage as weaponFrostbearerCoverage } from "../weapons/frostbearer/coverage.js"
import { equipmentCoverage as weaponFrostbreathCoverage } from "../weapons/frostbreath/coverage.js"
import { equipmentCoverage as weaponFruitOfFulfillmentCoverage } from "../weapons/fruit-of-fulfillment/coverage.js"
import { equipmentCoverage as weaponFruitfulHookCoverage } from "../weapons/fruitful-hook/coverage.js"
import { equipmentCoverage as weaponGestOfTheMightyWolfCoverage } from "../weapons/gest-of-the-mighty-wolf/coverage.js"
import { equipmentCoverage as weaponGoldenFrostboundOathCoverage } from "../weapons/golden-frostbound-oath/coverage.js"
import { equipmentCoverage as weaponHakushinRingCoverage } from "../weapons/hakushin-ring/coverage.js"
import { equipmentCoverage as weaponHalberdCoverage } from "../weapons/halberd/coverage.js"
import { equipmentCoverage as weaponHamayumiCoverage } from "../weapons/hamayumi/coverage.js"
import { equipmentCoverage as weaponHaranGeppakuFutsuCoverage } from "../weapons/haran-geppaku-futsu/coverage.js"
import { equipmentCoverage as weaponHarbingerOfDawnCoverage } from "../weapons/harbinger-of-dawn/coverage.js"
import { equipmentCoverage as weaponHereticsMoltenBladeCoverage } from "../weapons/heretics-molten-blade/coverage.js"
import { equipmentCoverage as weaponHuntersBowCoverage } from "../weapons/hunters-bow/coverage.js"
import { equipmentCoverage as weaponHuntersPathCoverage } from "../weapons/hunters-path/coverage.js"
import { equipmentCoverage as weaponIbisPiercerCoverage } from "../weapons/ibis-piercer/coverage.js"
import { equipmentCoverage as weaponIronPointCoverage } from "../weapons/iron-point/coverage.js"
import { equipmentCoverage as weaponIronStingCoverage } from "../weapons/iron-sting/coverage.js"
import { equipmentCoverage as weaponJadeVistaCoverage } from "../weapons/jade-vista/coverage.js"
import { equipmentCoverage as weaponJadefallsSplendorCoverage } from "../weapons/jadefalls-splendor/coverage.js"
import { equipmentCoverage as weaponKagotsurubeIsshinCoverage } from "../weapons/kagotsurube-isshin/coverage.js"
import { equipmentCoverage as weaponKagurasVerityCoverage } from "../weapons/kaguras-verity/coverage.js"
import { equipmentCoverage as weaponKatsuragikiriNagamasaCoverage } from "../weapons/katsuragikiri-nagamasa/coverage.js"
import { equipmentCoverage as weaponKeyOfKhajNisutCoverage } from "../weapons/key-of-khaj-nisut/coverage.js"
import { equipmentCoverage as weaponKingsSquireCoverage } from "../weapons/kings-squire/coverage.js"
import { equipmentCoverage as weaponKitainCrossSpearCoverage } from "../weapons/kitain-cross-spear/coverage.js"
import { equipmentCoverage as weaponLightOfFoliarIncisionCoverage } from "../weapons/light-of-foliar-incision/coverage.js"
import { equipmentCoverage as weaponLightbearingMoonshardCoverage } from "../weapons/lightbearing-moonshard/coverage.js"
import { equipmentCoverage as weaponLionsRoarCoverage } from "../weapons/lions-roar/coverage.js"
import { equipmentCoverage as weaponLithicBladeCoverage } from "../weapons/lithic-blade/coverage.js"
import { equipmentCoverage as weaponLithicSpearCoverage } from "../weapons/lithic-spear/coverage.js"
import { equipmentCoverage as weaponLostPrayerToTheSacredWindsCoverage } from "../weapons/lost-prayer-to-the-sacred-winds/coverage.js"
import { equipmentCoverage as weaponLumidouceElegyCoverage } from "../weapons/lumidouce-elegy/coverage.js"
import { equipmentCoverage as weaponLuxuriousSeaLordCoverage } from "../weapons/luxurious-sea-lord/coverage.js"
import { equipmentCoverage as weaponMagicGuideCoverage } from "../weapons/magic-guide/coverage.js"
import { equipmentCoverage as weaponMailedFlowerCoverage } from "../weapons/mailed-flower/coverage.js"
import { equipmentCoverage as weaponMakhairaAquamarineCoverage } from "../weapons/makhaira-aquamarine/coverage.js"
import { equipmentCoverage as weaponMappaMareCoverage } from "../weapons/mappa-mare/coverage.js"
import { equipmentCoverage as weaponMasterKeyCoverage } from "../weapons/master-key/coverage.js"
import { equipmentCoverage as weaponMemoryOfDustCoverage } from "../weapons/memory-of-dust/coverage.js"
import { equipmentCoverage as weaponMessengerCoverage } from "../weapons/messenger/coverage.js"
import { equipmentCoverage as weaponMissiveWindspearCoverage } from "../weapons/missive-windspear/coverage.js"
import { equipmentCoverage as weaponMistsplitterReforgedCoverage } from "../weapons/mistsplitter-reforged/coverage.js"
import { equipmentCoverage as weaponMitternachtsWaltzCoverage } from "../weapons/mitternachts-waltz/coverage.js"
import { equipmentCoverage as weaponMoonpiercerCoverage } from "../weapons/moonpiercer/coverage.js"
import { equipmentCoverage as weaponMoonweaversDawnCoverage } from "../weapons/moonweavers-dawn/coverage.js"
import { equipmentCoverage as weaponMountainBracingBoltCoverage } from "../weapons/mountain-bracing-bolt/coverage.js"
import { equipmentCoverage as weaponMouunsMoonCoverage } from "../weapons/mouuns-moon/coverage.js"
import { equipmentCoverage as weaponNightweaversLookingGlassCoverage } from "../weapons/nightweavers-looking-glass/coverage.js"
import { equipmentCoverage as weaponNocturnesCurtainCallCoverage } from "../weapons/nocturnes-curtain-call/coverage.js"
import { equipmentCoverage as weaponOathswornEyeCoverage } from "../weapons/oathsworn-eye/coverage.js"
import { equipmentCoverage as weaponOldMercsPalCoverage } from "../weapons/old-mercs-pal/coverage.js"
import { equipmentCoverage as weaponOtherworldlyStoryCoverage } from "../weapons/otherworldly-story/coverage.js"
import { equipmentCoverage as weaponPeakPatrolSongCoverage } from "../weapons/peak-patrol-song/coverage.js"
import { equipmentCoverage as weaponPocketGrimoireCoverage } from "../weapons/pocket-grimoire/coverage.js"
import { equipmentCoverage as weaponPolarStarCoverage } from "../weapons/polar-star/coverage.js"
import { equipmentCoverage as weaponPortablePowerSawCoverage } from "../weapons/portable-power-saw/coverage.js"
import { equipmentCoverage as weaponPredatorCoverage } from "../weapons/predator/coverage.js"
import { equipmentCoverage as weaponPrimordialJadeCutterCoverage } from "../weapons/primordial-jade-cutter/coverage.js"
import { equipmentCoverage as weaponPrimordialJadeWingedSpearCoverage } from "../weapons/primordial-jade-winged-spear/coverage.js"
import { equipmentCoverage as weaponProspectorsDrillCoverage } from "../weapons/prospectors-drill/coverage.js"
import { equipmentCoverage as weaponProspectorsShovelCoverage } from "../weapons/prospectors-shovel/coverage.js"
import { equipmentCoverage as weaponPrototypeAmberCoverage } from "../weapons/prototype-amber/coverage.js"
import { equipmentCoverage as weaponPrototypeArchaicCoverage } from "../weapons/prototype-archaic/coverage.js"
import { equipmentCoverage as weaponPrototypeCrescentCoverage } from "../weapons/prototype-crescent/coverage.js"
import { equipmentCoverage as weaponPrototypeRancourCoverage } from "../weapons/prototype-rancour/coverage.js"
import { equipmentCoverage as weaponPrototypeStarglitterCoverage } from "../weapons/prototype-starglitter/coverage.js"
import { equipmentCoverage as weaponRainbowSerpentsRainBowCoverage } from "../weapons/rainbow-serpents-rain-bow/coverage.js"
import { equipmentCoverage as weaponRainslasherCoverage } from "../weapons/rainslasher/coverage.js"
import { equipmentCoverage as weaponRangeGaugeCoverage } from "../weapons/range-gauge/coverage.js"
import { equipmentCoverage as weaponRavenBowCoverage } from "../weapons/raven-bow/coverage.js"
import { equipmentCoverage as weaponRecurveBowCoverage } from "../weapons/recurve-bow/coverage.js"
import { equipmentCoverage as weaponRedhornStonethresherCoverage } from "../weapons/redhorn-stonethresher/coverage.js"
import { equipmentCoverage as weaponReliquaryOfTruthCoverage } from "../weapons/reliquary-of-truth/coverage.js"
import { equipmentCoverage as weaponRightfulRewardCoverage } from "../weapons/rightful-reward/coverage.js"
import { equipmentCoverage as weaponRingOfYaxcheCoverage } from "../weapons/ring-of-yaxche/coverage.js"
import { equipmentCoverage as weaponRoyalBowCoverage } from "../weapons/royal-bow/coverage.js"
import { equipmentCoverage as weaponRoyalGreatswordCoverage } from "../weapons/royal-greatsword/coverage.js"
import { equipmentCoverage as weaponRoyalGrimoireCoverage } from "../weapons/royal-grimoire/coverage.js"
import { equipmentCoverage as weaponRoyalLongswordCoverage } from "../weapons/royal-longsword/coverage.js"
import { equipmentCoverage as weaponRoyalSpearCoverage } from "../weapons/royal-spear/coverage.js"
import { equipmentCoverage as weaponRustCoverage } from "../weapons/rust/coverage.js"
import { equipmentCoverage as weaponSacrificersStaffCoverage } from "../weapons/sacrificers-staff/coverage.js"
import { equipmentCoverage as weaponSacrificialBowCoverage } from "../weapons/sacrificial-bow/coverage.js"
import { equipmentCoverage as weaponSacrificialFragmentsCoverage } from "../weapons/sacrificial-fragments/coverage.js"
import { equipmentCoverage as weaponSacrificialGreatswordCoverage } from "../weapons/sacrificial-greatsword/coverage.js"
import { equipmentCoverage as weaponSacrificialJadeCoverage } from "../weapons/sacrificial-jade/coverage.js"
import { equipmentCoverage as weaponSacrificialSwordCoverage } from "../weapons/sacrificial-sword/coverage.js"
import { equipmentCoverage as weaponSapwoodBladeCoverage } from "../weapons/sapwood-blade/coverage.js"
import { equipmentCoverage as weaponScionOfTheBlazingSunCoverage } from "../weapons/scion-of-the-blazing-sun/coverage.js"
import { equipmentCoverage as weaponSeasonedHuntersBowCoverage } from "../weapons/seasoned-hunters-bow/coverage.js"
import { equipmentCoverage as weaponSequenceOfSolitudeCoverage } from "../weapons/sequence-of-solitude/coverage.js"
import { equipmentCoverage as weaponSerenitysCallCoverage } from "../weapons/serenitys-call/coverage.js"
import { equipmentCoverage as weaponSerpentSpineCoverage } from "../weapons/serpent-spine/coverage.js"
import { equipmentCoverage as weaponSharpshootersOathCoverage } from "../weapons/sharpshooters-oath/coverage.js"
import { equipmentCoverage as weaponSilverSwordCoverage } from "../weapons/silver-sword/coverage.js"
import { equipmentCoverage as weaponSilvershowerHeartstringsCoverage } from "../weapons/silvershower-heartstrings/coverage.js"
import { equipmentCoverage as weaponSkyriderGreatswordCoverage } from "../weapons/skyrider-greatsword/coverage.js"
import { equipmentCoverage as weaponSkyriderSwordCoverage } from "../weapons/skyrider-sword/coverage.js"
import { equipmentCoverage as weaponSkywardAtlasCoverage } from "../weapons/skyward-atlas/coverage.js"
import { equipmentCoverage as weaponSkywardBladeCoverage } from "../weapons/skyward-blade/coverage.js"
import { equipmentCoverage as weaponSkywardHarpCoverage } from "../weapons/skyward-harp/coverage.js"
import { equipmentCoverage as weaponSkywardPrideCoverage } from "../weapons/skyward-pride/coverage.js"
import { equipmentCoverage as weaponSkywardSpineCoverage } from "../weapons/skyward-spine/coverage.js"
import { equipmentCoverage as weaponSlingshotCoverage } from "../weapons/slingshot/coverage.js"
import { equipmentCoverage as weaponSnareHookCoverage } from "../weapons/snare-hook/coverage.js"
import { equipmentCoverage as weaponSnowTombedStarsilverCoverage } from "../weapons/snow-tombed-starsilver/coverage.js"
import { equipmentCoverage as weaponSolarPearlCoverage } from "../weapons/solar-pearl/coverage.js"
import { equipmentCoverage as weaponSongOfBrokenPinesCoverage } from "../weapons/song-of-broken-pines/coverage.js"
import { equipmentCoverage as weaponSongOfStillnessCoverage } from "../weapons/song-of-stillness/coverage.js"
import { equipmentCoverage as weaponSongOfTheVigilCoverage } from "../weapons/song-of-the-vigil/coverage.js"
import { equipmentCoverage as weaponSplendorOfTranquilWatersCoverage } from "../weapons/splendor-of-tranquil-waters/coverage.js"
import { equipmentCoverage as weaponStaffOfHomaCoverage } from "../weapons/staff-of-homa/coverage.js"
import { equipmentCoverage as weaponStaffOfTheScarletSandsCoverage } from "../weapons/staff-of-the-scarlet-sands/coverage.js"
import { equipmentCoverage as weaponStarcallersWatchCoverage } from "../weapons/starcallers-watch/coverage.js"
import { equipmentCoverage as weaponSturdyBoneCoverage } from "../weapons/sturdy-bone/coverage.js"
import { equipmentCoverage as weaponSummitShaperCoverage } from "../weapons/summit-shaper/coverage.js"
import { equipmentCoverage as weaponSunnyMorningSleepInCoverage } from "../weapons/sunny-morning-sleep-in/coverage.js"
import { equipmentCoverage as weaponSurfsUpCoverage } from "../weapons/surfs-up/coverage.js"
import { equipmentCoverage as weaponSwordOfDescensionCoverage } from "../weapons/sword-of-descension/coverage.js"
import { equipmentCoverage as weaponSwordOfNarzissenkreuzCoverage } from "../weapons/sword-of-narzissenkreuz/coverage.js"
import { equipmentCoverage as weaponSymphonistOfScentsCoverage } from "../weapons/symphonist-of-scents/coverage.js"
import { equipmentCoverage as weaponTalkingStickCoverage } from "../weapons/talking-stick/coverage.js"
import { equipmentCoverage as weaponTamayurateiNoOhanashiCoverage } from "../weapons/tamayuratei-no-ohanashi/coverage.js"
import { equipmentCoverage as weaponTheAlleyFlashCoverage } from "../weapons/the-alley-flash/coverage.js"
import { equipmentCoverage as weaponTheBellCoverage } from "../weapons/the-bell/coverage.js"
import { equipmentCoverage as weaponTheBlackSwordCoverage } from "../weapons/the-black-sword/coverage.js"
import { equipmentCoverage as weaponTheCatchCoverage } from "../weapons/the-catch/coverage.js"
import { equipmentCoverage as weaponTheDaybreakChroniclesCoverage } from "../weapons/the-daybreak-chronicles/coverage.js"
import { equipmentCoverage as weaponTheDockhandsAssistantCoverage } from "../weapons/the-dockhands-assistant/coverage.js"
import { equipmentCoverage as weaponTheFirstGreatMagicCoverage } from "../weapons/the-first-great-magic/coverage.js"
import { equipmentCoverage as weaponTheFluteCoverage } from "../weapons/the-flute/coverage.js"
import { equipmentCoverage as weaponTheStringlessCoverage } from "../weapons/the-stringless/coverage.js"
import { equipmentCoverage as weaponTheUnforgedCoverage } from "../weapons/the-unforged/coverage.js"
import { equipmentCoverage as weaponTheViridescentHuntCoverage } from "../weapons/the-viridescent-hunt/coverage.js"
import { equipmentCoverage as weaponTheWidsithCoverage } from "../weapons/the-widsith/coverage.js"
import { equipmentCoverage as weaponThrillingTalesOfDragonSlayersCoverage } from "../weapons/thrilling-tales-of-dragon-slayers/coverage.js"
import { equipmentCoverage as weaponThunderingPulseCoverage } from "../weapons/thundering-pulse/coverage.js"
import { equipmentCoverage as weaponTidalShadowCoverage } from "../weapons/tidal-shadow/coverage.js"
import { equipmentCoverage as weaponTomeOfTheEternalFlowCoverage } from "../weapons/tome-of-the-eternal-flow/coverage.js"
import { equipmentCoverage as weaponToukabouShigureCoverage } from "../weapons/toukabou-shigure/coverage.js"
import { equipmentCoverage as weaponTravelersHandySwordCoverage } from "../weapons/travelers-handy-sword/coverage.js"
import { equipmentCoverage as weaponTulaytullahsRemembranceCoverage } from "../weapons/tulaytullahs-remembrance/coverage.js"
import { equipmentCoverage as weaponTwinNephriteCoverage } from "../weapons/twin-nephrite/coverage.js"
import { equipmentCoverage as weaponUltimateOverlordsMegaMagicSwordCoverage } from "../weapons/ultimate-overlords-mega-magic-sword/coverage.js"
import { equipmentCoverage as weaponUrakuMisugiriCoverage } from "../weapons/uraku-misugiri/coverage.js"
import { equipmentCoverage as weaponVerdictCoverage } from "../weapons/verdict/coverage.js"
import { equipmentCoverage as weaponVividNotionsCoverage } from "../weapons/vivid-notions/coverage.js"
import { equipmentCoverage as weaponVortexVanquisherCoverage } from "../weapons/vortex-vanquisher/coverage.js"
import { equipmentCoverage as weaponWanderingEvenstarCoverage } from "../weapons/wandering-evenstar/coverage.js"
import { equipmentCoverage as weaponWasterGreatswordCoverage } from "../weapons/waster-greatsword/coverage.js"
import { equipmentCoverage as weaponWavebreakersFinCoverage } from "../weapons/wavebreakers-fin/coverage.js"
import { equipmentCoverage as weaponWaveridingWhirlCoverage } from "../weapons/waveriding-whirl/coverage.js"
import { equipmentCoverage as weaponWhiteIronGreatswordCoverage } from "../weapons/white-iron-greatsword/coverage.js"
import { equipmentCoverage as weaponWhiteTasselCoverage } from "../weapons/white-tassel/coverage.js"
import { equipmentCoverage as weaponWhiteblindCoverage } from "../weapons/whiteblind/coverage.js"
import { equipmentCoverage as weaponWhitelakeFrostfeatherCoverage } from "../weapons/whitelake-frostfeather/coverage.js"
import { equipmentCoverage as weaponWindblumeOdeCoverage } from "../weapons/windblume-ode/coverage.js"
import { equipmentCoverage as weaponWineAndSongCoverage } from "../weapons/wine-and-song/coverage.js"
import { equipmentCoverage as weaponWolfFangCoverage } from "../weapons/wolf-fang/coverage.js"
import { equipmentCoverage as weaponWolfsGravestoneCoverage } from "../weapons/wolfs-gravestone/coverage.js"
import { equipmentCoverage as weaponXiphosMoonlightCoverage } from "../weapons/xiphos-moonlight/coverage.js"

export const reviewedEquipmentCoverageRegistry: readonly EquipmentCoverageEntry[] = [
  artifactADayCarvedFromRisingWindsCoverage,
  artifactAdventurerCoverage,
  artifactArchaicPetraCoverage,
  artifactAubadeOfMorningstarAndMoonCoverage,
  artifactBerserkerCoverage,
  artifactBlizzardStrayerCoverage,
  artifactBloodstainedChivalryCoverage,
  artifactBraveHeartCoverage,
  artifactCelestialGiftCoverage,
  artifactCrimsonWitchOfFlamesCoverage,
  artifactDeepwoodMemoriesCoverage,
  artifactDefendersWillCoverage,
  artifactDesertPavilionChronicleCoverage,
  artifactDisenchantmentInDeepShadowCoverage,
  artifactEchoesOfAnOfferingCoverage,
  artifactEmblemOfSeveredFateCoverage,
  artifactFinaleOfTheDeepGalleriesCoverage,
  artifactFlowerOfParadiseLostCoverage,
  artifactFragmentOfHarmonicWhimsyCoverage,
  artifactGamblerCoverage,
  artifactGildedDreamsCoverage,
  artifactGladiatorsFinaleCoverage,
  artifactGoldenTroupeCoverage,
  artifactHeartOfDepthCoverage,
  artifactHeartOfTheFurnaceCoverage,
  artifactHuskOfOpulentDreamsCoverage,
  artifactInstructorCoverage,
  artifactLavawalkerCoverage,
  artifactLongNightsOathCoverage,
  artifactLuckyDogCoverage,
  artifactMaidenBelovedCoverage,
  artifactMarechausseeHunterCoverage,
  artifactMartialArtistCoverage,
  artifactNightOfTheSkysUnveilingCoverage,
  artifactNighttimeWhispersInTheEchoingWoodsCoverage,
  artifactNoblesseObligeCoverage,
  artifactNymphsDreamCoverage,
  artifactObsidianCodexCoverage,
  artifactOceanHuedClamCoverage,
  artifactPaleFlameCoverage,
  artifactPrayersForDestinyCoverage,
  artifactPrayersForIlluminationCoverage,
  artifactPrayersForWisdomCoverage,
  artifactPrayersToSpringtimeCoverage,
  artifactResolutionOfSojournerCoverage,
  artifactRetracingBolideCoverage,
  artifactScarletProofCoverage,
  artifactScholarCoverage,
  artifactScrollOfTheHeroOfCinderCityCoverage,
  artifactShimenawasReminiscenceCoverage,
  artifactSilkenMoonsSerenadeCoverage,
  artifactSongOfDaysPastCoverage,
  artifactTenacityOfTheMillelithCoverage,
  artifactTheExileCoverage,
  artifactThunderingFuryCoverage,
  artifactThundersootherCoverage,
  artifactTinyMiracleCoverage,
  artifactTravelingDoctorCoverage,
  artifactUnfinishedReverieCoverage,
  artifactVermillionHereafterCoverage,
  artifactViridescentVenererCoverage,
  artifactVourukashasGlowCoverage,
  artifactWanderersTroupeCoverage,
  weaponATeaspoonOfTranscendenceCoverage,
  weaponAThousandBlazingSunsCoverage,
  weaponAThousandFloatingDreamsCoverage,
  weaponAbsolutionCoverage,
  weaponAkuoumaruCoverage,
  weaponAlleyHunterCoverage,
  weaponAmenomaKageuchiCoverage,
  weaponAmosBowCoverage,
  weaponAngelosHeptadesCoverage,
  weaponApprenticesNotesCoverage,
  weaponAquaSimulacraCoverage,
  weaponAquilaFavoniaCoverage,
  weaponAshGravenDrinkingHornCoverage,
  weaponAstralVulturesCrimsonPlumageCoverage,
  weaponAthameArtisCoverage,
  weaponAzurelightCoverage,
  weaponBalladOfTheBoundlessBlueCoverage,
  weaponBalladOfTheFjordsCoverage,
  weaponBeaconOfTheReedSeaCoverage,
  weaponBeginnersProtectorCoverage,
  weaponBlackTasselCoverage,
  weaponBlackcliffAgateCoverage,
  weaponBlackcliffLongswordCoverage,
  weaponBlackcliffPoleCoverage,
  weaponBlackcliffSlasherCoverage,
  weaponBlackcliffWarbowCoverage,
  weaponBlackmarrowLanternCoverage,
  weaponBladeOfAtonementCoverage,
  weaponBloodsoakedRuinsCoverage,
  weaponBloodtaintedGreatswordCoverage,
  weaponCalamityOfEshuCoverage,
  weaponCalamityQuellerCoverage,
  weaponCashflowSupervisionCoverage,
  weaponChainBreakerCoverage,
  weaponCinnabarSpindleCoverage,
  weaponClashOfKingsCoverage,
  weaponCloudforgedCoverage,
  weaponCompoundBowCoverage,
  weaponCoolSteelCoverage,
  weaponCovenantOfFrostAndSnowCoverage,
  weaponCranesEchoingCallCoverage,
  weaponCrescentPikeCoverage,
  weaponCrimsonMoonsSemblanceCoverage,
  weaponDarkIronSwordCoverage,
  weaponDawningFrostCoverage,
  weaponDeathmatchCoverage,
  weaponDebateClubCoverage,
  weaponDialoguesOfTheDesertSagesCoverage,
  weaponDisasterAndRemorseCoverage,
  weaponDodocoTalesCoverage,
  weaponDragonsBaneCoverage,
  weaponDragonspineSpearCoverage,
  weaponDullBladeCoverage,
  weaponEarthShakerCoverage,
  weaponEchoesOfTheHeartCoverage,
  weaponElegyForTheEndCoverage,
  weaponEmberwellCoverage,
  weaponEmeraldOrbCoverage,
  weaponEndOfTheLineCoverage,
  weaponEngulfingLightningCoverage,
  weaponEtherlightSpindleluteCoverage,
  weaponEverlastingMoonglowCoverage,
  weaponExaiphanesBladeCoverage,
  weaponEyeOfPerceptionCoverage,
  weaponFadingTwilightCoverage,
  weaponFangOfTheMountainKingCoverage,
  weaponFavoniusCodexCoverage,
  weaponFavoniusGreatswordCoverage,
  weaponFavoniusLanceCoverage,
  weaponFavoniusSwordCoverage,
  weaponFavoniusWarbowCoverage,
  weaponFerrousShadowCoverage,
  weaponFesteringDesireCoverage,
  weaponFilletBladeCoverage,
  weaponFinaleOfTheDeepCoverage,
  weaponFlameForgedInsightCoverage,
  weaponFleuveCendreFerrymanCoverage,
  weaponFlowerWreathedFeathersCoverage,
  weaponFlowingPurityCoverage,
  weaponFluteOfEzpitzalCoverage,
  weaponFootprintOfTheRainbowCoverage,
  weaponForestRegaliaCoverage,
  weaponForgedByTheGoldenMelodyCoverage,
  weaponFracturedHaloCoverage,
  weaponFreedomSwornCoverage,
  weaponFrostbearerCoverage,
  weaponFrostbreathCoverage,
  weaponFruitOfFulfillmentCoverage,
  weaponFruitfulHookCoverage,
  weaponGestOfTheMightyWolfCoverage,
  weaponGoldenFrostboundOathCoverage,
  weaponHakushinRingCoverage,
  weaponHalberdCoverage,
  weaponHamayumiCoverage,
  weaponHaranGeppakuFutsuCoverage,
  weaponHarbingerOfDawnCoverage,
  weaponHereticsMoltenBladeCoverage,
  weaponHuntersBowCoverage,
  weaponHuntersPathCoverage,
  weaponIbisPiercerCoverage,
  weaponIronPointCoverage,
  weaponIronStingCoverage,
  weaponJadeVistaCoverage,
  weaponJadefallsSplendorCoverage,
  weaponKagotsurubeIsshinCoverage,
  weaponKagurasVerityCoverage,
  weaponKatsuragikiriNagamasaCoverage,
  weaponKeyOfKhajNisutCoverage,
  weaponKingsSquireCoverage,
  weaponKitainCrossSpearCoverage,
  weaponLightOfFoliarIncisionCoverage,
  weaponLightbearingMoonshardCoverage,
  weaponLionsRoarCoverage,
  weaponLithicBladeCoverage,
  weaponLithicSpearCoverage,
  weaponLostPrayerToTheSacredWindsCoverage,
  weaponLumidouceElegyCoverage,
  weaponLuxuriousSeaLordCoverage,
  weaponMagicGuideCoverage,
  weaponMailedFlowerCoverage,
  weaponMakhairaAquamarineCoverage,
  weaponMappaMareCoverage,
  weaponMasterKeyCoverage,
  weaponMemoryOfDustCoverage,
  weaponMessengerCoverage,
  weaponMissiveWindspearCoverage,
  weaponMistsplitterReforgedCoverage,
  weaponMitternachtsWaltzCoverage,
  weaponMoonpiercerCoverage,
  weaponMoonweaversDawnCoverage,
  weaponMountainBracingBoltCoverage,
  weaponMouunsMoonCoverage,
  weaponNightweaversLookingGlassCoverage,
  weaponNocturnesCurtainCallCoverage,
  weaponOathswornEyeCoverage,
  weaponOldMercsPalCoverage,
  weaponOtherworldlyStoryCoverage,
  weaponPeakPatrolSongCoverage,
  weaponPocketGrimoireCoverage,
  weaponPolarStarCoverage,
  weaponPortablePowerSawCoverage,
  weaponPredatorCoverage,
  weaponPrimordialJadeCutterCoverage,
  weaponPrimordialJadeWingedSpearCoverage,
  weaponProspectorsDrillCoverage,
  weaponProspectorsShovelCoverage,
  weaponPrototypeAmberCoverage,
  weaponPrototypeArchaicCoverage,
  weaponPrototypeCrescentCoverage,
  weaponPrototypeRancourCoverage,
  weaponPrototypeStarglitterCoverage,
  weaponRainbowSerpentsRainBowCoverage,
  weaponRainslasherCoverage,
  weaponRangeGaugeCoverage,
  weaponRavenBowCoverage,
  weaponRecurveBowCoverage,
  weaponRedhornStonethresherCoverage,
  weaponReliquaryOfTruthCoverage,
  weaponRightfulRewardCoverage,
  weaponRingOfYaxcheCoverage,
  weaponRoyalBowCoverage,
  weaponRoyalGreatswordCoverage,
  weaponRoyalGrimoireCoverage,
  weaponRoyalLongswordCoverage,
  weaponRoyalSpearCoverage,
  weaponRustCoverage,
  weaponSacrificersStaffCoverage,
  weaponSacrificialBowCoverage,
  weaponSacrificialFragmentsCoverage,
  weaponSacrificialGreatswordCoverage,
  weaponSacrificialJadeCoverage,
  weaponSacrificialSwordCoverage,
  weaponSapwoodBladeCoverage,
  weaponScionOfTheBlazingSunCoverage,
  weaponSeasonedHuntersBowCoverage,
  weaponSequenceOfSolitudeCoverage,
  weaponSerenitysCallCoverage,
  weaponSerpentSpineCoverage,
  weaponSharpshootersOathCoverage,
  weaponSilverSwordCoverage,
  weaponSilvershowerHeartstringsCoverage,
  weaponSkyriderGreatswordCoverage,
  weaponSkyriderSwordCoverage,
  weaponSkywardAtlasCoverage,
  weaponSkywardBladeCoverage,
  weaponSkywardHarpCoverage,
  weaponSkywardPrideCoverage,
  weaponSkywardSpineCoverage,
  weaponSlingshotCoverage,
  weaponSnareHookCoverage,
  weaponSnowTombedStarsilverCoverage,
  weaponSolarPearlCoverage,
  weaponSongOfBrokenPinesCoverage,
  weaponSongOfStillnessCoverage,
  weaponSongOfTheVigilCoverage,
  weaponSplendorOfTranquilWatersCoverage,
  weaponStaffOfHomaCoverage,
  weaponStaffOfTheScarletSandsCoverage,
  weaponStarcallersWatchCoverage,
  weaponSturdyBoneCoverage,
  weaponSummitShaperCoverage,
  weaponSunnyMorningSleepInCoverage,
  weaponSurfsUpCoverage,
  weaponSwordOfDescensionCoverage,
  weaponSwordOfNarzissenkreuzCoverage,
  weaponSymphonistOfScentsCoverage,
  weaponTalkingStickCoverage,
  weaponTamayurateiNoOhanashiCoverage,
  weaponTheAlleyFlashCoverage,
  weaponTheBellCoverage,
  weaponTheBlackSwordCoverage,
  weaponTheCatchCoverage,
  weaponTheDaybreakChroniclesCoverage,
  weaponTheDockhandsAssistantCoverage,
  weaponTheFirstGreatMagicCoverage,
  weaponTheFluteCoverage,
  weaponTheStringlessCoverage,
  weaponTheUnforgedCoverage,
  weaponTheViridescentHuntCoverage,
  weaponTheWidsithCoverage,
  weaponThrillingTalesOfDragonSlayersCoverage,
  weaponThunderingPulseCoverage,
  weaponTidalShadowCoverage,
  weaponTomeOfTheEternalFlowCoverage,
  weaponToukabouShigureCoverage,
  weaponTravelersHandySwordCoverage,
  weaponTulaytullahsRemembranceCoverage,
  weaponTwinNephriteCoverage,
  weaponUltimateOverlordsMegaMagicSwordCoverage,
  weaponUrakuMisugiriCoverage,
  weaponVerdictCoverage,
  weaponVividNotionsCoverage,
  weaponVortexVanquisherCoverage,
  weaponWanderingEvenstarCoverage,
  weaponWasterGreatswordCoverage,
  weaponWavebreakersFinCoverage,
  weaponWaveridingWhirlCoverage,
  weaponWhiteIronGreatswordCoverage,
  weaponWhiteTasselCoverage,
  weaponWhiteblindCoverage,
  weaponWhitelakeFrostfeatherCoverage,
  weaponWindblumeOdeCoverage,
  weaponWineAndSongCoverage,
  weaponWolfFangCoverage,
  weaponWolfsGravestoneCoverage,
  weaponXiphosMoonlightCoverage
]
