// Generated by tools/generate-registries.ts; do not edit by hand.
import type { CombatEquipmentCapability } from "../combat/capabilities.js"

import { otherworldlyStoryCombatCapabilities } from "../weapons/otherworldly-story/effects.js"
import { prototypeAmberCombatCapabilities } from "../weapons/prototype-amber/effects.js"
import { sacrificialBowCombatCapabilities } from "../weapons/sacrificial-bow/effects.js"
import { sacrificialFragmentsCombatCapabilities } from "../weapons/sacrificial-fragments/effects.js"
import { sacrificialGreatswordCombatCapabilities } from "../weapons/sacrificial-greatsword/effects.js"
import { sacrificialSwordCombatCapabilities } from "../weapons/sacrificial-sword/effects.js"
import { travelersHandySwordCombatCapabilities } from "../weapons/travelers-handy-sword/effects.js"
import { shimenawasReminiscenceCombatCapabilities } from "../artifacts/shimenawas-reminiscence/effects.js"

export const equipmentCombatCapabilities: readonly CombatEquipmentCapability[] = [
  ...otherworldlyStoryCombatCapabilities,
  ...prototypeAmberCombatCapabilities,
  ...sacrificialBowCombatCapabilities,
  ...sacrificialFragmentsCombatCapabilities,
  ...sacrificialGreatswordCombatCapabilities,
  ...sacrificialSwordCombatCapabilities,
  ...travelersHandySwordCombatCapabilities,
  ...shimenawasReminiscenceCombatCapabilities
]
