// Generated by tools/generate-registries.ts; do not edit by hand.
import type { CombatEquipmentCapability } from "../combat/capabilities.js"

import { sacrificialBowCombatCapabilities } from "../weapons/sacrificial-bow/effects.js"
import { sacrificialFragmentsCombatCapabilities } from "../weapons/sacrificial-fragments/effects.js"
import { sacrificialGreatswordCombatCapabilities } from "../weapons/sacrificial-greatsword/effects.js"
import { sacrificialSwordCombatCapabilities } from "../weapons/sacrificial-sword/effects.js"

export const equipmentCombatCapabilities: readonly CombatEquipmentCapability[] = [
  ...sacrificialBowCombatCapabilities,
  ...sacrificialFragmentsCombatCapabilities,
  ...sacrificialGreatswordCombatCapabilities,
  ...sacrificialSwordCombatCapabilities
]
