// Generated by tools/generate-registries.ts; do not edit by hand.
import type { CombatActionEffect } from "../combat/types.js"

import { aDayCarvedFromRisingWindsCombatActionEffects as artifactADayCarvedFromRisingWindsEffects } from "../artifacts/a-day-carved-from-rising-winds/effects.js"
import { adventurerCombatActionEffects as artifactAdventurerEffects } from "../artifacts/adventurer/effects.js"
import { archaicPetraCombatActionEffects as artifactArchaicPetraEffects } from "../artifacts/archaic-petra/effects.js"
import { aubadeOfMorningstarAndMoonCombatActionEffects as artifactAubadeOfMorningstarAndMoonEffects } from "../artifacts/aubade-of-morningstar-and-moon/effects.js"
import { berserkerCombatActionEffects as artifactBerserkerEffects } from "../artifacts/berserker/effects.js"
import { blizzardStrayerCombatActionEffects as artifactBlizzardStrayerEffects } from "../artifacts/blizzard-strayer/effects.js"
import { bloodstainedChivalryCombatActionEffects as artifactBloodstainedChivalryEffects } from "../artifacts/bloodstained-chivalry/effects.js"
import { braveHeartCombatActionEffects as artifactBraveHeartEffects } from "../artifacts/brave-heart/effects.js"
import { celestialGiftCombatActionEffects as artifactCelestialGiftEffects } from "../artifacts/celestial-gift/effects.js"
import { crimsonWitchOfFlamesCombatActionEffects as artifactCrimsonWitchOfFlamesEffects } from "../artifacts/crimson-witch-of-flames/effects.js"
import { deepwoodMemoriesCombatActionEffects as artifactDeepwoodMemoriesEffects } from "../artifacts/deepwood-memories/effects.js"
import { defendersWillCombatActionEffects as artifactDefendersWillEffects } from "../artifacts/defenders-will/effects.js"
import { desertPavilionChronicleCombatActionEffects as artifactDesertPavilionChronicleEffects } from "../artifacts/desert-pavilion-chronicle/effects.js"
import { disenchantmentInDeepShadowCombatActionEffects as artifactDisenchantmentInDeepShadowEffects } from "../artifacts/disenchantment-in-deep-shadow/effects.js"
import { echoesOfAnOfferingCombatActionEffects as artifactEchoesOfAnOfferingEffects } from "../artifacts/echoes-of-an-offering/effects.js"
import { emblemOfSeveredFateCombatActionEffects as artifactEmblemOfSeveredFateEffects } from "../artifacts/emblem-of-severed-fate/effects.js"
import { finaleOfTheDeepGalleriesCombatActionEffects as artifactFinaleOfTheDeepGalleriesEffects } from "../artifacts/finale-of-the-deep-galleries/effects.js"
import { flowerOfParadiseLostCombatActionEffects as artifactFlowerOfParadiseLostEffects } from "../artifacts/flower-of-paradise-lost/effects.js"
import { fragmentOfHarmonicWhimsyCombatActionEffects as artifactFragmentOfHarmonicWhimsyEffects } from "../artifacts/fragment-of-harmonic-whimsy/effects.js"
import { gamblerCombatActionEffects as artifactGamblerEffects } from "../artifacts/gambler/effects.js"
import { gildedDreamsCombatActionEffects as artifactGildedDreamsEffects } from "../artifacts/gilded-dreams/effects.js"
import { gladiatorsFinaleCombatActionEffects as artifactGladiatorsFinaleEffects } from "../artifacts/gladiators-finale/effects.js"
import { goldenTroupeCombatActionEffects as artifactGoldenTroupeEffects } from "../artifacts/golden-troupe/effects.js"
import { heartOfDepthCombatActionEffects as artifactHeartOfDepthEffects } from "../artifacts/heart-of-depth/effects.js"
import { heartOfTheFurnaceCombatActionEffects as artifactHeartOfTheFurnaceEffects } from "../artifacts/heart-of-the-furnace/effects.js"
import { huskOfOpulentDreamsCombatActionEffects as artifactHuskOfOpulentDreamsEffects } from "../artifacts/husk-of-opulent-dreams/effects.js"
import { instructorCombatActionEffects as artifactInstructorEffects } from "../artifacts/instructor/effects.js"
import { lavawalkerCombatActionEffects as artifactLavawalkerEffects } from "../artifacts/lavawalker/effects.js"
import { longNightsOathCombatActionEffects as artifactLongNightsOathEffects } from "../artifacts/long-nights-oath/effects.js"
import { luckyDogCombatActionEffects as artifactLuckyDogEffects } from "../artifacts/lucky-dog/effects.js"
import { maidenBelovedCombatActionEffects as artifactMaidenBelovedEffects } from "../artifacts/maiden-beloved/effects.js"
import { marechausseeHunterCombatActionEffects as artifactMarechausseeHunterEffects } from "../artifacts/marechaussee-hunter/effects.js"
import { martialArtistCombatActionEffects as artifactMartialArtistEffects } from "../artifacts/martial-artist/effects.js"
import { nightOfTheSkysUnveilingCombatActionEffects as artifactNightOfTheSkysUnveilingEffects } from "../artifacts/night-of-the-skys-unveiling/effects.js"
import { nighttimeWhispersInTheEchoingWoodsCombatActionEffects as artifactNighttimeWhispersInTheEchoingWoodsEffects } from "../artifacts/nighttime-whispers-in-the-echoing-woods/effects.js"
import { noblesseObligeCombatActionEffects as artifactNoblesseObligeEffects } from "../artifacts/noblesse-oblige/effects.js"
import { nymphsDreamCombatActionEffects as artifactNymphsDreamEffects } from "../artifacts/nymphs-dream/effects.js"
import { obsidianCodexCombatActionEffects as artifactObsidianCodexEffects } from "../artifacts/obsidian-codex/effects.js"
import { oceanHuedClamCombatActionEffects as artifactOceanHuedClamEffects } from "../artifacts/ocean-hued-clam/effects.js"
import { paleFlameCombatActionEffects as artifactPaleFlameEffects } from "../artifacts/pale-flame/effects.js"
import { prayersForDestinyCombatActionEffects as artifactPrayersForDestinyEffects } from "../artifacts/prayers-for-destiny/effects.js"
import { prayersForIlluminationCombatActionEffects as artifactPrayersForIlluminationEffects } from "../artifacts/prayers-for-illumination/effects.js"
import { prayersForWisdomCombatActionEffects as artifactPrayersForWisdomEffects } from "../artifacts/prayers-for-wisdom/effects.js"
import { prayersToSpringtimeCombatActionEffects as artifactPrayersToSpringtimeEffects } from "../artifacts/prayers-to-springtime/effects.js"
import { resolutionOfSojournerCombatActionEffects as artifactResolutionOfSojournerEffects } from "../artifacts/resolution-of-sojourner/effects.js"
import { retracingBolideCombatActionEffects as artifactRetracingBolideEffects } from "../artifacts/retracing-bolide/effects.js"
import { scarletProofCombatActionEffects as artifactScarletProofEffects } from "../artifacts/scarlet-proof/effects.js"
import { scholarCombatActionEffects as artifactScholarEffects } from "../artifacts/scholar/effects.js"
import { scrollOfTheHeroOfCinderCityCombatActionEffects as artifactScrollOfTheHeroOfCinderCityEffects } from "../artifacts/scroll-of-the-hero-of-cinder-city/effects.js"
import { shimenawasReminiscenceCombatActionEffects as artifactShimenawasReminiscenceEffects } from "../artifacts/shimenawas-reminiscence/effects.js"
import { silkenMoonsSerenadeCombatActionEffects as artifactSilkenMoonsSerenadeEffects } from "../artifacts/silken-moons-serenade/effects.js"
import { songOfDaysPastCombatActionEffects as artifactSongOfDaysPastEffects } from "../artifacts/song-of-days-past/effects.js"
import { tenacityOfTheMillelithCombatActionEffects as artifactTenacityOfTheMillelithEffects } from "../artifacts/tenacity-of-the-millelith/effects.js"
import { theExileCombatActionEffects as artifactTheExileEffects } from "../artifacts/the-exile/effects.js"
import { thunderingFuryCombatActionEffects as artifactThunderingFuryEffects } from "../artifacts/thundering-fury/effects.js"
import { thundersootherCombatActionEffects as artifactThundersootherEffects } from "../artifacts/thundersoother/effects.js"
import { tinyMiracleCombatActionEffects as artifactTinyMiracleEffects } from "../artifacts/tiny-miracle/effects.js"
import { travelingDoctorCombatActionEffects as artifactTravelingDoctorEffects } from "../artifacts/traveling-doctor/effects.js"
import { unfinishedReverieCombatActionEffects as artifactUnfinishedReverieEffects } from "../artifacts/unfinished-reverie/effects.js"
import { vermillionHereafterCombatActionEffects as artifactVermillionHereafterEffects } from "../artifacts/vermillion-hereafter/effects.js"
import { viridescentVenererCombatActionEffects as artifactViridescentVenererEffects } from "../artifacts/viridescent-venerer/effects.js"
import { vourukashasGlowCombatActionEffects as artifactVourukashasGlowEffects } from "../artifacts/vourukashas-glow/effects.js"
import { wanderersTroupeCombatActionEffects as artifactWanderersTroupeEffects } from "../artifacts/wanderers-troupe/effects.js"
import { aTeaspoonOfTranscendenceCombatActionEffects as weaponATeaspoonOfTranscendenceEffects } from "../weapons/a-teaspoon-of-transcendence/effects.js"
import { aThousandBlazingSunsCombatActionEffects as weaponAThousandBlazingSunsEffects } from "../weapons/a-thousand-blazing-suns/effects.js"
import { aThousandFloatingDreamsCombatActionEffects as weaponAThousandFloatingDreamsEffects } from "../weapons/a-thousand-floating-dreams/effects.js"
import { absolutionCombatActionEffects as weaponAbsolutionEffects } from "../weapons/absolution/effects.js"
import { akuoumaruCombatActionEffects as weaponAkuoumaruEffects } from "../weapons/akuoumaru/effects.js"
import { alleyHunterCombatActionEffects as weaponAlleyHunterEffects } from "../weapons/alley-hunter/effects.js"
import { amenomaKageuchiCombatActionEffects as weaponAmenomaKageuchiEffects } from "../weapons/amenoma-kageuchi/effects.js"
import { amosBowCombatActionEffects as weaponAmosBowEffects } from "../weapons/amos-bow/effects.js"
import { angelosHeptadesCombatActionEffects as weaponAngelosHeptadesEffects } from "../weapons/angelos-heptades/effects.js"
import { apprenticesNotesCombatActionEffects as weaponApprenticesNotesEffects } from "../weapons/apprentices-notes/effects.js"
import { aquaSimulacraCombatActionEffects as weaponAquaSimulacraEffects } from "../weapons/aqua-simulacra/effects.js"
import { aquilaFavoniaCombatActionEffects as weaponAquilaFavoniaEffects } from "../weapons/aquila-favonia/effects.js"
import { ashGravenDrinkingHornCombatActionEffects as weaponAshGravenDrinkingHornEffects } from "../weapons/ash-graven-drinking-horn/effects.js"
import { astralVulturesCrimsonPlumageCombatActionEffects as weaponAstralVulturesCrimsonPlumageEffects } from "../weapons/astral-vultures-crimson-plumage/effects.js"
import { athameArtisCombatActionEffects as weaponAthameArtisEffects } from "../weapons/athame-artis/effects.js"
import { azurelightCombatActionEffects as weaponAzurelightEffects } from "../weapons/azurelight/effects.js"
import { balladOfTheBoundlessBlueCombatActionEffects as weaponBalladOfTheBoundlessBlueEffects } from "../weapons/ballad-of-the-boundless-blue/effects.js"
import { balladOfTheFjordsCombatActionEffects as weaponBalladOfTheFjordsEffects } from "../weapons/ballad-of-the-fjords/effects.js"
import { beaconOfTheReedSeaCombatActionEffects as weaponBeaconOfTheReedSeaEffects } from "../weapons/beacon-of-the-reed-sea/effects.js"
import { beginnersProtectorCombatActionEffects as weaponBeginnersProtectorEffects } from "../weapons/beginners-protector/effects.js"
import { blackTasselCombatActionEffects as weaponBlackTasselEffects } from "../weapons/black-tassel/effects.js"
import { blackcliffAgateCombatActionEffects as weaponBlackcliffAgateEffects } from "../weapons/blackcliff-agate/effects.js"
import { blackcliffLongswordCombatActionEffects as weaponBlackcliffLongswordEffects } from "../weapons/blackcliff-longsword/effects.js"
import { blackcliffPoleCombatActionEffects as weaponBlackcliffPoleEffects } from "../weapons/blackcliff-pole/effects.js"
import { blackcliffSlasherCombatActionEffects as weaponBlackcliffSlasherEffects } from "../weapons/blackcliff-slasher/effects.js"
import { blackcliffWarbowCombatActionEffects as weaponBlackcliffWarbowEffects } from "../weapons/blackcliff-warbow/effects.js"
import { blackmarrowLanternCombatActionEffects as weaponBlackmarrowLanternEffects } from "../weapons/blackmarrow-lantern/effects.js"
import { bladeOfAtonementCombatActionEffects as weaponBladeOfAtonementEffects } from "../weapons/blade-of-atonement/effects.js"
import { bloodsoakedRuinsCombatActionEffects as weaponBloodsoakedRuinsEffects } from "../weapons/bloodsoaked-ruins/effects.js"
import { bloodtaintedGreatswordCombatActionEffects as weaponBloodtaintedGreatswordEffects } from "../weapons/bloodtainted-greatsword/effects.js"
import { calamityOfEshuCombatActionEffects as weaponCalamityOfEshuEffects } from "../weapons/calamity-of-eshu/effects.js"
import { calamityQuellerCombatActionEffects as weaponCalamityQuellerEffects } from "../weapons/calamity-queller/effects.js"
import { cashflowSupervisionCombatActionEffects as weaponCashflowSupervisionEffects } from "../weapons/cashflow-supervision/effects.js"
import { chainBreakerCombatActionEffects as weaponChainBreakerEffects } from "../weapons/chain-breaker/effects.js"
import { cinnabarSpindleCombatActionEffects as weaponCinnabarSpindleEffects } from "../weapons/cinnabar-spindle/effects.js"
import { clashOfKingsCombatActionEffects as weaponClashOfKingsEffects } from "../weapons/clash-of-kings/effects.js"
import { cloudforgedCombatActionEffects as weaponCloudforgedEffects } from "../weapons/cloudforged/effects.js"
import { compoundBowCombatActionEffects as weaponCompoundBowEffects } from "../weapons/compound-bow/effects.js"
import { coolSteelCombatActionEffects as weaponCoolSteelEffects } from "../weapons/cool-steel/effects.js"
import { covenantOfFrostAndSnowCombatActionEffects as weaponCovenantOfFrostAndSnowEffects } from "../weapons/covenant-of-frost-and-snow/effects.js"
import { cranesEchoingCallCombatActionEffects as weaponCranesEchoingCallEffects } from "../weapons/cranes-echoing-call/effects.js"
import { crescentPikeCombatActionEffects as weaponCrescentPikeEffects } from "../weapons/crescent-pike/effects.js"
import { crimsonMoonsSemblanceCombatActionEffects as weaponCrimsonMoonsSemblanceEffects } from "../weapons/crimson-moons-semblance/effects.js"
import { darkIronSwordCombatActionEffects as weaponDarkIronSwordEffects } from "../weapons/dark-iron-sword/effects.js"
import { dawningFrostCombatActionEffects as weaponDawningFrostEffects } from "../weapons/dawning-frost/effects.js"
import { deathmatchCombatActionEffects as weaponDeathmatchEffects } from "../weapons/deathmatch/effects.js"
import { debateClubCombatActionEffects as weaponDebateClubEffects } from "../weapons/debate-club/effects.js"
import { dialoguesOfTheDesertSagesCombatActionEffects as weaponDialoguesOfTheDesertSagesEffects } from "../weapons/dialogues-of-the-desert-sages/effects.js"
import { disasterAndRemorseCombatActionEffects as weaponDisasterAndRemorseEffects } from "../weapons/disaster-and-remorse/effects.js"
import { dodocoTalesCombatActionEffects as weaponDodocoTalesEffects } from "../weapons/dodoco-tales/effects.js"
import { dragonsBaneCombatActionEffects as weaponDragonsBaneEffects } from "../weapons/dragons-bane/effects.js"
import { dragonspineSpearCombatActionEffects as weaponDragonspineSpearEffects } from "../weapons/dragonspine-spear/effects.js"
import { dullBladeCombatActionEffects as weaponDullBladeEffects } from "../weapons/dull-blade/effects.js"
import { earthShakerCombatActionEffects as weaponEarthShakerEffects } from "../weapons/earth-shaker/effects.js"
import { echoesOfTheHeartCombatActionEffects as weaponEchoesOfTheHeartEffects } from "../weapons/echoes-of-the-heart/effects.js"
import { elegyForTheEndCombatActionEffects as weaponElegyForTheEndEffects } from "../weapons/elegy-for-the-end/effects.js"
import { emberwellCombatActionEffects as weaponEmberwellEffects } from "../weapons/emberwell/effects.js"
import { emeraldOrbCombatActionEffects as weaponEmeraldOrbEffects } from "../weapons/emerald-orb/effects.js"
import { endOfTheLineCombatActionEffects as weaponEndOfTheLineEffects } from "../weapons/end-of-the-line/effects.js"
import { engulfingLightningCombatActionEffects as weaponEngulfingLightningEffects } from "../weapons/engulfing-lightning/effects.js"
import { etherlightSpindleluteCombatActionEffects as weaponEtherlightSpindleluteEffects } from "../weapons/etherlight-spindlelute/effects.js"
import { everlastingMoonglowCombatActionEffects as weaponEverlastingMoonglowEffects } from "../weapons/everlasting-moonglow/effects.js"
import { exaiphanesBladeCombatActionEffects as weaponExaiphanesBladeEffects } from "../weapons/exaiphanes-blade/effects.js"
import { eyeOfPerceptionCombatActionEffects as weaponEyeOfPerceptionEffects } from "../weapons/eye-of-perception/effects.js"
import { fadingTwilightCombatActionEffects as weaponFadingTwilightEffects } from "../weapons/fading-twilight/effects.js"
import { fangOfTheMountainKingCombatActionEffects as weaponFangOfTheMountainKingEffects } from "../weapons/fang-of-the-mountain-king/effects.js"
import { favoniusCodexCombatActionEffects as weaponFavoniusCodexEffects } from "../weapons/favonius-codex/effects.js"
import { favoniusGreatswordCombatActionEffects as weaponFavoniusGreatswordEffects } from "../weapons/favonius-greatsword/effects.js"
import { favoniusLanceCombatActionEffects as weaponFavoniusLanceEffects } from "../weapons/favonius-lance/effects.js"
import { favoniusSwordCombatActionEffects as weaponFavoniusSwordEffects } from "../weapons/favonius-sword/effects.js"
import { favoniusWarbowCombatActionEffects as weaponFavoniusWarbowEffects } from "../weapons/favonius-warbow/effects.js"
import { ferrousShadowCombatActionEffects as weaponFerrousShadowEffects } from "../weapons/ferrous-shadow/effects.js"
import { festeringDesireCombatActionEffects as weaponFesteringDesireEffects } from "../weapons/festering-desire/effects.js"
import { filletBladeCombatActionEffects as weaponFilletBladeEffects } from "../weapons/fillet-blade/effects.js"
import { finaleOfTheDeepCombatActionEffects as weaponFinaleOfTheDeepEffects } from "../weapons/finale-of-the-deep/effects.js"
import { flameForgedInsightCombatActionEffects as weaponFlameForgedInsightEffects } from "../weapons/flame-forged-insight/effects.js"
import { fleuveCendreFerrymanCombatActionEffects as weaponFleuveCendreFerrymanEffects } from "../weapons/fleuve-cendre-ferryman/effects.js"
import { flowerWreathedFeathersCombatActionEffects as weaponFlowerWreathedFeathersEffects } from "../weapons/flower-wreathed-feathers/effects.js"
import { flowingPurityCombatActionEffects as weaponFlowingPurityEffects } from "../weapons/flowing-purity/effects.js"
import { fluteOfEzpitzalCombatActionEffects as weaponFluteOfEzpitzalEffects } from "../weapons/flute-of-ezpitzal/effects.js"
import { footprintOfTheRainbowCombatActionEffects as weaponFootprintOfTheRainbowEffects } from "../weapons/footprint-of-the-rainbow/effects.js"
import { forestRegaliaCombatActionEffects as weaponForestRegaliaEffects } from "../weapons/forest-regalia/effects.js"
import { forgedByTheGoldenMelodyCombatActionEffects as weaponForgedByTheGoldenMelodyEffects } from "../weapons/forged-by-the-golden-melody/effects.js"
import { fracturedHaloCombatActionEffects as weaponFracturedHaloEffects } from "../weapons/fractured-halo/effects.js"
import { freedomSwornCombatActionEffects as weaponFreedomSwornEffects } from "../weapons/freedom-sworn/effects.js"
import { frostbearerCombatActionEffects as weaponFrostbearerEffects } from "../weapons/frostbearer/effects.js"
import { frostbreathCombatActionEffects as weaponFrostbreathEffects } from "../weapons/frostbreath/effects.js"
import { fruitOfFulfillmentCombatActionEffects as weaponFruitOfFulfillmentEffects } from "../weapons/fruit-of-fulfillment/effects.js"
import { fruitfulHookCombatActionEffects as weaponFruitfulHookEffects } from "../weapons/fruitful-hook/effects.js"
import { gestOfTheMightyWolfCombatActionEffects as weaponGestOfTheMightyWolfEffects } from "../weapons/gest-of-the-mighty-wolf/effects.js"
import { goldenFrostboundOathCombatActionEffects as weaponGoldenFrostboundOathEffects } from "../weapons/golden-frostbound-oath/effects.js"
import { hakushinRingCombatActionEffects as weaponHakushinRingEffects } from "../weapons/hakushin-ring/effects.js"
import { halberdCombatActionEffects as weaponHalberdEffects } from "../weapons/halberd/effects.js"
import { hamayumiCombatActionEffects as weaponHamayumiEffects } from "../weapons/hamayumi/effects.js"
import { haranGeppakuFutsuCombatActionEffects as weaponHaranGeppakuFutsuEffects } from "../weapons/haran-geppaku-futsu/effects.js"
import { harbingerOfDawnCombatActionEffects as weaponHarbingerOfDawnEffects } from "../weapons/harbinger-of-dawn/effects.js"
import { hereticsMoltenBladeCombatActionEffects as weaponHereticsMoltenBladeEffects } from "../weapons/heretics-molten-blade/effects.js"
import { huntersBowCombatActionEffects as weaponHuntersBowEffects } from "../weapons/hunters-bow/effects.js"
import { huntersPathCombatActionEffects as weaponHuntersPathEffects } from "../weapons/hunters-path/effects.js"
import { ibisPiercerCombatActionEffects as weaponIbisPiercerEffects } from "../weapons/ibis-piercer/effects.js"
import { ironPointCombatActionEffects as weaponIronPointEffects } from "../weapons/iron-point/effects.js"
import { ironStingCombatActionEffects as weaponIronStingEffects } from "../weapons/iron-sting/effects.js"
import { jadeVistaCombatActionEffects as weaponJadeVistaEffects } from "../weapons/jade-vista/effects.js"
import { jadefallsSplendorCombatActionEffects as weaponJadefallsSplendorEffects } from "../weapons/jadefalls-splendor/effects.js"
import { kagotsurubeIsshinCombatActionEffects as weaponKagotsurubeIsshinEffects } from "../weapons/kagotsurube-isshin/effects.js"
import { kagurasVerityCombatActionEffects as weaponKagurasVerityEffects } from "../weapons/kaguras-verity/effects.js"
import { katsuragikiriNagamasaCombatActionEffects as weaponKatsuragikiriNagamasaEffects } from "../weapons/katsuragikiri-nagamasa/effects.js"
import { keyOfKhajNisutCombatActionEffects as weaponKeyOfKhajNisutEffects } from "../weapons/key-of-khaj-nisut/effects.js"
import { kingsSquireCombatActionEffects as weaponKingsSquireEffects } from "../weapons/kings-squire/effects.js"
import { kitainCrossSpearCombatActionEffects as weaponKitainCrossSpearEffects } from "../weapons/kitain-cross-spear/effects.js"
import { lightOfFoliarIncisionCombatActionEffects as weaponLightOfFoliarIncisionEffects } from "../weapons/light-of-foliar-incision/effects.js"
import { lightbearingMoonshardCombatActionEffects as weaponLightbearingMoonshardEffects } from "../weapons/lightbearing-moonshard/effects.js"
import { lionsRoarCombatActionEffects as weaponLionsRoarEffects } from "../weapons/lions-roar/effects.js"
import { lithicBladeCombatActionEffects as weaponLithicBladeEffects } from "../weapons/lithic-blade/effects.js"
import { lithicSpearCombatActionEffects as weaponLithicSpearEffects } from "../weapons/lithic-spear/effects.js"
import { lostPrayerToTheSacredWindsCombatActionEffects as weaponLostPrayerToTheSacredWindsEffects } from "../weapons/lost-prayer-to-the-sacred-winds/effects.js"
import { lumidouceElegyCombatActionEffects as weaponLumidouceElegyEffects } from "../weapons/lumidouce-elegy/effects.js"
import { luxuriousSeaLordCombatActionEffects as weaponLuxuriousSeaLordEffects } from "../weapons/luxurious-sea-lord/effects.js"
import { magicGuideCombatActionEffects as weaponMagicGuideEffects } from "../weapons/magic-guide/effects.js"
import { mailedFlowerCombatActionEffects as weaponMailedFlowerEffects } from "../weapons/mailed-flower/effects.js"
import { makhairaAquamarineCombatActionEffects as weaponMakhairaAquamarineEffects } from "../weapons/makhaira-aquamarine/effects.js"
import { mappaMareCombatActionEffects as weaponMappaMareEffects } from "../weapons/mappa-mare/effects.js"
import { masterKeyCombatActionEffects as weaponMasterKeyEffects } from "../weapons/master-key/effects.js"
import { memoryOfDustCombatActionEffects as weaponMemoryOfDustEffects } from "../weapons/memory-of-dust/effects.js"
import { messengerCombatActionEffects as weaponMessengerEffects } from "../weapons/messenger/effects.js"
import { missiveWindspearCombatActionEffects as weaponMissiveWindspearEffects } from "../weapons/missive-windspear/effects.js"
import { mistsplitterReforgedCombatActionEffects as weaponMistsplitterReforgedEffects } from "../weapons/mistsplitter-reforged/effects.js"
import { mitternachtsWaltzCombatActionEffects as weaponMitternachtsWaltzEffects } from "../weapons/mitternachts-waltz/effects.js"
import { moonpiercerCombatActionEffects as weaponMoonpiercerEffects } from "../weapons/moonpiercer/effects.js"
import { moonweaversDawnCombatActionEffects as weaponMoonweaversDawnEffects } from "../weapons/moonweavers-dawn/effects.js"
import { mountainBracingBoltCombatActionEffects as weaponMountainBracingBoltEffects } from "../weapons/mountain-bracing-bolt/effects.js"
import { mouunsMoonCombatActionEffects as weaponMouunsMoonEffects } from "../weapons/mouuns-moon/effects.js"
import { nightweaversLookingGlassCombatActionEffects as weaponNightweaversLookingGlassEffects } from "../weapons/nightweavers-looking-glass/effects.js"
import { nocturnesCurtainCallCombatActionEffects as weaponNocturnesCurtainCallEffects } from "../weapons/nocturnes-curtain-call/effects.js"
import { oathswornEyeCombatActionEffects as weaponOathswornEyeEffects } from "../weapons/oathsworn-eye/effects.js"
import { oldMercsPalCombatActionEffects as weaponOldMercsPalEffects } from "../weapons/old-mercs-pal/effects.js"
import { otherworldlyStoryCombatActionEffects as weaponOtherworldlyStoryEffects } from "../weapons/otherworldly-story/effects.js"
import { peakPatrolSongCombatActionEffects as weaponPeakPatrolSongEffects } from "../weapons/peak-patrol-song/effects.js"
import { pocketGrimoireCombatActionEffects as weaponPocketGrimoireEffects } from "../weapons/pocket-grimoire/effects.js"
import { polarStarCombatActionEffects as weaponPolarStarEffects } from "../weapons/polar-star/effects.js"
import { portablePowerSawCombatActionEffects as weaponPortablePowerSawEffects } from "../weapons/portable-power-saw/effects.js"
import { predatorCombatActionEffects as weaponPredatorEffects } from "../weapons/predator/effects.js"
import { primordialJadeCutterCombatActionEffects as weaponPrimordialJadeCutterEffects } from "../weapons/primordial-jade-cutter/effects.js"
import { primordialJadeWingedSpearCombatActionEffects as weaponPrimordialJadeWingedSpearEffects } from "../weapons/primordial-jade-winged-spear/effects.js"
import { prospectorsDrillCombatActionEffects as weaponProspectorsDrillEffects } from "../weapons/prospectors-drill/effects.js"
import { prospectorsShovelCombatActionEffects as weaponProspectorsShovelEffects } from "../weapons/prospectors-shovel/effects.js"
import { prototypeAmberCombatActionEffects as weaponPrototypeAmberEffects } from "../weapons/prototype-amber/effects.js"
import { prototypeArchaicCombatActionEffects as weaponPrototypeArchaicEffects } from "../weapons/prototype-archaic/effects.js"
import { prototypeCrescentCombatActionEffects as weaponPrototypeCrescentEffects } from "../weapons/prototype-crescent/effects.js"
import { prototypeRancourCombatActionEffects as weaponPrototypeRancourEffects } from "../weapons/prototype-rancour/effects.js"
import { prototypeStarglitterCombatActionEffects as weaponPrototypeStarglitterEffects } from "../weapons/prototype-starglitter/effects.js"
import { rainbowSerpentsRainBowCombatActionEffects as weaponRainbowSerpentsRainBowEffects } from "../weapons/rainbow-serpents-rain-bow/effects.js"
import { rainslasherCombatActionEffects as weaponRainslasherEffects } from "../weapons/rainslasher/effects.js"
import { rangeGaugeCombatActionEffects as weaponRangeGaugeEffects } from "../weapons/range-gauge/effects.js"
import { ravenBowCombatActionEffects as weaponRavenBowEffects } from "../weapons/raven-bow/effects.js"
import { recurveBowCombatActionEffects as weaponRecurveBowEffects } from "../weapons/recurve-bow/effects.js"
import { redhornStonethresherCombatActionEffects as weaponRedhornStonethresherEffects } from "../weapons/redhorn-stonethresher/effects.js"
import { reliquaryOfTruthCombatActionEffects as weaponReliquaryOfTruthEffects } from "../weapons/reliquary-of-truth/effects.js"
import { rightfulRewardCombatActionEffects as weaponRightfulRewardEffects } from "../weapons/rightful-reward/effects.js"
import { ringOfYaxcheCombatActionEffects as weaponRingOfYaxcheEffects } from "../weapons/ring-of-yaxche/effects.js"
import { royalBowCombatActionEffects as weaponRoyalBowEffects } from "../weapons/royal-bow/effects.js"
import { royalGreatswordCombatActionEffects as weaponRoyalGreatswordEffects } from "../weapons/royal-greatsword/effects.js"
import { royalGrimoireCombatActionEffects as weaponRoyalGrimoireEffects } from "../weapons/royal-grimoire/effects.js"
import { royalLongswordCombatActionEffects as weaponRoyalLongswordEffects } from "../weapons/royal-longsword/effects.js"
import { royalSpearCombatActionEffects as weaponRoyalSpearEffects } from "../weapons/royal-spear/effects.js"
import { rustCombatActionEffects as weaponRustEffects } from "../weapons/rust/effects.js"
import { sacrificersStaffCombatActionEffects as weaponSacrificersStaffEffects } from "../weapons/sacrificers-staff/effects.js"
import { sacrificialBowCombatActionEffects as weaponSacrificialBowEffects } from "../weapons/sacrificial-bow/effects.js"
import { sacrificialFragmentsCombatActionEffects as weaponSacrificialFragmentsEffects } from "../weapons/sacrificial-fragments/effects.js"
import { sacrificialGreatswordCombatActionEffects as weaponSacrificialGreatswordEffects } from "../weapons/sacrificial-greatsword/effects.js"
import { sacrificialJadeCombatActionEffects as weaponSacrificialJadeEffects } from "../weapons/sacrificial-jade/effects.js"
import { sacrificialSwordCombatActionEffects as weaponSacrificialSwordEffects } from "../weapons/sacrificial-sword/effects.js"
import { sapwoodBladeCombatActionEffects as weaponSapwoodBladeEffects } from "../weapons/sapwood-blade/effects.js"
import { scionOfTheBlazingSunCombatActionEffects as weaponScionOfTheBlazingSunEffects } from "../weapons/scion-of-the-blazing-sun/effects.js"
import { seasonedHuntersBowCombatActionEffects as weaponSeasonedHuntersBowEffects } from "../weapons/seasoned-hunters-bow/effects.js"
import { sequenceOfSolitudeCombatActionEffects as weaponSequenceOfSolitudeEffects } from "../weapons/sequence-of-solitude/effects.js"
import { serenitysCallCombatActionEffects as weaponSerenitysCallEffects } from "../weapons/serenitys-call/effects.js"
import { serpentSpineCombatActionEffects as weaponSerpentSpineEffects } from "../weapons/serpent-spine/effects.js"
import { sharpshootersOathCombatActionEffects as weaponSharpshootersOathEffects } from "../weapons/sharpshooters-oath/effects.js"
import { silverSwordCombatActionEffects as weaponSilverSwordEffects } from "../weapons/silver-sword/effects.js"
import { silvershowerHeartstringsCombatActionEffects as weaponSilvershowerHeartstringsEffects } from "../weapons/silvershower-heartstrings/effects.js"
import { skyriderGreatswordCombatActionEffects as weaponSkyriderGreatswordEffects } from "../weapons/skyrider-greatsword/effects.js"
import { skyriderSwordCombatActionEffects as weaponSkyriderSwordEffects } from "../weapons/skyrider-sword/effects.js"
import { skywardAtlasCombatActionEffects as weaponSkywardAtlasEffects } from "../weapons/skyward-atlas/effects.js"
import { skywardBladeCombatActionEffects as weaponSkywardBladeEffects } from "../weapons/skyward-blade/effects.js"
import { skywardHarpCombatActionEffects as weaponSkywardHarpEffects } from "../weapons/skyward-harp/effects.js"
import { skywardPrideCombatActionEffects as weaponSkywardPrideEffects } from "../weapons/skyward-pride/effects.js"
import { skywardSpineCombatActionEffects as weaponSkywardSpineEffects } from "../weapons/skyward-spine/effects.js"
import { slingshotCombatActionEffects as weaponSlingshotEffects } from "../weapons/slingshot/effects.js"
import { snareHookCombatActionEffects as weaponSnareHookEffects } from "../weapons/snare-hook/effects.js"
import { snowTombedStarsilverCombatActionEffects as weaponSnowTombedStarsilverEffects } from "../weapons/snow-tombed-starsilver/effects.js"
import { solarPearlCombatActionEffects as weaponSolarPearlEffects } from "../weapons/solar-pearl/effects.js"
import { songOfBrokenPinesCombatActionEffects as weaponSongOfBrokenPinesEffects } from "../weapons/song-of-broken-pines/effects.js"
import { songOfStillnessCombatActionEffects as weaponSongOfStillnessEffects } from "../weapons/song-of-stillness/effects.js"
import { songOfTheVigilCombatActionEffects as weaponSongOfTheVigilEffects } from "../weapons/song-of-the-vigil/effects.js"
import { splendorOfTranquilWatersCombatActionEffects as weaponSplendorOfTranquilWatersEffects } from "../weapons/splendor-of-tranquil-waters/effects.js"
import { staffOfHomaCombatActionEffects as weaponStaffOfHomaEffects } from "../weapons/staff-of-homa/effects.js"
import { staffOfTheScarletSandsCombatActionEffects as weaponStaffOfTheScarletSandsEffects } from "../weapons/staff-of-the-scarlet-sands/effects.js"
import { starcallersWatchCombatActionEffects as weaponStarcallersWatchEffects } from "../weapons/starcallers-watch/effects.js"
import { sturdyBoneCombatActionEffects as weaponSturdyBoneEffects } from "../weapons/sturdy-bone/effects.js"
import { summitShaperCombatActionEffects as weaponSummitShaperEffects } from "../weapons/summit-shaper/effects.js"
import { sunnyMorningSleepInCombatActionEffects as weaponSunnyMorningSleepInEffects } from "../weapons/sunny-morning-sleep-in/effects.js"
import { surfsUpCombatActionEffects as weaponSurfsUpEffects } from "../weapons/surfs-up/effects.js"
import { swordOfDescensionCombatActionEffects as weaponSwordOfDescensionEffects } from "../weapons/sword-of-descension/effects.js"
import { swordOfNarzissenkreuzCombatActionEffects as weaponSwordOfNarzissenkreuzEffects } from "../weapons/sword-of-narzissenkreuz/effects.js"
import { symphonistOfScentsCombatActionEffects as weaponSymphonistOfScentsEffects } from "../weapons/symphonist-of-scents/effects.js"
import { talkingStickCombatActionEffects as weaponTalkingStickEffects } from "../weapons/talking-stick/effects.js"
import { tamayurateiNoOhanashiCombatActionEffects as weaponTamayurateiNoOhanashiEffects } from "../weapons/tamayuratei-no-ohanashi/effects.js"
import { theAlleyFlashCombatActionEffects as weaponTheAlleyFlashEffects } from "../weapons/the-alley-flash/effects.js"
import { theBellCombatActionEffects as weaponTheBellEffects } from "../weapons/the-bell/effects.js"
import { theBlackSwordCombatActionEffects as weaponTheBlackSwordEffects } from "../weapons/the-black-sword/effects.js"
import { theCatchCombatActionEffects as weaponTheCatchEffects } from "../weapons/the-catch/effects.js"
import { theDaybreakChroniclesCombatActionEffects as weaponTheDaybreakChroniclesEffects } from "../weapons/the-daybreak-chronicles/effects.js"
import { theDockhandsAssistantCombatActionEffects as weaponTheDockhandsAssistantEffects } from "../weapons/the-dockhands-assistant/effects.js"
import { theFirstGreatMagicCombatActionEffects as weaponTheFirstGreatMagicEffects } from "../weapons/the-first-great-magic/effects.js"
import { theFluteCombatActionEffects as weaponTheFluteEffects } from "../weapons/the-flute/effects.js"
import { theStringlessCombatActionEffects as weaponTheStringlessEffects } from "../weapons/the-stringless/effects.js"
import { theUnforgedCombatActionEffects as weaponTheUnforgedEffects } from "../weapons/the-unforged/effects.js"
import { theViridescentHuntCombatActionEffects as weaponTheViridescentHuntEffects } from "../weapons/the-viridescent-hunt/effects.js"
import { theWidsithCombatActionEffects as weaponTheWidsithEffects } from "../weapons/the-widsith/effects.js"
import { thrillingTalesOfDragonSlayersCombatActionEffects as weaponThrillingTalesOfDragonSlayersEffects } from "../weapons/thrilling-tales-of-dragon-slayers/effects.js"
import { thunderingPulseCombatActionEffects as weaponThunderingPulseEffects } from "../weapons/thundering-pulse/effects.js"
import { tidalShadowCombatActionEffects as weaponTidalShadowEffects } from "../weapons/tidal-shadow/effects.js"
import { tomeOfTheEternalFlowCombatActionEffects as weaponTomeOfTheEternalFlowEffects } from "../weapons/tome-of-the-eternal-flow/effects.js"
import { toukabouShigureCombatActionEffects as weaponToukabouShigureEffects } from "../weapons/toukabou-shigure/effects.js"
import { travelersHandySwordCombatActionEffects as weaponTravelersHandySwordEffects } from "../weapons/travelers-handy-sword/effects.js"
import { tulaytullahsRemembranceCombatActionEffects as weaponTulaytullahsRemembranceEffects } from "../weapons/tulaytullahs-remembrance/effects.js"
import { twinNephriteCombatActionEffects as weaponTwinNephriteEffects } from "../weapons/twin-nephrite/effects.js"
import { ultimateOverlordsMegaMagicSwordCombatActionEffects as weaponUltimateOverlordsMegaMagicSwordEffects } from "../weapons/ultimate-overlords-mega-magic-sword/effects.js"
import { urakuMisugiriCombatActionEffects as weaponUrakuMisugiriEffects } from "../weapons/uraku-misugiri/effects.js"
import { verdictCombatActionEffects as weaponVerdictEffects } from "../weapons/verdict/effects.js"
import { vividNotionsCombatActionEffects as weaponVividNotionsEffects } from "../weapons/vivid-notions/effects.js"
import { vortexVanquisherCombatActionEffects as weaponVortexVanquisherEffects } from "../weapons/vortex-vanquisher/effects.js"
import { wanderingEvenstarCombatActionEffects as weaponWanderingEvenstarEffects } from "../weapons/wandering-evenstar/effects.js"
import { wasterGreatswordCombatActionEffects as weaponWasterGreatswordEffects } from "../weapons/waster-greatsword/effects.js"
import { wavebreakersFinCombatActionEffects as weaponWavebreakersFinEffects } from "../weapons/wavebreakers-fin/effects.js"
import { waveridingWhirlCombatActionEffects as weaponWaveridingWhirlEffects } from "../weapons/waveriding-whirl/effects.js"
import { whiteIronGreatswordCombatActionEffects as weaponWhiteIronGreatswordEffects } from "../weapons/white-iron-greatsword/effects.js"
import { whiteTasselCombatActionEffects as weaponWhiteTasselEffects } from "../weapons/white-tassel/effects.js"
import { whiteblindCombatActionEffects as weaponWhiteblindEffects } from "../weapons/whiteblind/effects.js"
import { whitelakeFrostfeatherCombatActionEffects as weaponWhitelakeFrostfeatherEffects } from "../weapons/whitelake-frostfeather/effects.js"
import { windblumeOdeCombatActionEffects as weaponWindblumeOdeEffects } from "../weapons/windblume-ode/effects.js"
import { wineAndSongCombatActionEffects as weaponWineAndSongEffects } from "../weapons/wine-and-song/effects.js"
import { wolfFangCombatActionEffects as weaponWolfFangEffects } from "../weapons/wolf-fang/effects.js"
import { wolfsGravestoneCombatActionEffects as weaponWolfsGravestoneEffects } from "../weapons/wolfs-gravestone/effects.js"
import { xiphosMoonlightCombatActionEffects as weaponXiphosMoonlightEffects } from "../weapons/xiphos-moonlight/effects.js"

export const equipmentCombatActionEffects: readonly CombatActionEffect[] = [
  ...artifactADayCarvedFromRisingWindsEffects,
  ...artifactAdventurerEffects,
  ...artifactArchaicPetraEffects,
  ...artifactAubadeOfMorningstarAndMoonEffects,
  ...artifactBerserkerEffects,
  ...artifactBlizzardStrayerEffects,
  ...artifactBloodstainedChivalryEffects,
  ...artifactBraveHeartEffects,
  ...artifactCelestialGiftEffects,
  ...artifactCrimsonWitchOfFlamesEffects,
  ...artifactDeepwoodMemoriesEffects,
  ...artifactDefendersWillEffects,
  ...artifactDesertPavilionChronicleEffects,
  ...artifactDisenchantmentInDeepShadowEffects,
  ...artifactEchoesOfAnOfferingEffects,
  ...artifactEmblemOfSeveredFateEffects,
  ...artifactFinaleOfTheDeepGalleriesEffects,
  ...artifactFlowerOfParadiseLostEffects,
  ...artifactFragmentOfHarmonicWhimsyEffects,
  ...artifactGamblerEffects,
  ...artifactGildedDreamsEffects,
  ...artifactGladiatorsFinaleEffects,
  ...artifactGoldenTroupeEffects,
  ...artifactHeartOfDepthEffects,
  ...artifactHeartOfTheFurnaceEffects,
  ...artifactHuskOfOpulentDreamsEffects,
  ...artifactInstructorEffects,
  ...artifactLavawalkerEffects,
  ...artifactLongNightsOathEffects,
  ...artifactLuckyDogEffects,
  ...artifactMaidenBelovedEffects,
  ...artifactMarechausseeHunterEffects,
  ...artifactMartialArtistEffects,
  ...artifactNightOfTheSkysUnveilingEffects,
  ...artifactNighttimeWhispersInTheEchoingWoodsEffects,
  ...artifactNoblesseObligeEffects,
  ...artifactNymphsDreamEffects,
  ...artifactObsidianCodexEffects,
  ...artifactOceanHuedClamEffects,
  ...artifactPaleFlameEffects,
  ...artifactPrayersForDestinyEffects,
  ...artifactPrayersForIlluminationEffects,
  ...artifactPrayersForWisdomEffects,
  ...artifactPrayersToSpringtimeEffects,
  ...artifactResolutionOfSojournerEffects,
  ...artifactRetracingBolideEffects,
  ...artifactScarletProofEffects,
  ...artifactScholarEffects,
  ...artifactScrollOfTheHeroOfCinderCityEffects,
  ...artifactShimenawasReminiscenceEffects,
  ...artifactSilkenMoonsSerenadeEffects,
  ...artifactSongOfDaysPastEffects,
  ...artifactTenacityOfTheMillelithEffects,
  ...artifactTheExileEffects,
  ...artifactThunderingFuryEffects,
  ...artifactThundersootherEffects,
  ...artifactTinyMiracleEffects,
  ...artifactTravelingDoctorEffects,
  ...artifactUnfinishedReverieEffects,
  ...artifactVermillionHereafterEffects,
  ...artifactViridescentVenererEffects,
  ...artifactVourukashasGlowEffects,
  ...artifactWanderersTroupeEffects,
  ...weaponATeaspoonOfTranscendenceEffects,
  ...weaponAThousandBlazingSunsEffects,
  ...weaponAThousandFloatingDreamsEffects,
  ...weaponAbsolutionEffects,
  ...weaponAkuoumaruEffects,
  ...weaponAlleyHunterEffects,
  ...weaponAmenomaKageuchiEffects,
  ...weaponAmosBowEffects,
  ...weaponAngelosHeptadesEffects,
  ...weaponApprenticesNotesEffects,
  ...weaponAquaSimulacraEffects,
  ...weaponAquilaFavoniaEffects,
  ...weaponAshGravenDrinkingHornEffects,
  ...weaponAstralVulturesCrimsonPlumageEffects,
  ...weaponAthameArtisEffects,
  ...weaponAzurelightEffects,
  ...weaponBalladOfTheBoundlessBlueEffects,
  ...weaponBalladOfTheFjordsEffects,
  ...weaponBeaconOfTheReedSeaEffects,
  ...weaponBeginnersProtectorEffects,
  ...weaponBlackTasselEffects,
  ...weaponBlackcliffAgateEffects,
  ...weaponBlackcliffLongswordEffects,
  ...weaponBlackcliffPoleEffects,
  ...weaponBlackcliffSlasherEffects,
  ...weaponBlackcliffWarbowEffects,
  ...weaponBlackmarrowLanternEffects,
  ...weaponBladeOfAtonementEffects,
  ...weaponBloodsoakedRuinsEffects,
  ...weaponBloodtaintedGreatswordEffects,
  ...weaponCalamityOfEshuEffects,
  ...weaponCalamityQuellerEffects,
  ...weaponCashflowSupervisionEffects,
  ...weaponChainBreakerEffects,
  ...weaponCinnabarSpindleEffects,
  ...weaponClashOfKingsEffects,
  ...weaponCloudforgedEffects,
  ...weaponCompoundBowEffects,
  ...weaponCoolSteelEffects,
  ...weaponCovenantOfFrostAndSnowEffects,
  ...weaponCranesEchoingCallEffects,
  ...weaponCrescentPikeEffects,
  ...weaponCrimsonMoonsSemblanceEffects,
  ...weaponDarkIronSwordEffects,
  ...weaponDawningFrostEffects,
  ...weaponDeathmatchEffects,
  ...weaponDebateClubEffects,
  ...weaponDialoguesOfTheDesertSagesEffects,
  ...weaponDisasterAndRemorseEffects,
  ...weaponDodocoTalesEffects,
  ...weaponDragonsBaneEffects,
  ...weaponDragonspineSpearEffects,
  ...weaponDullBladeEffects,
  ...weaponEarthShakerEffects,
  ...weaponEchoesOfTheHeartEffects,
  ...weaponElegyForTheEndEffects,
  ...weaponEmberwellEffects,
  ...weaponEmeraldOrbEffects,
  ...weaponEndOfTheLineEffects,
  ...weaponEngulfingLightningEffects,
  ...weaponEtherlightSpindleluteEffects,
  ...weaponEverlastingMoonglowEffects,
  ...weaponExaiphanesBladeEffects,
  ...weaponEyeOfPerceptionEffects,
  ...weaponFadingTwilightEffects,
  ...weaponFangOfTheMountainKingEffects,
  ...weaponFavoniusCodexEffects,
  ...weaponFavoniusGreatswordEffects,
  ...weaponFavoniusLanceEffects,
  ...weaponFavoniusSwordEffects,
  ...weaponFavoniusWarbowEffects,
  ...weaponFerrousShadowEffects,
  ...weaponFesteringDesireEffects,
  ...weaponFilletBladeEffects,
  ...weaponFinaleOfTheDeepEffects,
  ...weaponFlameForgedInsightEffects,
  ...weaponFleuveCendreFerrymanEffects,
  ...weaponFlowerWreathedFeathersEffects,
  ...weaponFlowingPurityEffects,
  ...weaponFluteOfEzpitzalEffects,
  ...weaponFootprintOfTheRainbowEffects,
  ...weaponForestRegaliaEffects,
  ...weaponForgedByTheGoldenMelodyEffects,
  ...weaponFracturedHaloEffects,
  ...weaponFreedomSwornEffects,
  ...weaponFrostbearerEffects,
  ...weaponFrostbreathEffects,
  ...weaponFruitOfFulfillmentEffects,
  ...weaponFruitfulHookEffects,
  ...weaponGestOfTheMightyWolfEffects,
  ...weaponGoldenFrostboundOathEffects,
  ...weaponHakushinRingEffects,
  ...weaponHalberdEffects,
  ...weaponHamayumiEffects,
  ...weaponHaranGeppakuFutsuEffects,
  ...weaponHarbingerOfDawnEffects,
  ...weaponHereticsMoltenBladeEffects,
  ...weaponHuntersBowEffects,
  ...weaponHuntersPathEffects,
  ...weaponIbisPiercerEffects,
  ...weaponIronPointEffects,
  ...weaponIronStingEffects,
  ...weaponJadeVistaEffects,
  ...weaponJadefallsSplendorEffects,
  ...weaponKagotsurubeIsshinEffects,
  ...weaponKagurasVerityEffects,
  ...weaponKatsuragikiriNagamasaEffects,
  ...weaponKeyOfKhajNisutEffects,
  ...weaponKingsSquireEffects,
  ...weaponKitainCrossSpearEffects,
  ...weaponLightOfFoliarIncisionEffects,
  ...weaponLightbearingMoonshardEffects,
  ...weaponLionsRoarEffects,
  ...weaponLithicBladeEffects,
  ...weaponLithicSpearEffects,
  ...weaponLostPrayerToTheSacredWindsEffects,
  ...weaponLumidouceElegyEffects,
  ...weaponLuxuriousSeaLordEffects,
  ...weaponMagicGuideEffects,
  ...weaponMailedFlowerEffects,
  ...weaponMakhairaAquamarineEffects,
  ...weaponMappaMareEffects,
  ...weaponMasterKeyEffects,
  ...weaponMemoryOfDustEffects,
  ...weaponMessengerEffects,
  ...weaponMissiveWindspearEffects,
  ...weaponMistsplitterReforgedEffects,
  ...weaponMitternachtsWaltzEffects,
  ...weaponMoonpiercerEffects,
  ...weaponMoonweaversDawnEffects,
  ...weaponMountainBracingBoltEffects,
  ...weaponMouunsMoonEffects,
  ...weaponNightweaversLookingGlassEffects,
  ...weaponNocturnesCurtainCallEffects,
  ...weaponOathswornEyeEffects,
  ...weaponOldMercsPalEffects,
  ...weaponOtherworldlyStoryEffects,
  ...weaponPeakPatrolSongEffects,
  ...weaponPocketGrimoireEffects,
  ...weaponPolarStarEffects,
  ...weaponPortablePowerSawEffects,
  ...weaponPredatorEffects,
  ...weaponPrimordialJadeCutterEffects,
  ...weaponPrimordialJadeWingedSpearEffects,
  ...weaponProspectorsDrillEffects,
  ...weaponProspectorsShovelEffects,
  ...weaponPrototypeAmberEffects,
  ...weaponPrototypeArchaicEffects,
  ...weaponPrototypeCrescentEffects,
  ...weaponPrototypeRancourEffects,
  ...weaponPrototypeStarglitterEffects,
  ...weaponRainbowSerpentsRainBowEffects,
  ...weaponRainslasherEffects,
  ...weaponRangeGaugeEffects,
  ...weaponRavenBowEffects,
  ...weaponRecurveBowEffects,
  ...weaponRedhornStonethresherEffects,
  ...weaponReliquaryOfTruthEffects,
  ...weaponRightfulRewardEffects,
  ...weaponRingOfYaxcheEffects,
  ...weaponRoyalBowEffects,
  ...weaponRoyalGreatswordEffects,
  ...weaponRoyalGrimoireEffects,
  ...weaponRoyalLongswordEffects,
  ...weaponRoyalSpearEffects,
  ...weaponRustEffects,
  ...weaponSacrificersStaffEffects,
  ...weaponSacrificialBowEffects,
  ...weaponSacrificialFragmentsEffects,
  ...weaponSacrificialGreatswordEffects,
  ...weaponSacrificialJadeEffects,
  ...weaponSacrificialSwordEffects,
  ...weaponSapwoodBladeEffects,
  ...weaponScionOfTheBlazingSunEffects,
  ...weaponSeasonedHuntersBowEffects,
  ...weaponSequenceOfSolitudeEffects,
  ...weaponSerenitysCallEffects,
  ...weaponSerpentSpineEffects,
  ...weaponSharpshootersOathEffects,
  ...weaponSilverSwordEffects,
  ...weaponSilvershowerHeartstringsEffects,
  ...weaponSkyriderGreatswordEffects,
  ...weaponSkyriderSwordEffects,
  ...weaponSkywardAtlasEffects,
  ...weaponSkywardBladeEffects,
  ...weaponSkywardHarpEffects,
  ...weaponSkywardPrideEffects,
  ...weaponSkywardSpineEffects,
  ...weaponSlingshotEffects,
  ...weaponSnareHookEffects,
  ...weaponSnowTombedStarsilverEffects,
  ...weaponSolarPearlEffects,
  ...weaponSongOfBrokenPinesEffects,
  ...weaponSongOfStillnessEffects,
  ...weaponSongOfTheVigilEffects,
  ...weaponSplendorOfTranquilWatersEffects,
  ...weaponStaffOfHomaEffects,
  ...weaponStaffOfTheScarletSandsEffects,
  ...weaponStarcallersWatchEffects,
  ...weaponSturdyBoneEffects,
  ...weaponSummitShaperEffects,
  ...weaponSunnyMorningSleepInEffects,
  ...weaponSurfsUpEffects,
  ...weaponSwordOfDescensionEffects,
  ...weaponSwordOfNarzissenkreuzEffects,
  ...weaponSymphonistOfScentsEffects,
  ...weaponTalkingStickEffects,
  ...weaponTamayurateiNoOhanashiEffects,
  ...weaponTheAlleyFlashEffects,
  ...weaponTheBellEffects,
  ...weaponTheBlackSwordEffects,
  ...weaponTheCatchEffects,
  ...weaponTheDaybreakChroniclesEffects,
  ...weaponTheDockhandsAssistantEffects,
  ...weaponTheFirstGreatMagicEffects,
  ...weaponTheFluteEffects,
  ...weaponTheStringlessEffects,
  ...weaponTheUnforgedEffects,
  ...weaponTheViridescentHuntEffects,
  ...weaponTheWidsithEffects,
  ...weaponThrillingTalesOfDragonSlayersEffects,
  ...weaponThunderingPulseEffects,
  ...weaponTidalShadowEffects,
  ...weaponTomeOfTheEternalFlowEffects,
  ...weaponToukabouShigureEffects,
  ...weaponTravelersHandySwordEffects,
  ...weaponTulaytullahsRemembranceEffects,
  ...weaponTwinNephriteEffects,
  ...weaponUltimateOverlordsMegaMagicSwordEffects,
  ...weaponUrakuMisugiriEffects,
  ...weaponVerdictEffects,
  ...weaponVividNotionsEffects,
  ...weaponVortexVanquisherEffects,
  ...weaponWanderingEvenstarEffects,
  ...weaponWasterGreatswordEffects,
  ...weaponWavebreakersFinEffects,
  ...weaponWaveridingWhirlEffects,
  ...weaponWhiteIronGreatswordEffects,
  ...weaponWhiteTasselEffects,
  ...weaponWhiteblindEffects,
  ...weaponWhitelakeFrostfeatherEffects,
  ...weaponWindblumeOdeEffects,
  ...weaponWineAndSongEffects,
  ...weaponWolfFangEffects,
  ...weaponWolfsGravestoneEffects,
  ...weaponXiphosMoonlightEffects
]
