// Generated by tools/generate-registries.ts; do not edit by hand.
import type { HealingEquipmentEffect } from "../rules/equipment/healing/types.js"

import { maidenBelovedHealingEquipmentEffects } from "../artifacts/maiden-beloved/support-effects.js"
import { oceanHuedClamHealingEquipmentEffects } from "../artifacts/ocean-hued-clam/support-effects.js"
import { songOfDaysPastHealingEquipmentEffects } from "../artifacts/song-of-days-past/support-effects.js"
import { everlastingMoonglowHealingEquipmentEffects } from "../weapons/everlasting-moonglow/support-effects.js"

export const healingEquipmentEffects: readonly HealingEquipmentEffect[] = [
  ...maidenBelovedHealingEquipmentEffects,
  ...oceanHuedClamHealingEquipmentEffects,
  ...songOfDaysPastHealingEquipmentEffects,
  ...everlastingMoonglowHealingEquipmentEffects
]
