// Generated by tools/generate-registries.ts; do not edit by hand.
import type { RecipientEquipmentEffect } from "../rules/equipment/recipient/types.js"

import { maidenBelovedRecipientEquipmentEffects } from "../artifacts/maiden-beloved/support-effects.js"
import { retracingBolideRecipientEquipmentEffects } from "../artifacts/retracing-bolide/support-effects.js"
import { tenacityOfTheMillelithRecipientEquipmentEffects } from "../artifacts/tenacity-of-the-millelith/support-effects.js"
import { travelingDoctorRecipientEquipmentEffects } from "../artifacts/traveling-doctor/support-effects.js"
import { memoryOfDustRecipientEquipmentEffects } from "../weapons/memory-of-dust/support-effects.js"
import { summitShaperRecipientEquipmentEffects } from "../weapons/summit-shaper/support-effects.js"
import { theUnforgedRecipientEquipmentEffects } from "../weapons/the-unforged/support-effects.js"
import { vortexVanquisherRecipientEquipmentEffects } from "../weapons/vortex-vanquisher/support-effects.js"

export const recipientEquipmentEffects: readonly RecipientEquipmentEffect[] = [
  ...maidenBelovedRecipientEquipmentEffects,
  ...retracingBolideRecipientEquipmentEffects,
  ...tenacityOfTheMillelithRecipientEquipmentEffects,
  ...travelingDoctorRecipientEquipmentEffects,
  ...memoryOfDustRecipientEquipmentEffects,
  ...summitShaperRecipientEquipmentEffects,
  ...theUnforgedRecipientEquipmentEffects,
  ...vortexVanquisherRecipientEquipmentEffects
]
