// Generated by tools/generate-registries.ts; do not edit by hand.
import type { ReviewedMultiScalingEvidenceRecord } from "../characters/evidence.js"

import { reviewedMultiScalingEvidence as characterAinoEvidence } from "../characters/aino/evidence.js"
import { reviewedMultiScalingEvidence as characterAlhaithamEvidence } from "../characters/alhaitham/evidence.js"
import { reviewedMultiScalingEvidence as characterAratakiIttoEvidence } from "../characters/arataki-itto/evidence.js"
import { reviewedMultiScalingEvidence as characterArlecchinoEvidence } from "../characters/arlecchino/evidence.js"
import { reviewedMultiScalingEvidence as characterBeidouEvidence } from "../characters/beidou/evidence.js"
import { reviewedMultiScalingEvidence as characterChioriEvidence } from "../characters/chiori/evidence.js"
import { reviewedMultiScalingEvidence as characterCynoEvidence } from "../characters/cyno/evidence.js"
import { reviewedMultiScalingEvidence as characterDehyaEvidence } from "../characters/dehya/evidence.js"
import { reviewedMultiScalingEvidence as characterEulaEvidence } from "../characters/eula/evidence.js"
import { reviewedMultiScalingEvidence as characterIllugaEvidence } from "../characters/illuga/evidence.js"
import { reviewedMultiScalingEvidence as characterKachinaEvidence } from "../characters/kachina/evidence.js"
import { reviewedMultiScalingEvidence as characterKamisatoAyatoEvidence } from "../characters/kamisato-ayato/evidence.js"
import { reviewedMultiScalingEvidence as characterMavuikaEvidence } from "../characters/mavuika/evidence.js"
import { reviewedMultiScalingEvidence as characterNahidaEvidence } from "../characters/nahida/evidence.js"
import { reviewedMultiScalingEvidence as characterNeferEvidence } from "../characters/nefer/evidence.js"
import { reviewedMultiScalingEvidence as characterNoelleEvidence } from "../characters/noelle/evidence.js"
import { reviewedMultiScalingEvidence as characterRaidenEvidence } from "../characters/raiden/evidence.js"
import { reviewedMultiScalingEvidence as characterRazorEvidence } from "../characters/razor/evidence.js"
import { reviewedMultiScalingEvidence as characterSethosEvidence } from "../characters/sethos/evidence.js"
import { reviewedMultiScalingEvidence as characterShikanoinHeizouEvidence } from "../characters/shikanoin-heizou/evidence.js"
import { reviewedMultiScalingEvidence as characterVaresaEvidence } from "../characters/varesa/evidence.js"
import { reviewedMultiScalingEvidence as characterWandererEvidence } from "../characters/wanderer/evidence.js"
import { reviewedMultiScalingEvidence as characterYoimiyaEvidence } from "../characters/yoimiya/evidence.js"
import { reviewedMultiScalingEvidence as characterZhongliEvidence } from "../characters/zhongli/evidence.js"

export const reviewedMultiScalingEvidenceRecords: readonly ReviewedMultiScalingEvidenceRecord[] = [
  ...characterAinoEvidence,
  ...characterAlhaithamEvidence,
  ...characterAratakiIttoEvidence,
  ...characterArlecchinoEvidence,
  ...characterBeidouEvidence,
  ...characterChioriEvidence,
  ...characterCynoEvidence,
  ...characterDehyaEvidence,
  ...characterEulaEvidence,
  ...characterIllugaEvidence,
  ...characterKachinaEvidence,
  ...characterKamisatoAyatoEvidence,
  ...characterMavuikaEvidence,
  ...characterNahidaEvidence,
  ...characterNeferEvidence,
  ...characterNoelleEvidence,
  ...characterRaidenEvidence,
  ...characterRazorEvidence,
  ...characterSethosEvidence,
  ...characterShikanoinHeizouEvidence,
  ...characterVaresaEvidence,
  ...characterWandererEvidence,
  ...characterYoimiyaEvidence,
  ...characterZhongliEvidence
]
