/**
 * Browser-safe Chinese presentation metadata for the 6.7 supported-character catalog.
 *
 * This artifact intentionally contains no game-data repository access. Combat coverage
 * decides which actions are selectable; this file only gives those canonical character
 * IDs a stable display name and weapon type for API and browser consumers.
 * Official Simplified Chinese character names are pinned and regression-checked in
 * character-name-audit.ts; this browser-safe artifact does not reach into game-data at runtime.
 */
export const characterCatalogPresentationVersion = "6.7.1"

export type CatalogWeaponType = "bow" | "catalyst" | "claymore" | "polearm" | "sword"

export interface CharacterCatalogPresentation {
  readonly characterId: string
  readonly label: string
  readonly weaponType: CatalogWeaponType
}

export const characterCatalogPresentation: readonly CharacterCatalogPresentation[] = [
  { characterId: "RaidenShogun", label: "雷电将军", weaponType: "polearm" },
  { characterId: "Traveler", label: "旅行者", weaponType: "sword" },
  { characterId: "Bennett", label: "班尼特", weaponType: "sword" },
  { characterId: "Yelan", label: "夜兰", weaponType: "bow" },
  { characterId: "Albedo", label: "阿贝多", weaponType: "sword" },
  { characterId: "Dehya", label: "迪希雅", weaponType: "claymore" },
  { characterId: "Collei", label: "柯莱", weaponType: "bow" },
  { characterId: "Xiangling", label: "香菱", weaponType: "polearm" },
  { characterId: "Xingqiu", label: "行秋", weaponType: "sword" },
  { characterId: "Kaeya", label: "凯亚", weaponType: "sword" },
  { characterId: "Lisa", label: "丽莎", weaponType: "catalyst" },
  { characterId: "Sucrose", label: "砂糖", weaponType: "catalyst" },
  { characterId: "Noelle", label: "诺艾尔", weaponType: "claymore" },
  { characterId: "Chongyun", label: "重云", weaponType: "claymore" },
  { characterId: "Razor", label: "雷泽", weaponType: "claymore" },
  { characterId: "Yanfei", label: "烟绯", weaponType: "catalyst" },
  { characterId: "KujouSara", label: "九条裟罗", weaponType: "bow" },
  { characterId: "Gorou", label: "五郎", weaponType: "bow" },
  { characterId: "Kaveh", label: "卡维", weaponType: "claymore" },
  { characterId: "Gaming", label: "嘉明", weaponType: "claymore" },
  { characterId: "Chevreuse", label: "夏沃蕾", weaponType: "polearm" },
  { characterId: "Ororon", label: "欧洛伦", weaponType: "bow" },
  { characterId: "LanYan", label: "蓝砚", weaponType: "catalyst" },
  { characterId: "Kachina", label: "卡齐娜", weaponType: "polearm" },
  { characterId: "Dahlia", label: "塔利雅", weaponType: "sword" },
  { characterId: "Jean", label: "琴", weaponType: "sword" },
  { characterId: "Xiao", label: "魈", weaponType: "polearm" },
  { characterId: "Aloy", label: "埃洛伊", weaponType: "bow" },
  { characterId: "KamisatoAyaka", label: "神里绫华", weaponType: "sword" },
  { characterId: "Escoffier", label: "爱可菲", weaponType: "polearm" },
  { characterId: "Qiqi", label: "七七", weaponType: "sword" },
  { characterId: "Tighnari", label: "提纳里", weaponType: "bow" },
  { characterId: "YunJin", label: "云堇", weaponType: "polearm" },
  { characterId: "Zhongli", label: "钟离", weaponType: "polearm" },
  { characterId: "Neuvillette", label: "那维莱特", weaponType: "catalyst" },
  { characterId: "Nilou", label: "妮露", weaponType: "sword" },
  { characterId: "Diluc", label: "迪卢克", weaponType: "claymore" },
  { characterId: "Thoma", label: "托马", weaponType: "polearm" },
  { characterId: "Arlecchino", label: "阿蕾奇诺", weaponType: "polearm" },
  { characterId: "Cyno", label: "赛诺", weaponType: "polearm" },
  { characterId: "Beidou", label: "北斗", weaponType: "claymore" },
  { characterId: "Candace", label: "坎蒂丝", weaponType: "polearm" },
  { characterId: "Diona", label: "迪奥娜", weaponType: "bow" },
  { characterId: "Eula", label: "优菈", weaponType: "claymore" },
  { characterId: "Faruzan", label: "珐露珊", weaponType: "bow" },
  { characterId: "Ganyu", label: "甘雨", weaponType: "bow" },
  { characterId: "KaedeharaKazuha", label: "枫原万叶", weaponType: "sword" },
  { characterId: "Keqing", label: "刻晴", weaponType: "sword" },
  { characterId: "Kirara", label: "绮良良", weaponType: "sword" },
  { characterId: "KukiShinobu", label: "久岐忍", weaponType: "sword" },
  { characterId: "Layla", label: "莱依拉", weaponType: "sword" },
  { characterId: "Mika", label: "米卡", weaponType: "polearm" },
  { characterId: "Ningguang", label: "凝光", weaponType: "catalyst" },
  { characterId: "Sethos", label: "赛索斯", weaponType: "bow" },
  { characterId: "Shenhe", label: "申鹤", weaponType: "polearm" },
  { characterId: "Venti", label: "温迪", weaponType: "bow" },
  { characterId: "Xinyan", label: "辛焱", weaponType: "claymore" },
  { characterId: "Amber", label: "安柏", weaponType: "bow" },
  { characterId: "Barbara", label: "芭芭拉", weaponType: "catalyst" },
  { characterId: "Charlotte", label: "夏洛蒂", weaponType: "catalyst" },
  { characterId: "Dori", label: "多莉", weaponType: "claymore" },
  { characterId: "Fischl", label: "菲谢尔", weaponType: "bow" },
  { characterId: "Klee", label: "可莉", weaponType: "catalyst" },
  { characterId: "Lynette", label: "琳妮特", weaponType: "sword" },
  { characterId: "Nahida", label: "纳西妲", weaponType: "catalyst" },
  { characterId: "Navia", label: "娜维娅", weaponType: "claymore" },
  { characterId: "Rosaria", label: "罗莎莉亚", weaponType: "polearm" },
  { characterId: "Sayu", label: "早柚", weaponType: "claymore" },
  { characterId: "ShikanoinHeizou", label: "鹿野院平藏", weaponType: "catalyst" },
  { characterId: "Tartaglia", label: "达达利亚", weaponType: "bow" },
  { characterId: "Xianyun", label: "闲云", weaponType: "catalyst" },
  { characterId: "YaeMiko", label: "八重神子", weaponType: "catalyst" },
  { characterId: "Yaoyao", label: "瑶瑶", weaponType: "polearm" },
  { characterId: "Chasca", label: "恰斯卡", weaponType: "bow" },
  { characterId: "Ifa", label: "伊法", weaponType: "catalyst" },
  { characterId: "Citlali", label: "茜特菈莉", weaponType: "catalyst" },
  { characterId: "Freminet", label: "菲米尼", weaponType: "claymore" },
  { characterId: "Alhaitham", label: "艾尔海森", weaponType: "sword" },
  { characterId: "Baizhu", label: "白术", weaponType: "catalyst" },
  { characterId: "Clorinde", label: "克洛琳德", weaponType: "sword" },
  { characterId: "Iansan", label: "伊安珊", weaponType: "polearm" },
  { characterId: "AratakiItto", label: "荒泷一斗", weaponType: "claymore" },
  { characterId: "Chiori", label: "千织", weaponType: "sword" },
  { characterId: "Aino", label: "爱诺", weaponType: "claymore" },
  { characterId: "Mona", label: "莫娜", weaponType: "catalyst" },
  { characterId: "HuTao", label: "胡桃", weaponType: "polearm" },
  { characterId: "Lyney", label: "林尼", weaponType: "bow" },
  { characterId: "Furina", label: "芙宁娜", weaponType: "sword" },
  { characterId: "KamisatoAyato", label: "神里绫人", weaponType: "sword" },
  { characterId: "Jahoda", label: "雅珂达", weaponType: "bow" },
  { characterId: "Prune", label: "布伦妮", weaponType: "catalyst" },
  { characterId: "Varka", label: "法尔伽", weaponType: "claymore" },
  { characterId: "Lohen", label: "洛恩", weaponType: "polearm" },
  { characterId: "Wriothesley", label: "莱欧斯利", weaponType: "catalyst" },
  { characterId: "Emilie", label: "艾梅莉埃", weaponType: "polearm" },
  { characterId: "Lauma", label: "菈乌玛", weaponType: "catalyst" },
  { characterId: "Flins", label: "菲林斯", weaponType: "polearm" },
  { characterId: "Linnea", label: "莉奈娅", weaponType: "bow" },
  { characterId: "Xilonen", label: "希诺宁", weaponType: "sword" },
  { characterId: "Sigewinne", label: "希格雯", weaponType: "bow" },
  { characterId: "Columbina", label: "哥伦比娅", weaponType: "catalyst" },
  { characterId: "Yoimiya", label: "宵宫", weaponType: "bow" },
  { characterId: "Nicole", label: "尼可", weaponType: "catalyst" },
  { characterId: "Mavuika", label: "玛薇卡", weaponType: "claymore" },
  { characterId: "Wanderer", label: "流浪者", weaponType: "catalyst" },
  { characterId: "YumemizukiMizuki", label: "梦见月瑞希", weaponType: "catalyst" },
  { characterId: "Sandrone", label: "桑多涅", weaponType: "claymore" },
  { characterId: "Skirk", label: "丝柯克", weaponType: "sword" },
  { characterId: "Kinich", label: "基尼奇", weaponType: "claymore" },
  { characterId: "Nefer", label: "奈芙尔", weaponType: "catalyst" },
  { characterId: "Ineffa", label: "伊涅芙", weaponType: "polearm" },
  { characterId: "Varesa", label: "瓦雷莎", weaponType: "catalyst" },
  { characterId: "Illuga", label: "叶洛亚", weaponType: "polearm" },
  { characterId: "Zibai", label: "兹白", weaponType: "sword" },
  { characterId: "Mualani", label: "玛拉妮", weaponType: "catalyst" },
  { characterId: "SangonomiyaKokomi", label: "珊瑚宫心海", weaponType: "catalyst" },
  { characterId: "Durin", label: "杜林", weaponType: "sword" }
]
