// Generated by tools/generate-equipment-inventory.ts; do not edit by hand.
export const equipmentInventorySource = {
  "artifactNameAggregatePath": "libs/gi/dm-localization/assets/locales/chs/artifactNames_gen.json",
  "artifactNameAggregateSha256": "42ce43e34e763488690aceadb7c5b391edc9fadf786ba0d426cca6bd9ec169ac",
  "excludedNonGenshinWeaponIds": [
    "QuantumCatalyst"
  ],
  "gameVersion": "6.7",
  "upstreamCommit": "21c98eb60355160274a8c4cecfc5671e2151a073",
  "upstreamRepository": "https://github.com/frzyc/genshin-optimizer",
  "weaponNameAggregatePath": "libs/gi/dm-localization/assets/locales/chs/weaponNames_gen.json",
  "weaponNameAggregateSha256": "c14a4ae836f8405ca615e690009b0efa70b36e7b543ce92a1c1d285809f31640"
} as const

export const weaponInventoryGenerated = [
  {
    "id": "ATeaspoonOfTranscendence",
    "label": "超越之匙",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "AThousandBlazingSuns",
    "label": "焚曜千阳",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "AThousandFloatingDreams",
    "label": "千夜浮梦",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "Absolution",
    "label": "赦罪",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "Akuoumaru",
    "label": "恶王丸",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "AlleyHunter",
    "label": "暗巷猎手",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "AmenomaKageuchi",
    "label": "天目影打刀",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "AmosBow",
    "label": "阿莫斯之弓",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "AngelosHeptades",
    "label": "尘光七谕",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "ApprenticesNotes",
    "label": "学徒笔记",
    "rarity": 1,
    "weaponType": "catalyst"
  },
  {
    "id": "AquaSimulacra",
    "label": "若水",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "AquilaFavonia",
    "label": "风鹰剑",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "AshGravenDrinkingHorn",
    "label": "苍纹角杯",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "AstralVulturesCrimsonPlumage",
    "label": "星鹫赤羽",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "AthameArtis",
    "label": "黑蚀",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "Azurelight",
    "label": "苍耀",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "BalladOfTheBoundlessBlue",
    "label": "无垠蔚蓝之歌",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "BalladOfTheFjords",
    "label": "峡湾长歌",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "BeaconOfTheReedSea",
    "label": "苇海信标",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "BeginnersProtector",
    "label": "新手长枪",
    "rarity": 1,
    "weaponType": "polearm"
  },
  {
    "id": "BlackTassel",
    "label": "黑缨枪",
    "rarity": 3,
    "weaponType": "polearm"
  },
  {
    "id": "BlackcliffAgate",
    "label": "黑岩绯玉",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "BlackcliffLongsword",
    "label": "黑岩长剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "BlackcliffPole",
    "label": "黑岩刺枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "BlackcliffSlasher",
    "label": "黑岩斩刀",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "BlackcliffWarbow",
    "label": "黑岩战弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "BlackmarrowLantern",
    "label": "乌髓孑灯",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "BloodsoakedRuins",
    "label": "血染荒城",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "BloodtaintedGreatsword",
    "label": "沐浴龙血的剑",
    "rarity": 3,
    "weaponType": "claymore"
  },
  {
    "id": "CalamityOfEshu",
    "label": "厄水之祸",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "CalamityQueller",
    "label": "息灾",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "CashflowSupervision",
    "label": "金流监督",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "ChainBreaker",
    "label": "碎链",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "CinnabarSpindle",
    "label": "辰砂之纺锤",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "Cloudforged",
    "label": "筑云",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "CompoundBow",
    "label": "钢轮弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "CoolSteel",
    "label": "冷刃",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "CranesEchoingCall",
    "label": "鹤鸣余音",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "CrescentPike",
    "label": "流月针",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "CrimsonMoonsSemblance",
    "label": "赤月之形",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "DarkIronSword",
    "label": "暗铁剑",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "DawningFrost",
    "label": "霜辰",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "Deathmatch",
    "label": "决斗之枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "DebateClub",
    "label": "以理服人",
    "rarity": 3,
    "weaponType": "claymore"
  },
  {
    "id": "DialoguesOfTheDesertSages",
    "label": "沙中伟贤的对答",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "DisasterAndRemorse",
    "label": "灾悔",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "DodocoTales",
    "label": "嘟嘟可故事集",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "DragonsBane",
    "label": "匣里灭辰",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "DragonspineSpear",
    "label": "龙脊长枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "DullBlade",
    "label": "无锋剑",
    "rarity": 1,
    "weaponType": "sword"
  },
  {
    "id": "EarthShaker",
    "label": "撼地者",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "ElegyForTheEnd",
    "label": "终末嗟叹之诗",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "EmeraldOrb",
    "label": "翡玉法球",
    "rarity": 3,
    "weaponType": "catalyst"
  },
  {
    "id": "EndOfTheLine",
    "label": "竭泽",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "EngulfingLightning",
    "label": "薙草之稻光",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "EtherlightSpindlelute",
    "label": "天光的纺琴",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "EverlastingMoonglow",
    "label": "不灭月华",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "EyeOfPerception",
    "label": "昭心",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "FadingTwilight",
    "label": "落霞",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "FangOfTheMountainKing",
    "label": "山王长牙",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "FavoniusCodex",
    "label": "西风秘典",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "FavoniusGreatsword",
    "label": "西风大剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "FavoniusLance",
    "label": "西风长枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "FavoniusSword",
    "label": "西风剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "FavoniusWarbow",
    "label": "西风猎弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "FerrousShadow",
    "label": "铁影阔剑",
    "rarity": 3,
    "weaponType": "claymore"
  },
  {
    "id": "FesteringDesire",
    "label": "腐殖之剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "FilletBlade",
    "label": "吃虎鱼刀",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "FinaleOfTheDeep",
    "label": "海渊终曲",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "FlameForgedInsight",
    "label": "拾慧铸熔",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "FleuveCendreFerryman",
    "label": "灰河渡手",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "FlowerWreathedFeathers",
    "label": "缀花之翎",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "FlowingPurity",
    "label": "纯水流华",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "FluteOfEzpitzal",
    "label": "息燧之笛",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "FootprintOfTheRainbow",
    "label": "虹的行迹",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "ForestRegalia",
    "label": "森林王器",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "FracturedHalo",
    "label": "支离轮光",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "FreedomSworn",
    "label": "苍古自由之誓",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "Frostbearer",
    "label": "忍冬之果",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "FruitOfFulfillment",
    "label": "盈满之实",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "FruitfulHook",
    "label": "硕果钩",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "GestOfTheMightyWolf",
    "label": "狼的武功歌",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "GoldenFrostboundOath",
    "label": "霜结的誓金枝",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "HakushinRing",
    "label": "白辰之环",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "Halberd",
    "label": "钺矛",
    "rarity": 3,
    "weaponType": "polearm"
  },
  {
    "id": "Hamayumi",
    "label": "破魔之弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "HaranGeppakuFutsu",
    "label": "波乱月白经津",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "HarbingerOfDawn",
    "label": "黎明神剑",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "HuntersBow",
    "label": "猎弓",
    "rarity": 1,
    "weaponType": "bow"
  },
  {
    "id": "HuntersPath",
    "label": "猎人之径",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "IbisPiercer",
    "label": "鹮穿之喙",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "IronPoint",
    "label": "铁尖枪",
    "rarity": 2,
    "weaponType": "polearm"
  },
  {
    "id": "IronSting",
    "label": "铁蜂刺",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "JadefallsSplendor",
    "label": "碧落之珑",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "KagotsurubeIsshin",
    "label": "笼钓瓶一心",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "KagurasVerity",
    "label": "神乐之真意",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "KatsuragikiriNagamasa",
    "label": "桂木斩长正",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "KeyOfKhajNisut",
    "label": "圣显之钥",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "KingsSquire",
    "label": "王下近侍",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "KitainCrossSpear",
    "label": "喜多院十文字",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "LightOfFoliarIncision",
    "label": "裁叶萃光",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "LightbearingMoonshard",
    "label": "朏魄含光",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "LionsRoar",
    "label": "匣里龙吟",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "LithicBlade",
    "label": "千岩古剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "LithicSpear",
    "label": "千岩长枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "LostPrayerToTheSacredWinds",
    "label": "四风原典",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "LumidouceElegy",
    "label": "柔灯挽歌",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "LuxuriousSeaLord",
    "label": "衔珠海皇",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "MagicGuide",
    "label": "魔导绪论",
    "rarity": 3,
    "weaponType": "catalyst"
  },
  {
    "id": "MailedFlower",
    "label": "饰铁之花",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "MakhairaAquamarine",
    "label": "玛海菈的水色",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "MappaMare",
    "label": "万国诸海图谱",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "MasterKey",
    "label": "万能钥匙",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "MemoryOfDust",
    "label": "尘世之锁",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "Messenger",
    "label": "信使",
    "rarity": 3,
    "weaponType": "bow"
  },
  {
    "id": "MissiveWindspear",
    "label": "风信之锋",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "MistsplitterReforged",
    "label": "雾切之回光",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "MitternachtsWaltz",
    "label": "幽夜华尔兹",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "Moonpiercer",
    "label": "贯月矢",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "MoonweaversDawn",
    "label": "织月者的曙色",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "MountainBracingBolt",
    "label": "镇山之钉",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "MouunsMoon",
    "label": "曚云之月",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "NightweaversLookingGlass",
    "label": "纺夜天镜",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "NocturnesCurtainCall",
    "label": "帷间夜曲",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "OathswornEye",
    "label": "证誓之明瞳",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "OldMercsPal",
    "label": "佣兵重剑",
    "rarity": 2,
    "weaponType": "claymore"
  },
  {
    "id": "OtherworldlyStory",
    "label": "异世界行记",
    "rarity": 3,
    "weaponType": "catalyst"
  },
  {
    "id": "PeakPatrolSong",
    "label": "岩峰巡歌",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "PocketGrimoire",
    "label": "口袋魔导书",
    "rarity": 2,
    "weaponType": "catalyst"
  },
  {
    "id": "PolarStar",
    "label": "冬极白星",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "PortablePowerSaw",
    "label": "便携动力锯",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "Predator",
    "label": "掠食者",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "PrimordialJadeCutter",
    "label": "磐岩结绿",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "PrimordialJadeWingedSpear",
    "label": "和璞鸢",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "ProspectorsDrill",
    "label": "勘探钻机",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "ProspectorsShovel",
    "label": "掘金之锹",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "PrototypeAmber",
    "label": "试作金珀",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "PrototypeArchaic",
    "label": "试作古华",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "PrototypeCrescent",
    "label": "试作澹月",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "PrototypeRancour",
    "label": "试作斩岩",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "PrototypeStarglitter",
    "label": "试作星镰",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "RainbowSerpentsRainBow",
    "label": "虹蛇的雨弦",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "Rainslasher",
    "label": "雨裁",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "RangeGauge",
    "label": "测距规",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "RavenBow",
    "label": "鸦羽弓",
    "rarity": 3,
    "weaponType": "bow"
  },
  {
    "id": "RecurveBow",
    "label": "反曲弓",
    "rarity": 3,
    "weaponType": "bow"
  },
  {
    "id": "RedhornStonethresher",
    "label": "赤角石溃杵",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "ReliquaryOfTruth",
    "label": "真语秘匣",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "RightfulReward",
    "label": "公义的酬报",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "RingOfYaxche",
    "label": "木棉之环",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "RoyalBow",
    "label": "宗室长弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "RoyalGreatsword",
    "label": "宗室大剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "RoyalGrimoire",
    "label": "宗室秘法录",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "RoyalLongsword",
    "label": "宗室长剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "RoyalSpear",
    "label": "宗室猎枪",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "Rust",
    "label": "弓藏",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SacrificersStaff",
    "label": "圣祭者的辉杖",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "SacrificialBow",
    "label": "祭礼弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SacrificialFragments",
    "label": "祭礼残章",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "SacrificialGreatsword",
    "label": "祭礼大剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "SacrificialJade",
    "label": "遗祀玉珑",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "SacrificialSword",
    "label": "祭礼剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "SapwoodBlade",
    "label": "原木刀",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "ScionOfTheBlazingSun",
    "label": "烈阳之嗣",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SeasonedHuntersBow",
    "label": "历练的猎弓",
    "rarity": 2,
    "weaponType": "bow"
  },
  {
    "id": "SequenceOfSolitude",
    "label": "冷寂迸音",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SerenitysCall",
    "label": "谧音吹哨",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "SerpentSpine",
    "label": "螭骨剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "SharpshootersOath",
    "label": "神射手之誓",
    "rarity": 3,
    "weaponType": "bow"
  },
  {
    "id": "SilverSword",
    "label": "银剑",
    "rarity": 2,
    "weaponType": "sword"
  },
  {
    "id": "SilvershowerHeartstrings",
    "label": "白雨心弦",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "SkyriderGreatsword",
    "label": "飞天大御剑",
    "rarity": 3,
    "weaponType": "claymore"
  },
  {
    "id": "SkyriderSword",
    "label": "飞天御剑",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "SkywardAtlas",
    "label": "天空之卷",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "SkywardBlade",
    "label": "天空之刃",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "SkywardHarp",
    "label": "天空之翼",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "SkywardPride",
    "label": "天空之傲",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "SkywardSpine",
    "label": "天空之脊",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "Slingshot",
    "label": "弹弓",
    "rarity": 3,
    "weaponType": "bow"
  },
  {
    "id": "SnareHook",
    "label": "罗网勾针",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SnowTombedStarsilver",
    "label": "雪葬的星银",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "SolarPearl",
    "label": "匣里日月",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "SongOfBrokenPines",
    "label": "松籁响起之时",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "SongOfStillness",
    "label": "静谧之曲",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "SplendorOfTranquilWaters",
    "label": "静水流涌之辉",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "StaffOfHoma",
    "label": "护摩之杖",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "StaffOfTheScarletSands",
    "label": "赤沙之杖",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "StarcallersWatch",
    "label": "祭星者之望",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "SturdyBone",
    "label": "弥坚骨",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "SummitShaper",
    "label": "斫峰之刃",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "SunnyMorningSleepIn",
    "label": "寝正月初晴",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "SurfsUp",
    "label": "冲浪时光",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "SwordOfDescension",
    "label": "降临之剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "SwordOfNarzissenkreuz",
    "label": "水仙十字之剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "SymphonistOfScents",
    "label": "香韵奏者",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "TalkingStick",
    "label": "聊聊棒",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "TamayurateiNoOhanashi",
    "label": "且住亭御咄",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "TheAlleyFlash",
    "label": "暗巷闪光",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "TheBell",
    "label": "钟剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "TheBlackSword",
    "label": "黑剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "TheCatch",
    "label": "「渔获」",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "TheDaybreakChronicles",
    "label": "黎明破晓之史",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "TheDockhandsAssistant",
    "label": "船坞长剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "TheFirstGreatMagic",
    "label": "最初的大魔术",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "TheFlute",
    "label": "笛剑",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "TheStringless",
    "label": "绝弦",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "TheUnforged",
    "label": "无工之剑",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "TheViridescentHunt",
    "label": "苍翠猎弓",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "TheWidsith",
    "label": "流浪乐章",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "ThrillingTalesOfDragonSlayers",
    "label": "讨龙英杰谭",
    "rarity": 3,
    "weaponType": "catalyst"
  },
  {
    "id": "ThunderingPulse",
    "label": "飞雷之弦振",
    "rarity": 5,
    "weaponType": "bow"
  },
  {
    "id": "TidalShadow",
    "label": "浪影阔剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "TomeOfTheEternalFlow",
    "label": "万世流涌大典",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "ToukabouShigure",
    "label": "东花坊时雨",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "TravelersHandySword",
    "label": "旅行剑",
    "rarity": 3,
    "weaponType": "sword"
  },
  {
    "id": "TulaytullahsRemembrance",
    "label": "图莱杜拉的回忆",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "TwinNephrite",
    "label": "甲级宝珏",
    "rarity": 3,
    "weaponType": "catalyst"
  },
  {
    "id": "UltimateOverlordsMegaMagicSword",
    "label": "「究极霸王超级魔剑」",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "UrakuMisugiri",
    "label": "有乐御簾切",
    "rarity": 5,
    "weaponType": "sword"
  },
  {
    "id": "Verdict",
    "label": "裁断",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "VividNotions",
    "label": "溢彩心念",
    "rarity": 5,
    "weaponType": "catalyst"
  },
  {
    "id": "VortexVanquisher",
    "label": "贯虹之槊",
    "rarity": 5,
    "weaponType": "polearm"
  },
  {
    "id": "WanderingEvenstar",
    "label": "流浪的晚星",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "WasterGreatsword",
    "label": "训练大剑",
    "rarity": 1,
    "weaponType": "claymore"
  },
  {
    "id": "WavebreakersFin",
    "label": "断浪长鳍",
    "rarity": 4,
    "weaponType": "polearm"
  },
  {
    "id": "WaveridingWhirl",
    "label": "乘浪的回旋",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "WhiteIronGreatsword",
    "label": "白铁大剑",
    "rarity": 3,
    "weaponType": "claymore"
  },
  {
    "id": "WhiteTassel",
    "label": "白缨枪",
    "rarity": 3,
    "weaponType": "polearm"
  },
  {
    "id": "Whiteblind",
    "label": "白影剑",
    "rarity": 4,
    "weaponType": "claymore"
  },
  {
    "id": "WindblumeOde",
    "label": "风花之颂",
    "rarity": 4,
    "weaponType": "bow"
  },
  {
    "id": "WineAndSong",
    "label": "暗巷的酒与诗",
    "rarity": 4,
    "weaponType": "catalyst"
  },
  {
    "id": "WolfFang",
    "label": "狼牙",
    "rarity": 4,
    "weaponType": "sword"
  },
  {
    "id": "WolfsGravestone",
    "label": "狼的末路",
    "rarity": 5,
    "weaponType": "claymore"
  },
  {
    "id": "XiphosMoonlight",
    "label": "西福斯的月光",
    "rarity": 4,
    "weaponType": "sword"
  }
] as const

export const artifactSetInventoryGenerated = [
  {
    "id": "ADayCarvedFromRisingWinds",
    "label": "风起之日",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Adventurer",
    "label": "冒险家",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ArchaicPetra",
    "label": "悠古的磐岩",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "AubadeOfMorningstarAndMoon",
    "label": "晨星与月的晓歌",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Berserker",
    "label": "战狂",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "BlizzardStrayer",
    "label": "冰风迷途的勇士",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "BloodstainedChivalry",
    "label": "染血的骑士道",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "BraveHeart",
    "label": "勇士之心",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "CelestialGift",
    "label": "天之美赐",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "CrimsonWitchOfFlames",
    "label": "炽烈的炎之魔女",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "DeepwoodMemories",
    "label": "深林的记忆",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "DefendersWill",
    "label": "守护之心",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "DesertPavilionChronicle",
    "label": "沙上楼阁史话",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "DisenchantmentInDeepShadow",
    "label": "影中沉凝的幻灭",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "EchoesOfAnOffering",
    "label": "来歆余响",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "EmblemOfSeveredFate",
    "label": "绝缘之旗印",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "FinaleOfTheDeepGalleries",
    "label": "深廊终曲",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "FlowerOfParadiseLost",
    "label": "乐园遗落之花",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "FragmentOfHarmonicWhimsy",
    "label": "谐律异想断章",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Gambler",
    "label": "赌徒",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "GildedDreams",
    "label": "饰金之梦",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "GladiatorsFinale",
    "label": "角斗士的终幕礼",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "GoldenTroupe",
    "label": "黄金剧团",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "HeartOfDepth",
    "label": "沉沦之心",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "HuskOfOpulentDreams",
    "label": "华馆梦醒形骸记",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Instructor",
    "label": "教官",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Lavawalker",
    "label": "渡过烈火的贤人",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "LongNightsOath",
    "label": "长夜之誓",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "LuckyDog",
    "label": "幸运儿",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "MaidenBeloved",
    "label": "被怜爱的少女",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "MarechausseeHunter",
    "label": "逐影猎人",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "MartialArtist",
    "label": "武人",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "NightOfTheSkysUnveiling",
    "label": "穹境示现之夜",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "NighttimeWhispersInTheEchoingWoods",
    "label": "回声之林夜话",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "NoblesseOblige",
    "label": "昔日宗室之仪",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "NymphsDream",
    "label": "水仙之梦",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ObsidianCodex",
    "label": "黑曜秘典",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "OceanHuedClam",
    "label": "海染砗磲",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "PaleFlame",
    "label": "苍白之火",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "PrayersForDestiny",
    "label": "祭水之人",
    "setBonuses": [
      1
    ]
  },
  {
    "id": "PrayersForIllumination",
    "label": "祭火之人",
    "setBonuses": [
      1
    ]
  },
  {
    "id": "PrayersForWisdom",
    "label": "祭雷之人",
    "setBonuses": [
      1
    ]
  },
  {
    "id": "PrayersToSpringtime",
    "label": "祭冰之人",
    "setBonuses": [
      1
    ]
  },
  {
    "id": "ResolutionOfSojourner",
    "label": "行者之心",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "RetracingBolide",
    "label": "逆飞的流星",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Scholar",
    "label": "学士",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ScrollOfTheHeroOfCinderCity",
    "label": "烬城勇者绘卷",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ShimenawasReminiscence",
    "label": "追忆之注连",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "SilkenMoonsSerenade",
    "label": "纺月的夜歌",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "SongOfDaysPast",
    "label": "昔时之歌",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "TenacityOfTheMillelith",
    "label": "千岩牢固",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "TheExile",
    "label": "流放者",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ThunderingFury",
    "label": "如雷的盛怒",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "Thundersoother",
    "label": "平息鸣雷的尊者",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "TinyMiracle",
    "label": "奇迹",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "TravelingDoctor",
    "label": "游医",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "UnfinishedReverie",
    "label": "未竟的遐思",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "VermillionHereafter",
    "label": "辰砂往生录",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "ViridescentVenerer",
    "label": "翠绿之影",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "VourukashasGlow",
    "label": "花海甘露之光",
    "setBonuses": [
      2,
      4
    ]
  },
  {
    "id": "WanderersTroupe",
    "label": "流浪大地的乐团",
    "setBonuses": [
      2,
      4
    ]
  }
] as const
