/**
 * Browser-safe weapon-name data pinned to the same 7.0 Genshin Optimizer commit as the
 * bundled game-data snapshot. Names are copied from the upstream Simplified Chinese aggregate,
 * generated from entries at `libs/gi/dm-localization/assets/locales/chs/weapon_<weaponId>_gen.json`.
 */
export const pinnedWeaponNameSource = {
  gameVersion: "7.0",
  localizationAggregatePath: "libs/gi/dm-localization/assets/locales/chs/weaponNames_gen.json",
  localizationPathTemplate:
    "libs/gi/dm-localization/assets/locales/chs/weapon_<weaponId>_gen.json",
  upstreamCommit: "98aafa1f135f086524b611c7d5b5bfb78d98bb6d",
  upstreamRepository: "https://github.com/frzyc/genshin-optimizer"
} as const

const officialThreeStarWeaponNames: Readonly<Record<string, string>> = Object.freeze({
  BlackTassel: "黑缨枪",
  BloodtaintedGreatsword: "沐浴龙血的剑",
  CoolSteel: "冷刃",
  DarkIronSword: "暗铁剑",
  DebateClub: "以理服人",
  EmeraldOrb: "翡玉法球",
  FerrousShadow: "铁影阔剑",
  FilletBlade: "吃虎鱼刀",
  Halberd: "钺矛",
  HarbingerOfDawn: "黎明神剑",
  MagicGuide: "魔导绪论",
  Messenger: "信使",
  OtherworldlyStory: "异世界行记",
  RavenBow: "鸦羽弓",
  RecurveBow: "反曲弓",
  SharpshootersOath: "神射手之誓",
  SkyriderGreatsword: "飞天大御剑",
  SkyriderSword: "飞天御剑",
  Slingshot: "弹弓",
  ThrillingTalesOfDragonSlayers: "讨龙英杰谭",
  TravelersHandySword: "旅行剑",
  TwinNephrite: "甲级宝珏",
  WhiteIronGreatsword: "白铁大剑",
  WhiteTassel: "白缨枪"
})

/**
 * Official Simplified Chinese names for every player-facing four- and five-star weapon in the
 * pinned 7.0 player-facing snapshot.
 */
export const officialWeaponNames: Readonly<Record<string, string>> = Object.freeze({
  ATeaspoonOfTranscendence: "超越之匙",
  AThousandBlazingSuns: "焚曜千阳",
  AThousandFloatingDreams: "千夜浮梦",
  Absolution: "赦罪",
  Akuoumaru: "恶王丸",
  AlleyHunter: "暗巷猎手",
  AmenomaKageuchi: "天目影打刀",
  AmosBow: "阿莫斯之弓",
  AngelosHeptades: "尘光七谕",
  AquaSimulacra: "若水",
  AquilaFavonia: "风鹰剑",
  AshGravenDrinkingHorn: "苍纹角杯",
  AstralVulturesCrimsonPlumage: "星鹫赤羽",
  AthameArtis: "黑蚀",
  Azurelight: "苍耀",
  BalladOfTheBoundlessBlue: "无垠蔚蓝之歌",
  BalladOfTheFjords: "峡湾长歌",
  BeaconOfTheReedSea: "苇海信标",
  BlackcliffAgate: "黑岩绯玉",
  BlackcliffLongsword: "黑岩长剑",
  BlackcliffPole: "黑岩刺枪",
  BlackcliffSlasher: "黑岩斩刀",
  BlackcliffWarbow: "黑岩战弓",
  BlackmarrowLantern: "乌髓孑灯",
  BloodsoakedRuins: "血染荒城",
  CalamityOfEshu: "厄水之祸",
  CalamityQueller: "息灾",
  CashflowSupervision: "金流监督",
  ChainBreaker: "碎链",
  CinnabarSpindle: "辰砂之纺锤",
  Cloudforged: "筑云",
  CompoundBow: "钢轮弓",
  CranesEchoingCall: "鹤鸣余音",
  CrescentPike: "流月针",
  CrimsonMoonsSemblance: "赤月之形",
  DawningFrost: "霜辰",
  Deathmatch: "决斗之枪",
  DialoguesOfTheDesertSages: "沙中伟贤的对答",
  DisasterAndRemorse: "灾悔",
  DodocoTales: "嘟嘟可故事集",
  DragonsBane: "匣里灭辰",
  DragonspineSpear: "龙脊长枪",
  EarthShaker: "撼地者",
  ElegyForTheEnd: "终末嗟叹之诗",
  EndOfTheLine: "竭泽",
  EngulfingLightning: "薙草之稻光",
  EtherlightSpindlelute: "天光的纺琴",
  EverlastingMoonglow: "不灭月华",
  EyeOfPerception: "昭心",
  FadingTwilight: "落霞",
  FangOfTheMountainKing: "山王长牙",
  FavoniusCodex: "西风秘典",
  FavoniusGreatsword: "西风大剑",
  FavoniusLance: "西风长枪",
  FavoniusSword: "西风剑",
  FavoniusWarbow: "西风猎弓",
  FesteringDesire: "腐殖之剑",
  FinaleOfTheDeep: "海渊终曲",
  FlameForgedInsight: "拾慧铸熔",
  FleuveCendreFerryman: "灰河渡手",
  FlowerWreathedFeathers: "缀花之翎",
  FlowingPurity: "纯水流华",
  FluteOfEzpitzal: "息燧之笛",
  FootprintOfTheRainbow: "虹的行迹",
  ForestRegalia: "森林王器",
  FracturedHalo: "支离轮光",
  FreedomSworn: "苍古自由之誓",
  Frostbearer: "忍冬之果",
  FruitOfFulfillment: "盈满之实",
  FruitfulHook: "硕果钩",
  GestOfTheMightyWolf: "狼的武功歌",
  GoldenFrostboundOath: "霜结的誓金枝",
  HakushinRing: "白辰之环",
  Hamayumi: "破魔之弓",
  HaranGeppakuFutsu: "波乱月白经津",
  HuntersPath: "猎人之径",
  IbisPiercer: "鹮穿之喙",
  IronSting: "铁蜂刺",
  JadefallsSplendor: "碧落之珑",
  KagotsurubeIsshin: "笼钓瓶一心",
  KagurasVerity: "神乐之真意",
  KatsuragikiriNagamasa: "桂木斩长正",
  KeyOfKhajNisut: "圣显之钥",
  KingsSquire: "王下近侍",
  KitainCrossSpear: "喜多院十文字",
  LightOfFoliarIncision: "裁叶萃光",
  LightbearingMoonshard: "朏魄含光",
  LionsRoar: "匣里龙吟",
  LithicBlade: "千岩古剑",
  LithicSpear: "千岩长枪",
  LostPrayerToTheSacredWinds: "四风原典",
  LumidouceElegy: "柔灯挽歌",
  LuxuriousSeaLord: "衔珠海皇",
  MailedFlower: "饰铁之花",
  MakhairaAquamarine: "玛海菈的水色",
  MappaMare: "万国诸海图谱",
  MasterKey: "万能钥匙",
  MemoryOfDust: "尘世之锁",
  MissiveWindspear: "风信之锋",
  MistsplitterReforged: "雾切之回光",
  MitternachtsWaltz: "幽夜华尔兹",
  Moonpiercer: "贯月矢",
  MoonweaversDawn: "织月者的曙色",
  MountainBracingBolt: "镇山之钉",
  MouunsMoon: "曚云之月",
  NightweaversLookingGlass: "纺夜天镜",
  NocturnesCurtainCall: "帷间夜曲",
  OathswornEye: "证誓之明瞳",
  PeakPatrolSong: "岩峰巡歌",
  PolarStar: "冬极白星",
  PortablePowerSaw: "便携动力锯",
  Predator: "掠食者",
  PrimordialJadeCutter: "磐岩结绿",
  PrimordialJadeWingedSpear: "和璞鸢",
  ProspectorsDrill: "勘探钻机",
  ProspectorsShovel: "掘金之锹",
  PrototypeAmber: "试作金珀",
  PrototypeArchaic: "试作古华",
  PrototypeCrescent: "试作澹月",
  PrototypeRancour: "试作斩岩",
  PrototypeStarglitter: "试作星镰",
  RainbowSerpentsRainBow: "虹蛇的雨弦",
  Rainslasher: "雨裁",
  RangeGauge: "测距规",
  RedhornStonethresher: "赤角石溃杵",
  ReliquaryOfTruth: "真语秘匣",
  RightfulReward: "公义的酬报",
  RingOfYaxche: "木棉之环",
  RoyalBow: "宗室长弓",
  RoyalGreatsword: "宗室大剑",
  RoyalGrimoire: "宗室秘法录",
  RoyalLongsword: "宗室长剑",
  RoyalSpear: "宗室猎枪",
  Rust: "弓藏",
  SacrificersStaff: "圣祭者的辉杖",
  SacrificialBow: "祭礼弓",
  SacrificialFragments: "祭礼残章",
  SacrificialGreatsword: "祭礼大剑",
  SacrificialJade: "遗祀玉珑",
  SacrificialSword: "祭礼剑",
  SapwoodBlade: "原木刀",
  ScionOfTheBlazingSun: "烈阳之嗣",
  SequenceOfSolitude: "冷寂迸音",
  SerenitysCall: "谧音吹哨",
  SerpentSpine: "螭骨剑",
  SilvershowerHeartstrings: "白雨心弦",
  SkywardAtlas: "天空之卷",
  SkywardBlade: "天空之刃",
  SkywardHarp: "天空之翼",
  SkywardPride: "天空之傲",
  SkywardSpine: "天空之脊",
  SnareHook: "罗网勾针",
  SnowTombedStarsilver: "雪葬的星银",
  SolarPearl: "匣里日月",
  SongOfBrokenPines: "松籁响起之时",
  SongOfStillness: "静谧之曲",
  SplendorOfTranquilWaters: "静水流涌之辉",
  StaffOfHoma: "护摩之杖",
  StaffOfTheScarletSands: "赤沙之杖",
  StarcallersWatch: "祭星者之望",
  SturdyBone: "弥坚骨",
  SummitShaper: "斫峰之刃",
  SunnyMorningSleepIn: "寝正月初晴",
  SurfsUp: "冲浪时光",
  SwordOfDescension: "降临之剑",
  SwordOfNarzissenkreuz: "水仙十字之剑",
  SymphonistOfScents: "香韵奏者",
  TalkingStick: "聊聊棒",
  TamayurateiNoOhanashi: "且住亭御咄",
  TheAlleyFlash: "暗巷闪光",
  TheBell: "钟剑",
  TheBlackSword: "黑剑",
  TheCatch: "「渔获」",
  TheDaybreakChronicles: "黎明破晓之史",
  TheDockhandsAssistant: "船坞长剑",
  TheFirstGreatMagic: "最初的大魔术",
  TheFlute: "笛剑",
  TheStringless: "绝弦",
  TheUnforged: "无工之剑",
  TheViridescentHunt: "苍翠猎弓",
  TheWidsith: "流浪乐章",
  ThunderingPulse: "飞雷之弦振",
  TidalShadow: "浪影阔剑",
  TomeOfTheEternalFlow: "万世流涌大典",
  ToukabouShigure: "东花坊时雨",
  TulaytullahsRemembrance: "图莱杜拉的回忆",
  UltimateOverlordsMegaMagicSword: "「究极霸王超级魔剑」",
  UrakuMisugiri: "有乐御簾切",
  Verdict: "裁断",
  VividNotions: "溢彩心念",
  VortexVanquisher: "贯虹之槊",
  WanderingEvenstar: "流浪的晚星",
  WavebreakersFin: "断浪长鳍",
  WaveridingWhirl: "乘浪的回旋",
  Whiteblind: "白影剑",
  WindblumeOde: "风花之颂",
  WineAndSong: "暗巷的酒与诗",
  WolfFang: "狼牙",
  WolfsGravestone: "狼的末路",
  XiphosMoonlight: "西福斯的月光",
  BladeOfAtonement: "救赎之斩",
  ClashOfKings: "群王局戏",
  CovenantOfFrostAndSnow: "霜雪誓约",
  EchoesOfTheHeart: "寸心余响",
  Emberwell: "引火之源",
  ExaiphanesBlade: "星锋剑",
  ForgedByTheGoldenMelody: "金律铸影",
  Frostbreath: "寒息",
  HereticsMoltenBlade: "熔猎异端之刃",
  JadeVista: "悬黎千钧",
  SongOfTheVigil: "戍望谣歌",
  WhitelakeFrostfeather: "白湖冬羽"
})

/** Returns the maintained official Simplified Chinese name, never an internal-ID fallback. */
export function getOfficialWeaponName(weaponId: string): string | undefined {
  return officialWeaponNames[weaponId] ?? officialThreeStarWeaponNames[weaponId]
}

/** Returns a name only when an official Simplified Chinese display name is maintained. */
export function requireOfficialWeaponName(weaponId: string): string {
  const name = getOfficialWeaponName(weaponId)
  if (name) return name
  throw new Error(`Missing official Simplified Chinese weapon name for ${weaponId}`)
}
