export {
  HUSK_OF_OPULENT_DREAMS_CURIOSITY_DEFENSE_PERCENT_PER_STACK,
  HUSK_OF_OPULENT_DREAMS_CURIOSITY_GEO_DAMAGE_BONUS_PER_STACK,
  HUSK_OF_OPULENT_DREAMS_DEFENSE_PERCENT,
  huskOfOpulentDreamsCombatActionEffects
} from "./effects.js"
