export {
  BLACKCLIFF_AGATE_ONE_STACK_ATTACK_PERCENT,
  BLACKCLIFF_AGATE_THREE_STACK_ATTACK_PERCENT,
  BLACKCLIFF_AGATE_TWO_STACK_ATTACK_PERCENT,
  blackcliffAgateCombatActionEffects
} from "./effects.js"
