export {
  A_THOUSAND_BLAZING_SUNS_ATTACK_PERCENT,
  A_THOUSAND_BLAZING_SUNS_CRIT_DAMAGE,
  A_THOUSAND_BLAZING_SUNS_NIGHTSOUL_ATTACK_PERCENT,
  A_THOUSAND_BLAZING_SUNS_NIGHTSOUL_CRIT_DAMAGE,
  aThousandBlazingSunsCombatActionEffects
} from "./effects.js"
