export {
  SNOW_TOMBED_STARSILVER_CRYO_AURA_PHYSICAL_COEFFICIENT,
  SNOW_TOMBED_STARSILVER_STANDARD_PHYSICAL_COEFFICIENT,
  SNOW_TOMBED_STARSILVER_TRIGGER_PROBABILITY,
  snowTombedStarsilverCombatActionEffects
} from "./effects.js"
