export {
  GILDED_DREAMS_ATTACK_PERCENT_PER_SAME_ELEMENT_TEAMMATE,
  GILDED_DREAMS_ELEMENTAL_MASTERY_PER_DIFFERENT_ELEMENT_TEAMMATE,
  GILDED_DREAMS_TWO_PIECE_ELEMENTAL_MASTERY,
  gildedDreamsCombatActionEffects
} from "./effects.js"
