export {
  CRIMSON_WITCH_OF_FLAMES_PYRO_DAMAGE_BONUS,
  CRIMSON_WITCH_OF_FLAMES_SKILL_CAST_EXTRA_PYRO_DAMAGE_BONUS_PER_STACK,
  CRIMSON_WITCH_OF_FLAMES_TRANSFORMATIVE_REACTION_DAMAGE_BONUS,
  crimsonWitchOfFlamesCombatActionEffects
} from "./effects.js"
