export {
  VOURUKASHAS_GLOW_HP_PERCENT,
  VOURUKASHAS_GLOW_SKILL_BURST_DAMAGE_BONUS,
  VOURUKASHAS_GLOW_SKILL_BURST_DAMAGE_BONUS_PER_DAMAGE_TAKEN_STACK,
  vourukashasGlowCombatActionEffects
} from "./effects.js"
