export {
  VERMILLION_HEREAFTER_AFTER_BURST_ATTACK_PERCENT,
  VERMILLION_HEREAFTER_AFTER_HP_LOSS_ATTACK_PERCENT,
  VERMILLION_HEREAFTER_ATTACK_PERCENT,
  vermillionHereafterCombatActionEffects
} from "./effects.js"
