export {
  VIRIDESCENT_VENERER_ANEMO_DAMAGE_BONUS,
  VIRIDESCENT_VENERER_SWIRL_REACTION_DAMAGE_BONUS,
  VIRIDESCENT_VENERER_SWIRLED_ELEMENT_RESISTANCE_REDUCTION,
  viridescentVenererCombatActionEffects
} from "./effects.js"
