export {
  DRAGONSPINE_SPEAR_CRYO_AURA_PHYSICAL_COEFFICIENT,
  DRAGONSPINE_SPEAR_STANDARD_PHYSICAL_COEFFICIENT,
  DRAGONSPINE_SPEAR_TRIGGER_PROBABILITY,
  dragonspineSpearCombatActionEffects
} from "./effects.js"
